### PR TITLE
Ensure and update debug image during upgrade

### LINKED ISSUE #4820: sidecar debug imagename missing after upgrade from 2.7
### What is the issue?
The image name is missing in the configmap for the debug sidecar after upgrading from 2.7 to 2.8.1

### How can it be reproduced?
I guess by installing a 2.7 and upgrading it ? DIdn't try to reproduce it again

### Logs, error output, etc

Here's the extract of the CM : 
```
proxy: |
    {"proxyImage":{"imageName":"gcr.io/linkerd-io/proxy","pullPolicy":"IfNotPresent"},"proxyInitImage":{"imageName":"gcr.io/linkerd-io/proxy-init","pullPolicy":"IfNotPresent"},"controlPort":{"port":4190},"ignoreInboundPorts":[],"ignoreOutboundPorts":[{"portRange":"25"},{"portRange":"587"},{"portRange":"3306"},{"portRange":"4222"},{"portRange":"6222"},{"portRange":"8086"},{"portRange":"8222"},{"portRange":"27017"}],"inboundPort":{"port":4143},"adminPort":{"port":4191},"outboundPort":{"port":4140},"resource":{"requestCpu":"100m","requestMemory":"20Mi","limitCpu":"1","limitMemory":"250Mi"},"proxyUid":"2102","logLevel":{"level":"warn,linkerd=info"},"disableExternalProfiles":true,"proxyVersion":"stable-2.8.1","proxyInitImageVersion":"v1.3.3","debugImage":**{"imageName":"","pullPolicy":"IfNotPresent"},"debugImageVersion":"**","destinationGetNetworks":""}
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system
√ multiple replicas of control plane pods

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √

```

### Environment

- Kubernetes Version: 1.16
- Cluster Environment: vsphere via kubespray
- Host OS: ubuntu18
- Linkerd version: 2.8.1

### Possible solution
add control to make sure the string isn't missing ?

### Additional context
The problem could come from a previous upgrade as I didn't use debug sidecars for a while

### PR DESCRIPTION
**Pull request by javaducky**
Some installations upgrading from versions prior to 2.7.x may have missing debug image name and version. This fix ensures that the default values are in place for this scenario and additionally upgrades the version of debug image with the control plane version.

Fixes #4820 

Signed-off-by: Paul Balogh <javaducky@gmail.com>

### CODE REVIEW

File: cli/cmd/upgrade_test.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ data:
...
+    {"proxyImage":{"imageName":"gcr.io/linkerd-io/proxy","pullPolicy":"IfNotPresent"},"proxyInitImage":{"imageName":"gcr.io/linkerd-io/proxy-init","pullPolicy":"IfNotPresent"},"controlPort":{"port":4190},"ignoreInboundPorts":[{"portRange":"2525-2527"},{"portRange":"25259"}],"ignoreOutboundPorts":[],"inboundPort":{"port":4143},"adminPort":{"port":4191},"outboundPort":{"port":4140},"resource":{"requestCpu":"","requestMemory":"","limitCpu":"","limitMemory":""},"proxyUid":"2102","logLevel":{"level":"warn,linkerd=info"},"disableExternalProfiles":true,"debugImage":{"imageName":"gcr.io/linkerd-io/debug","pullPolicy":"IfNotPresent"},"debugImageVersion":"edge-19.4.1","destinationGetNetworks":"DST-GET-NETWORKS"}
```
Comment (javaducky) [inline cli/cmd/upgrade_test.go:60]: These changes verify that a previous image version is upgraded to the newer version.

File: cli/cmd/uninject_test.go [hunk 2]
```diff
@@ -111,7 +111,7 @@ func TestUninjectYAML(t *testing.T) {
 
 			exitCode := runUninjectCmd(read, report, output, nil)
 			if exitCode != 0 {
-				t.Errorf("Failed to inject %s\n", tc.inputFileName)
+				t.Errorf("Failed to uninject %s\n", tc.inputFileName)
```
Comment (javaducky) [inline cli/cmd/uninject_test.go:114]: Bonus!

File: cli/cmd/upgrade.go [hunk 3]
```diff
@@ -420,6 +420,12 @@ func repairConfigs(configs *pb.All) {
 	if configs.Proxy.DebugImage == nil {
 		configs.Proxy.DebugImage = &pb.Image{}
 	}
+	if configs.GetProxy().GetDebugImage().GetImageName() == "" {
+		configs.Proxy.DebugImage.ImageName = k8s.DebugSidecarImage
+	}
+	if configs.GetProxy().GetDebugImageVersion() == "" {
+		configs.Proxy.DebugImageVersion = version.Version
+	}
```
Comment (javaducky) [inline cli/cmd/upgrade.go:428]: Old versions of control plane did not have the debugImage info in the protobuf, so for example, upgrades from 2.6 -> 2.7 wound up with empty image name and version causing the issue.
