### PR TITLE
cli: make `linkerd uninstall` fail when injected pods are present

### LINKED ISSUE #5622: `linkerd uninstall` should fail when injected resources are present
Running `linkerd uninstall` on a cluster with injected resources can leave the cluster in a bad state (i.e. because pods will be unable to discover the control plane). `linkerd uninstall` should error out with a warning when there are injected resources on the cluster (i.e. including extensions).

We should provide a `--force` flag to ignore the cluster state and run removal anyway.

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #5622

This PR updates the `linkerd uninstall` cmd to check if there
are any injected pods and fails if there are any. This also
provides `--force` flag to skip this check.

pods from the control-plane namespace are skipped
so as to not error out for control-plane pods.

This PR also fixes `viz uninstall` and updates the
uninstall integration test to use it.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

File: cli/cmd/uninstall.go [hunk 1]
```diff
@@ -25,18 +28,34 @@ func newCmdUninstall() *cobra.Command {
...
+			}
+
+			if !force {
+				podsList, err := k8sAPI.CoreV1().Pods("").List(cmd.Context(), metav1.ListOptions{})
+				if err != nil {
+					return err
+				}
+				for _, pod := range podsList.Items {
+					// Skip core control-plane and extension namespaces when checking for proxies
+					if !strings.HasPrefix(pod.Namespace, "linkerd") && healthcheck.ContainsProxy(pod) {
```
Comment (alpeb) [inline cli/cmd/uninstall.go:44]: I think you can tap here into the `linkerd-namespace` flag instead of relying on the hard-coded value. Also, according to the requirement in #5622, this should also check for injected pods in extensions, so a strict comparison against the linkerd namespace might be enough.

File: cli/cmd/uninstall.go [hunk 2]
```diff
@@ -25,18 +28,34 @@ func newCmdUninstall() *cobra.Command {
...
+						return fmt.Errorf("Please uninject proxy containers before uninstalling the control-plane")
+					}
+				}
+			}
+
+			return uninstallRunE(cmd.Context(), k8sAPI)
 		},
 	}
 
+	cmd.Flags().BoolVarP(&force, "force", "f", force, "Enable this to perform a forced uninstall")
```
Comment (alpeb) [inline cli/cmd/uninstall.go:54]: Can you use a more explicit description, like "Force uninstall even if there exist non-control-plane injected pods"?

File: cli/cmd/uninstall.go [hunk 3]
```diff
@@ -25,18 +27,34 @@ func newCmdUninstall() *cobra.Command {
...
+
+			if !force {
+				podsList, err := k8sAPI.CoreV1().Pods("").List(cmd.Context(), metav1.ListOptions{})
+				if err != nil {
+					return err
+				}
+				for _, pod := range podsList.Items {
+					// Skip core control-plane namespace
+					if pod.Namespace != controlPlaneNamespace && healthcheck.ContainsProxy(pod) {
+						return fmt.Errorf("Please uninject proxy containers before uninstalling the control-plane")
```
Comment (kleimkuhler) [inline cli/cmd/uninstall.go:44]: Instead of returning an error here, I think something like the below would be good:

```suggestion
						fmt.Fprintln(os.Stderr, "Please uninject proxy containers before uninstalling the control-plane")
						os.Exit(1)
```

That way, we are not printing the usage text since it's not really a "usage" issue here. We do this in a few other places of the CLI and probably should try to do it more. There is an open issue for it.

With this change:

```
❯ ./bin/go-run cli uninstall
Please uninject proxy containers before uninstalling the control-plane
```

**Review by kleimkuhler — COMMENTED** [review]
This works well for me. I left a comment about handling the error case.

Something to consider is since we are looping through all pods already, could we be a little more specific about which pods (or even which namespaces) contain pods that still need to be uninjected?

This is kind of similar to the `check` change where we warn about specific pods that may not have tap or tracing configured correctly. It may be helpful here to be able to say "these are the pods that need to uninjected" instead of sending them on a search in their cluster.

File: cli/cmd/uninstall.go [hunk 4]
```diff
@@ -25,18 +27,34 @@ func newCmdUninstall() *cobra.Command {
...
 		RunE: func(cmd *cobra.Command, args []string) error {
-			return uninstallRunE(cmd.Context())
+
+			k8sAPI, err := k8s.NewAPI(kubeconfigPath, kubeContext, impersonate, impersonateGroup, 0)
+			if err != nil {
+				return err
+			}
+
+			if !force {
+				podsList, err := k8sAPI.CoreV1().Pods("").List(cmd.Context(), metav1.ListOptions{})
```
Comment (adleong) [inline cli/cmd/uninstall.go:37]: You can use a label selector to find data plane pods specifically: 
```
podList, err := api.CoreV1().Pods(dataPlaneNamespace).List(ctx, metav1.ListOptions{LabelSelector: k8s.ControllerNSLabel})
```
similar to what is done in `healthcheck.GetMeshedPodsIdentityData`

File: cli/cmd/uninstall.go (hunk 3 above)
Comment (adleong) [inline cli/cmd/uninstall.go:44]: We could collect the offending pods into a slice so that we can print the list of pods which need to be uninjected.

Comment (Pothulapati) [reply cli/cmd/uninstall.go:44]: Makes sense.

File: cli/cmd/uninstall.go (hunk 4 above)
Comment (Pothulapati) [reply cli/cmd/uninstall.go:37]: This makes sense. This way we don't have to do check if there is a proxy as having this label confirms that injection happened.

File: cli/cmd/uninstall.go [hunk 5]
```diff
@@ -34,16 +34,23 @@ This command provides all Kubernetes namespace-scoped and cluster-scoped resourc
...
-				for _, pod := range podsList.Items {
-					// Skip core control-plane namespace
-					if pod.Namespace != controlPlaneNamespace && healthcheck.ContainsProxy(pod) {
-						return fmt.Errorf("Please uninject proxy containers before uninstalling the control-plane")
+
+				var injectedPods []string
+				for _, pod := range podList.Items {
+					// skip core control-plane namespace
+					if pod.Namespace != controlPlaneNamespace {
+						injectedPods = append(injectedPods, fmt.Sprintf("* %s", pod.Name))
```
Comment (kleimkuhler) [inline cli/cmd/uninstall.go:46]: Could be nice including namespace here? Something like:

```
Please uninject the following pods before uninstalling the control-plane:
        * linkerd-tap-7df756764b-lqzkr
```

Turns into:

```
Please uninject the following pods before uninstalling the control-plane:
        * linkerd-viz/linkerd-tap-7df756764b-lqzkr
```

I realize we don't do this in `check --proxy` output either though so definitely not a blocker.

**Review by kleimkuhler — APPROVED** [review]
Awesome works well 🤙

**Review by adleong — APPROVED** [review]

File: cli/cmd/uninstall.go (hunk 5 above)
Comment (Pothulapati) [reply cli/cmd/uninstall.go:46]: Yep, Good suggestion. Will raise a separate PR fixing this everywhere.
