### PR TITLE
Fix issue with EdgesTable Grid wrapper

### LINKED ISSUE #3601: In mobile, font size when looking at a pod details is smaller
In mobile view (both portrait and landscape) the font size when in the pod details screen is smaller, both for the sidebar and the main section.

I reproduced this with Edge-19.10.3 and in #3547, using Chrome's mobile simulator

View in any section but the pod details:
image

View when looking at a pod details:
image

### PR DESCRIPTION
**Pull request by cynthia-sg**
Remove `Grid` wrapper around `EdgesTable` component in resource detail page.

  Fixes #3601

image

Signed-off-by: Cintia Sanchez Garcia <cynthiasg@icloud.com>

### CODE REVIEW

File: web/app/js/components/ResourceDetail.jsx [hunk 1]
```diff
@@ -380,15 +380,11 @@ export class ResourceDetailBase extends React.Component {
           isTcpTable={true}
           metrics={this.state.podMetrics} />
 
-        <Grid container direction="column" justify="center">
-          <Grid item>
```
Comment (cynthia-sg) [inline web/app/js/components/ResourceDetail.jsx]: Another solution would be to add prop `xs={12}` to Grid item, but I think that removing these extra `Grids` is better.

**Comment by scottcarol** [comment]
Great fix! To test this PR, I used the Chrome DevTools "Toggle Device Toolbar" button:
Screen Shot 2019-11-25 at 3 15 58 PM

to toggle mobile view. I looked at the detail page for a Pod in `master` and see that the `Edges` table is wider than the screen, unlike other tables, which is also affecting the sidebar font size:

Screen Shot 2019-11-25 at 3 20 29 PM

then I looked at the detail page in this branch and saw that the `Edges` table is formatted properly, and the sidebar font size stays consistent.

Screen Shot 2019-11-25 at 3 17 57 PM
