### PR TITLE
[fixed] : Excessive logging when encountering "unimplemented resource type" errors in injector webhook

### LINKED ISSUE #12186: Excessive logging when encourering "unimplemented resource type" errors in injector webhook
### What is the issue?

This is more of an annoyance rather than an actual bug.

I'm running KEDA with ScaledJob custom resources and these own Kubernetes Job resources for which pods we have linkerd inject sidecards. The problem is that every time the webhook handles these resources it logs something like this:

```
{"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:06:45Z"}
```

These logs are completely harmless but they are very annoying especially if the ScaledJob is triggered very frequently.

### How can it be reproduced?

You can see this happen for any CRD resource that is designed to own a workload-type resource. KEDA's ScaledJob is a good candidate.

### Logs, error output, etc

```
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:21Z"}
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:21Z"}
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:24Z"}
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:30Z"}
```

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

Silently handle these "unimplemented resource type" errors, or just log them as debug instead of warn.

https://github.com/linkerd/linkerd2/blob/c1fcbbafb2c15557f33e95dd609651cf92757d24/controller/proxy-injector/webhook.go#L76-L78

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by Adarsh-jaiss**
- This PR fixes #12186

### CODE REVIEW

**Comment by Adarsh-jaiss** [comment]
Hey @mateiidavid, here's a fresh PR :)

**Review by adleong — APPROVED** [review]
Thanks @Adarsh-jaiss!  I'd encourage even taking this further and changing this to trace level. Logging a line each time we skip injecting a resource that we don't support is not particularly useful when debugging.

**Comment by Adarsh-jaiss** [comment]
> Thanks @Adarsh-jaiss! I'd encourage even taking this further and changing this to trace level. Logging a line each time we skip injecting a resource that we don't support is not particularly useful when debugging.

I think for adding a trace level, we can Implement logrus, and can changes that line something like this
```
if err != nil {
		log.Tracef("skipping event for parent %s: %s", ownerRef.Kind, err)
}
```

what are your views on this?

File: controller/proxy-injector/webhook.go [hunk 1]
```diff
@@ -74,7 +74,7 @@ func Inject(linkerdNamespace string) webhook.Handler {
 		if ownerRef := resourceConfig.GetOwnerRef(); ownerRef != nil {
 			res, err := k8s.GetAPIResource(ownerRef.Kind)
 			if err != nil {
-				log.Warningf("skipping event for parent %s: %s", ownerRef.Kind, err)
+				log.Debugf("skipping event for parent %s: %s", ownerRef.Kind, err)
```
Comment (mateiidavid) [inline controller/proxy-injector/webhook.go:77]: This should change the level to trace. I agree it's a better choice.

```suggestion
				log.Tracef("skipping event for parent %s: %s", ownerRef.Kind, err)
```

Comment (Adarsh-jaiss) [reply controller/proxy-injector/webhook.go:77]: Hey @mateiidavid , I have already did the changes on my local development environment, rebased the commits , but i am facing problems in pushing the code :

```
adarsh@chiku:~/myfiles/OpenSource/linkerd2$ git push -u origin webhook-bug 
To https://github.com/Adarsh-jaiss/linkerd2.git
 ! [rejected]            webhook-bug -> webhook-bug (non-fast-forward)
error: failed to push some refs to 'https://github.com/Adarsh-jaiss/linkerd2.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

and to fix this whenever i am running `git pull origin webhook-bug`, a merge conflict is getting arised and it isn't getting resolved, i have been trying to fix it since morning!

This happened last time as well in the previous PR, if you could help me out, that would be very kind of you :)

Comment (mateiidavid) [reply controller/proxy-injector/webhook.go:77]: mm have you tried `git pull origin webhook-bug --strategy=recursive -X theirs`?

Comment (Adarsh-jaiss) [reply controller/proxy-injector/webhook.go:80]: I tried this and merged the changes in my codebase, and still now working!

Is there any other way?

File: controller/proxy-injector/webhook.go [hunk 2]
```diff
@@ -36,6 +38,7 @@ func Inject(linkerdNamespace string) webhook.Handler {
 		recorder record.EventRecorder,
 	) (*admissionv1beta1.AdmissionResponse, error) {
 		log.Debugf("request object bytes: %s", request.Object.Raw)
+		log.SetLevel(logrus.TraceLevel)
```
Comment (olix0r) [inline controller/proxy-injector/webhook.go:41]:
```suggestion
```
