### PR TITLE
tests: Add TestOverridesSecret integration test

### LINKED ISSUE #5670: tests: check for overrides secret during upgrades
## Bug Report

To prevent things like #5646, We should make the upgrade integration tests check for changes in the secret so that we can verify whatever overrides are applied, are being stored correctly.

This can't be added as part of #5653 as the current upgrade tests are based on the edge release, and hence a separate PR can be raised once an edge is released with those changes.

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #5670

This PR adds a new test under install tests called
`TestOverridesSecret` which reads the overrides secret
stored in the cluster and then checks if the relevant overrides
that are passed through helm override flags and CLi flags
are present or not.

Currently, Helm overrides flags are only available with the
edge releases and hence these flags are gated based on the version
in the install logic.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

File: bin/_test-helpers.sh [hunk 1]
```diff
@@ -362,7 +362,14 @@ install_version() {
 
     (
         set -x
-        "$linkerd_path" install | kubectl --context="$context" apply -f - 2>&1
+        # TODO: Use a mix of helm override flags and CLI flags and remove this condition
+        # once stable-2.10 is out
+        edge_regex='(edge)-([0-9]+\.[0-9]+\.[0-9]+)'
+        if [[ "$version" =~ $edge_regex ]]; then
+          "$linkerd_path" install --set proxyInit.ignoreInboundPorts="1234\,5678" --set controllerLogLevel=debug | kubectl --context="$context" apply -f - 2>&1
```
Comment (alpeb) [inline bin/_test-helpers.sh:369]: can you use a mix of helm and non-helm flags here?

File: test/integration/install_test.go [hunk 2]
```diff
@@ -670,6 +672,77 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
 	}
 }
 
+func TestOverridesSecret(t *testing.T) {
+
+	// Skip if Helm integration test
+	if TestHelper.IsHelm() {
+		t.Skip("Skipping as this is not a helm upgrade test")
+	}
```
Comment (alpeb) [inline test/integration/install_test.go:680]: If you're introducing `TestHelper.IsHelm()`, would you update the other checks above to also us this same function?
Also, I think the code comment is not necessary :wink:

File: test/integration/install_test.go [hunk 3]
```diff
@@ -349,7 +351,7 @@ func TestInstallOrUpgradeCli(t *testing.T) {
 		}
 
 		// prepare for stage 2
-		args = append([]string{"control-plane", "--addon-overwrite"}, args...)
+		args = append([]string{"control-plane", "--skip-outbound-ports", skippedOutboundPorts}, args...)
```
Comment (alpeb) [inline test/integration/install_test.go:354]: Also can you add here helm-style flags as well?

**Review by alpeb — COMMENTED** [review]
Looking good :+1: 
Can you also iterate over `overridesTree` keys to make sure there are no unintended entries? E.g. last time we discovered `stage` was sneaking in.

File: test/integration/install_test.go (hunk 3 above)
Comment (Pothulapati) [reply test/integration/install_test.go:354]: I don't think so. because this part is invoked both with `upgrade-edge` and `upgrade-stable` which would mean `upgrade-stable would fail`. Is there a way to gate this to be only for the edges?

File: test/integration/install_test.go (hunk 2 above)
Comment (Pothulapati) [reply test/integration/install_test.go]: I don't think we can replace the checks above. As in those cases, They want to skip only if the test is a helm upgrade test. In this case, We have to skip in all cases where Helm is involved as there is no overrides secret available with helm.

Also, updated the skip description to be more verbose.

File: bin/_test-helpers.sh (hunk 1 above)
Comment (Pothulapati) [reply bin/_test-helpers.sh]: Makes sense. Updated.

File: bin/_test-helpers.sh [hunk 4]
```diff
@@ -362,7 +362,14 @@ install_version() {
 
     (
         set -x
-        "$linkerd_path" install | kubectl --context="$context" apply -f - 2>&1
+        # TODO: Use a mix of helm override flags and CLI flags and remove this condition
+        # once stable-2.10 is out
```
Comment (kleimkuhler) [inline bin/_test-helpers.sh:366]: Can you make an issue for this? A TODO is a little easy to forget and I think this is definitely something that will be good to test as soon as the stable is out.

**Review by kleimkuhler — APPROVED** [review]
Left a comment about returning to this once the stable is out, but otherwise looks good!

File: test/integration/install_test.go (hunk 2 above)
Comment (alpeb) [reply test/integration/install_test.go]: Sorry for my vague suggestion. I mean replacing `TestHelper.GetHelmReleaseName() (=|!)= ""` with `TestHelper.IsHelm()`. And while you're at it actually remove the `GetHelmReleaseName()` method declaration and the associated `helmReleaseName` property in `test_helper.go` as they won't be used at all,

File: test/integration/install_test.go (hunk 3 above)
Comment (alpeb) [reply test/integration/install_test.go:354]: .... well, there's `TestHelper.UpgradeFromVersion()`, which could be augmented through some wrapper checking if it corresponds to an edge or a stable...

File: test/integration/install_test.go (hunk 2 above)
Comment (Pothulapati) [reply test/integration/install_test.go]: I removed `GetHelmReleaseName()` but was not able to remove `helm.releaseName` as the release name is used with helm upgrades, etc. So, Makes sense to have it still. WDYT?

File: test/integration/install_test.go (hunk 3 above)
Comment (Pothulapati) [reply test/integration/install_test.go:354]: Ahh, Let me try. Also, Def feels like an important test to check if things are actually persisted after upgrades.

File: test/integration/install_test.go (hunk 2 above)
Comment (Pothulapati) [reply test/integration/install_test.go]: Okay, I changed it to use `GetHelmReleaseName` isntead of my new `IsHelm` as it was breaking some stuff. Looks like `releaseName` is a better toggle to rely on then helm binary

**Comment by kleimkuhler** [comment]
CI should be good after a `main` merge

**Comment by Pothulapati** [comment]
> Can you also iterate over overridesTree keys to make sure there are no unintended entries? E.g. last time we discovered stage was sneaking in.

That definitely seems useful. Currently working on it.

File: test/integration/install_test.go [hunk 5]
```diff
@@ -359,7 +363,17 @@ func TestInstallOrUpgradeCli(t *testing.T) {
...
 		// prepare for stage 2
-		args = append([]string{"control-plane", "--addon-overwrite"}, args...)
+		args = append([]string{"control-plane"}, args...)
+		edge, err := regexp.Match(`(edge)-([0-9]+\.[0-9]+\.[0-9]+)`, []byte(TestHelper.UpgradeFromVersion()))
+		if err != nil {
+			testutil.AnnotatedFatal(t, "could not match regex", err)
+		}
+
+		if edge {
+			args = append(args, []string{"--set", fmt.Sprintf("proxyInit.ignoreOutboundPorts=\"%s\"", strings.Replace("1234,5678", ",", "\\,", 1))}...)
```
Comment (alpeb) [inline test/integration/install_test.go:373]:
```suggestion
			args = append(args, []string{"--set", fmt.Sprintf("proxyInit.ignoreOutboundPorts=\"%s\"", strings.Replace(skippedOutboundPorts, ",", "\\,", 1))}...)
```

File: test/integration/install_test.go [hunk 6]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+	overrides := configOverridesSecret.Data["linkerd-config-overrides"]
+	overridesTree, err := tree.BytesToTree(overrides)
+	if err != nil {
+		testutil.AnnotatedFatalf(t, "could not retrieve linkerd-config-overrides",
+			"could not retrieve linkerd-config-overrides\n%s", err.Error())
+	}
+
+	// Check for fields that were added during install
+	testCases := []struct {
+		tree  tree.Tree
```
Comment (alpeb) [inline test/integration/install_test.go:717]: Why parametrizing `tree` if it's always `overridesTree`?

File: test/integration/install_test.go [hunk 7]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+	}{
+		{
+			overridesTree,
+			[]string{"controllerLogLevel"},
+			"debug",
+		},
+		{
+			overridesTree,
+			[]string{"proxyInit", "ignoreInboundPorts"},
+			"1234,5678",
```
Comment (alpeb) [inline test/integration/install_test.go:729]:
```suggestion
			skippedInboundPorts,
```

File: test/integration/install_test.go [hunk 8]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+	if TestHelper.UpgradeFromVersion() != "" {
+		testCases = append(testCases, []struct {
+			tree  tree.Tree
+			path  []string
+			value string
+		}{
+			{
+				overridesTree,
+				[]string{"proxyInit", "ignoreOutboundPorts"},
+				"1234,5678",
```
Comment (alpeb) [inline test/integration/install_test.go:743]:
```suggestion
				skippedOutboundPorts,
```

File: test/integration/install_test.go [hunk 9]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+		}...)
+	}
+
+	for _, tc := range testCases {
+		tc := tc // pin
+		t.Run(fmt.Sprintf("%s: %s", strings.Join(tc.path, "/"), tc.value), func(t *testing.T) {
+			finalValue, err := tc.tree.GetString(tc.path...)
+			if err != nil {
+				testutil.AnnotatedFatalf(t, "could not perform tree.GetString",
+					"could not perform tree.GetString\n%s", err.Error())
```
Comment (alpeb) [inline test/integration/install_test.go:754]:
```suggestion
					"could not perform tree.GetString\n%s", err)
```

File: test/integration/install_test.go [hunk 10]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+func TestOverridesSecret(t *testing.T) {
+
+	if TestHelper.GetHelmReleaseName() != "" {
+		t.Skip("Skipping as this is a helm test where linkerd-config-overrides is absent")
+	}
+
+	configOverridesSecret, err := TestHelper.KubernetesHelper.GetSecret(context.Background(), TestHelper.GetLinkerdNamespace(), "linkerd-config-overrides")
+	if err != nil {
+		testutil.AnnotatedFatalf(t, "could not retrieve linkerd-config-overrides",
+			"could not retrieve linkerd-config-overrides\n%s", err.Error())
```
Comment (alpeb) [inline test/integration/install_test.go:705]: `.Error()` not needed
```suggestion
			"could not retrieve linkerd-config-overrides\n%s", err)
```

File: test/integration/install_test.go [hunk 11]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+	}
+
+	overrides := configOverridesSecret.Data["linkerd-config-overrides"]
+	overridesTree, err := tree.BytesToTree(overrides)
+	if err != nil {
+		testutil.AnnotatedFatalf(t, "could not retrieve linkerd-config-overrides",
+			"could not retrieve linkerd-config-overrides\n%s", err.Error())
```
Comment (alpeb) [inline test/integration/install_test.go:712]:
```suggestion
			"could not retrieve linkerd-config-overrides\n%s", err)
```

File: test/integration/install_test.go [hunk 12]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+					strings.Join(tc.path, "/"), tc.value, finalValue)
+			}
+		})
+	}
+
+	panicIfError := func(t *testing.T, f func(...string) (string, error), path ...string) string {
+		val, err := f(path...)
+		if err != nil {
+			testutil.AnnotatedFatalf(t, err.Error(),
+				err.Error(), err.Error())
```
Comment (alpeb) [inline test/integration/install_test.go:769]:
```suggestion
			testutil.AnnotatedFatalf(t, "error calling tree.GetString()", "error calling tree.GetString(): %s", err)
```

File: test/integration/install_test.go [hunk 13]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+
+	t.Run("Check if any unknown fields sneaked in", func(t *testing.T) {
+		knownKeys := tree.Tree{
+			"controllerLogLevel": "debug",
+			"identity": map[string]interface{}{
+				"issuer": map[string]interface{}{},
+			},
+			"identityTrustAnchorsPEM": panicIfError(t, overridesTree.GetString, []string{"identityTrustAnchorsPEM"}...),
+			"proxyInit": map[string]interface{}{
+				"ignoreInboundPorts": "1234,5678",
```
Comment (alpeb) [inline test/integration/install_test.go:784]:
```suggestion
				"ignoreInboundPorts": skippedInboundPorts,
```

File: test/integration/install_test.go [hunk 14]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+			},
+		}
+
+		// Check for fields that were added during upgrade
+		if TestHelper.UpgradeFromVersion() != "" {
+			knownKeys["proxyInit"].(map[string]interface{})["ignoreOutboundPorts"] = "1234,5678"
```
Comment (alpeb) [inline test/integration/install_test.go:790]:
```suggestion
			knownKeys["proxyInit"].(map[string]interface{})["ignoreOutboundPorts"] = skippedOutboundPorts
```

File: test/integration/install_test.go [hunk 15]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+		return val
+	}
+
+	t.Run("Check if any unknown fields sneaked in", func(t *testing.T) {
+		knownKeys := tree.Tree{
+			"controllerLogLevel": "debug",
+			"identity": map[string]interface{}{
+				"issuer": map[string]interface{}{},
+			},
+			"identityTrustAnchorsPEM": panicIfError(t, overridesTree.GetString, []string{"identityTrustAnchorsPEM"}...),
```
Comment (alpeb) [inline test/integration/install_test.go:782]: In this call and all the others below, you can pass a list of args instead of having to build a slice.

File: test/integration/install_test.go [hunk 16]
```diff
@@ -679,6 +693,138 @@ func TestRetrieveUidPostUpgrade(t *testing.T) {
...
+
+			if tc.value != finalValue {
+				testutil.AnnotatedFatalf(t, fmt.Sprintf("Values at path %s do not match", strings.Join(tc.path, "/")),
+					"Expected value at [%s] to be [%s] but received [%s]",
+					strings.Join(tc.path, "/"), tc.value, finalValue)
+			}
+		})
+	}
+
+	panicIfError := func(t *testing.T, f func(...string) (string, error), path ...string) string {
```
Comment (alpeb) [inline test/integration/install_test.go:765]: Given `f` will always be `overridesTree.GetString` you can just omit that param and call `overridesTree.GetString()` directly.

Comment (alpeb) [reply test/integration/install_test.go:765]: Also, I think a better name for the function would be `extractValue` or something like that...

**Review by alpeb — COMMENTED** [review]
This looks like it covers all the bases :+1: 
Just a bunch of nits below :grimacing:

**Review by alpeb — APPROVED** [review]
Thanks @Pothulapati , this looks good to me :+1:
