### PR TITLE
Apply overrides to chart values on install #15025

### LINKED ISSUE #15025: Linkerd upgrade fails when using an externalCA
### What is the issue?

I have setup cert-manager along with the required trust-achor and identity issuer as described in the documentation. Then I installed the linkerd CRDs and finally installed the control plane via (edge-26.1.1):
```
linkerd install \
  --ha \
  --set proxy.metrics.hostnameLabels=true \
  --set identity.externalCA=true \
  --set identity.issuer.scheme=kubernetes.io/tls \
  --set policyValidator.externalSecret=true \
  --set policyValidator.injectCaFrom=cert-manager/webhook-ca \
  --set proxyInjector.externalSecret=true \
  --set proxyInjector.injectCaFrom=cert-manager/webhook-ca \
  --set profileValidator.externalSecret=true \
  --set profileValidator.injectCaFrom=cert-manager/webhook-ca \
  --ignore-cluster
```

When I run the upgrade (edge-26.3.1), I get the following error:
```
% ./linkerd2-cli-edge-26.3.1-linux-amd64  upgrade
--identity-issuer-certificate-file must not be specified if --identity-external-issuer=true
```

The current version 26.1.1 is working fine with our app namespaces llinkerd inject enabled.

I have setup a second test EKS cluster and deployed everything from scratch and I get the same error.

### How can it be reproduced?

I have setup a second test EKS cluster and deployed everything from scratch (cert-manager, certs, CRDs, control-plane). Everything is working fine, but runinng the upgarde command gives me the same error.

### Logs, error output, etc

```
--identity-issuer-certificate-file must not be specified if --identity-external-issuer=true
```

### output of `linkerd check -o short`

```
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2026-03-11T16:31:18Z
    see https://linkerd.io/2/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2026-03-11T16:31:18Z
    see https://linkerd.io/2/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2026-03-11T16:31:17Z
    see https://linkerd.io/2/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints
‼ policy-validator cert is valid for at least 60 days
    certificate will expire on 2026-03-11T16:31:19Z
    see https://linkerd.io/2/checks/#l5d-policy-validator-webhook-cert-not-expiring-soon for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 26.1.1 but the latest edge version is 26.3.1
    see https://linkerd.io/2/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running edge-26.1.1 but cli running edge-26.3.1
    see https://linkerd.io/2/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-79dd489695-dkw5w (edge-26.1.1)
	* linkerd-destination-79dd489695-skkq2 (edge-26.1.1)
	* linkerd-destination-79dd489695-xktvq (edge-26.1.1)
	* linkerd-identity-77695c449d-9fnxw (edge-26.1.1)
	* linkerd-identity-77695c449d-p5mmw (edge-26.1.1)
	* linkerd-identity-77695c449d-wtq8d (edge-26.1.1)
	* linkerd-proxy-injector-68bfc6ccbf-n4mg8 (edge-26.1.1)
	* linkerd-proxy-injector-68bfc6ccbf-s2fk9 (edge-26.1.1)
	* linkerd-proxy-injector-68bfc6ccbf-w72dm (edge-26.1.1)
    see https://linkerd.io/2/checks/#l5d-cp-proxy-version for hints
‼ control plane proxies and cli versions match
    linkerd-destination-79dd489695-dkw5w running edge-26.1.1 but cli running edge-26.3.1
    see https://linkerd.io/2/checks/#l5d-cp-proxy-cli-version for hints
```

### Environment

- k8s: 1.34
- Cluster: EKS
- host OS: amazon linux 2023
- linkerd version: edge-26.1.1

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by raykroeker**
Running `linkerd upgrade` fails after running install with an external ca.  The issue presents at upgrade but the cause is due to install incorrectly initializing the chart values for identity, specifically it initializes the issuer versus querying for one that is already set.

```bash
linkerd install \
  --ha \
  --set proxy.metrics.hostnameLabels=true \
  --set identity.externalCA=true \
  --set identity.issuer.scheme=kubernetes.io/tls \
  --set policyValidator.externalSecret=true \
  --set policyValidator.injectCaFrom=cert-manager/webhook-ca \
  --set proxyInjector.externalSecret=true \
  --set proxyInjector.injectCaFrom=cert-manager/webhook-ca \
  --set profileValidator.externalSecret=true \
  --set profileValidator.injectCaFrom=cert-manager/webhook-ca \
  --ignore-cluster
```

The install process did not apply the '--set' command line options onto internal values state before attempting to initialize the issuer credentials.

 * The change applies the overrides to the values before initialize.
 * Add test code to cover initializeIssuerCredentials.
 * Track unit test run history in 'go-test.json' in the root directory when running in the justfile.
 * Ignore 'go-test.json.'
 * Add testify assertions as a go module.

Added unit test and ran through the integration test suite.

Fixes #15025

### CODE REVIEW

File: cli/cmd/install.go [hunk 1]
```diff
@@ -303,6 +303,18 @@ func installControlPlane(ctx context.Context, k8sAPI *k8s.KubernetesAPI, w io.Wr
...
 	}
 
+	// in order to correctly initialize the issuer credentials the overrides
+	// (from above) need to be set/applied to the values themselves
+	// specifically identity issuer scheme, and trust values
+	data, err := yaml.Marshal(valuesOverrides)
+	if err != nil {
+		return err
+	}
+	err = yaml.Unmarshal(data, values)
```
Comment (adleong) [inline cli/cmd/install.go:316]: This relies on the "partial unmarshal" behavior where existing fields in `values` will be retained with their value if the field is not present in `data`.  This is a bit subtle and in a casual reading of this code, one might expect `values` to be completely replaced by `data`.  I think this could use a comment.

File: go.mod [hunk 2]
```diff
@@ -14,6 +14,7 @@ require (
 	github.com/fatih/color v1.19.0
 	github.com/fsnotify/fsnotify v1.9.0
 	github.com/go-openapi/spec v0.22.4
+	github.com/go-openapi/testify/v2 v2.4.0
```
Comment (adleong) [inline go.mod]: I hesitate to introduce a new testing library that is used here but not throughout the project.  I'd prefer to evaluate testify independently of this PR.  Can the test here be written without it?

File: cli/cmd/install_test.go [hunk 3]
```diff
@@ -314,6 +316,246 @@ func TestRender(t *testing.T) {
...
+	// issuer trust anchor and tls crt+key as a secret.
+	newK8S := func(opts values.Options) *k8s.KubernetesAPI {
+		t.Helper()
+		buf := &bytes.Buffer{}
+		err := renderCRDs(context.Background(), nil, buf, opts, "yaml")
+		if err != nil {
+			t.Fatalf("cannot render-crds for new-k8s-api opts=%+v err=%v",
+				opts, err)
+		}
+		api, err := k8s.NewFakeAPIFromManifests([]io.Reader{buf})
```
Comment (alpeb) [inline cli/cmd/install_test.go]: No need to account for the CRDs here. Shorter version:
```suggestion
		api, err := k8s.NewFakeAPI()
```

**Review by alpeb — COMMENTED** [review]
Thanks @raykroeker , I think this correctly addresses the issue for the `linkerd install command`, but if I'm not mistaking the problem remains for `linkerd upgrade`, so the function `upgradeControlPlane` needs a similar treatment.

**Comment by alpeb** [comment]
Ok I think the issue might actually be a bit different. Say you install cert-manager+trust-manager configured for linkerd as described [here](https://linkerd.io/2.19/tasks/automatically-rotating-control-plane-tls-credentials/). So you end up with the `linkerd-identity-trust-roots` ConfigMap deployed in the linkerd namespace. Then you install linkerd with
```
linkerd install \
  --set identity.externalCA=true \
  --set identity.issuer.scheme=kubernetes.io/tls
```
That will retrieve the trust-root and put it in linkerd's config:
```
$ k -n linkerd get secret linkerd-config-overrides -oyaml|yq .data.\"linkerd-config-overrides\"|base64 -d
identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    tls:
      crtPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBiTCCAS6gAwIBAgIBATAKBggqhkjOPQQDAjAcMRowGAYDVQQDExFpZGVudGl0
        eS5saW5rZXJkLjAeFw0yNjA0MTcyMzU1MzRaFw0yNzA0MTcyMzU1NTRaMBwxGjAY
        BgNVBAMTEWlkZW50aXR5LmxpbmtlcmQuMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
        QgAEPfckMf1lPoSD8ZtyUpkGAqnojauHrYs4piTMDbC8JMu6nKu0Q5VmKmAbwooW
        ym5zSGNfmpgw3cb4jfl6GK6f+aNhMF8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQW
        MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
        BBT+llc7aLuvZVEWjtddAVCtMPnlOjAKBggqhkjOPQQDAgNJADBGAiEA4Fc86Nf7
        N1IsrOWpK2ca8lRsdUgap5ZgL/ozkiaZLYUCIQCCB9KDxjvbrKEnGMWRTHQvwvz1
        XtngXkk0F9AhlMPsdw==
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        <snip>
        -----END EC PRIVATE KEY-----
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBiTCCAS6gAwIBAgIBATAKBggqhkjOPQQDAjAcMRowGAYDVQQDExFpZGVudGl0
  eS5saW5rZXJkLjAeFw0yNjA0MTcyMzU1MzRaFw0yNzA0MTcyMzU1NTRaMBwxGjAY
  BgNVBAMTEWlkZW50aXR5LmxpbmtlcmQuMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
  QgAEPfckMf1lPoSD8ZtyUpkGAqnojauHrYs4piTMDbC8JMu6nKu0Q5VmKmAbwooW
  ym5zSGNfmpgw3cb4jfl6GK6f+aNhMF8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQW
  MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
  BBT+llc7aLuvZVEWjtddAVCtMPnlOjAKBggqhkjOPQQDAgNJADBGAiEA4Fc86Nf7
  N1IsrOWpK2ca8lRsdUgap5ZgL/ozkiaZLYUCIQCCB9KDxjvbrKEnGMWRTHQvwvz1
  XtngXkk0F9AhlMPsdw==
  -----END CERTIFICATE-----
```
So when running `linkerd upgrade`, this check in `options.go` won't let us through:
```
	if values.Identity.Issuer.Scheme == string(corev1.SecretTypeTLS) {
		if values.Identity.Issuer.TLS.CrtPEM != "" {
			return errors.New("--identity-issuer-certificate-file must not be specified if --identity-external-issuer=true")
		}
```
I think that check needs to be relaxed for the upgrade case.

**Comment by alpeb** [comment]
... and avoiding `linkerd install` to actually pull that cert and put it into the config is what your change actually fixes. Makes sense to me now, sorry for the noise :blush:

**Review by alpeb — APPROVED** [review]

**Review by adleong — APPROVED** [review]
