### PR TITLE
Unregister prom gauges when recycling cluster watcher

### LINKED ISSUE #11839: `duplicate metrics` warnings in service-mirror
### What is the issue?

I'm seeing `failed to register Prometheus gauge ... duplicate metrics collector registration attempted` warnings for `service_cache_size` and `endpoints_cache_size` metrics in the service-mirror log.

### How can it be reproduced?

Follow the Multicluster install instructions: https://linkerd.io/2.14/tasks/multicluster/, then:
```bash
kubectl -n linkerd-multicluster logs -f deploy/linkerd-service-mirror-east -c service-mirror
```

### Logs, error output, etc

```bash
$ kubectl -n linkerd-multicluster logs -f deploy/linkerd-service-mirror-east -c service-mirror
...
time="2023-12-26T22:40:54Z" level=warning msg="failed to register Prometheus gauge Desc{fqName: \"service_cache_size\", help: \"Number of items in the client-go service cache\", constLabels: {cluster=\"remote\"}, variableLabels: []}: duplicate metrics collector registration attempted"
time="2023-12-26T22:40:54Z" level=warning msg="failed to register Prometheus gauge Desc{fqName: \"endpoints_cache_size\", help: \"Number of items in the client-go endpoints cache\", constLabels: {cluster=\"remote\"}, variableLabels: []}: duplicate metrics collector registration attempted"
```

### output of `linkerd check -o short`

```bash
$ linkerd check -o short
linkerd-buoyant
---------------
‼ Linkerd health ok
    Linkerd not connected to Buoyant Cloud
    see https://buoyant.io/linkerd/debugging#linkerd-health for hints
‼ Linkerd vulnerability report ok
    Linkerd not connected to Buoyant Cloud
    see https://buoyant.io/linkerd/debugging#linkerd-vulnerability-report for hints
‼ Linkerd data plane upgrade assistance ok
    Linkerd not connected to Buoyant Cloud
    see https://buoyant.io/linkerd/debugging#linkerd-data-plane-upgrade for hints
‼ Linkerd trust anchor rotation assistance ok
    Linkerd not connected to Buoyant Cloud
    see https://buoyant.io/linkerd/debugging#linkerd-trust-anchor-rotation for hints

Status check results are √
```

### Environment

- Kubernetes Version: `v1.27.3`
- Cluster Environment: kind
- Host OS: `Ubuntu 22.04.3 LTS`
- Linkerd version: `stable-2.14.7`

### Possible solution

Ensure Prometheus metrics are registered only once, preferably at startup, and/or scope each registration with subsystem names.

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #11839

When in `restartClusterWatcher` we fail to connect to the target cluster for whatever reason, the function gets called again 10s later, and tries to register the same prometheus metrics without unregistering them first, which generates warnings.

The problem lies in `NewRemoteClusterServiceWatcher`, which instantiates the remote kube-api client and registers the metrics, returning a nil object if the client can't connect. `cleanupWorkers` at the beginning of `restartClusterWatcher` won't unregister those metrics because of that nil object.

This fix reorders `NewRemoteClusterServiceWatcher` so that an object is returned even when there's an error, so cleanup on that object can be performed.

### CODE REVIEW

**Review by mateiidavid — APPROVED** [review]
Looks good. So, to fix, this basically ensures that any error encountered _after_ building the remote client will still retain a reference to a cluster watcher. e.g. https://github.com/linkerd/linkerd2/blob/999eff3671a3b7444ef2074c57fc16d4ccb35873/multicluster/cmd/service-mirror/main.go#L155-L163 if we reach this point, and we instantiated a client (and as a result registered the metrics) we'll clean-up the reference in the next iteration of the link watch and ensure we don't register the same metrics again.

Good way to fix it imo.

File: multicluster/service-mirror/cluster_watcher.go [hunk 1]
```diff
@@ -207,7 +203,14 @@ func NewRemoteClusterServiceWatcher(
 		headlessServicesEnabled: enableHeadlessSvc,
 		// always instantiate the gatewayAlive=true to prevent unexpected service fail fast
 		gatewayAlive: true,
-	}, nil
+	}
+
+	_, err = remoteAPI.Client.Discovery().ServerVersion()
+	if err != nil {
+		return &rcsw, fmt.Errorf("cannot connect to api for target cluster %s: %w", clusterName, err)
```
Comment (olix0r) [inline multicluster/service-mirror/cluster_watcher.go:210]: It's generally not considered sound to handle a value when err != nil; so we probably ought to omit the value.

```suggestion
		return nil, fmt.Errorf("cannot connect to api for target cluster %s: %w", clusterName, err)
```

However, your description seems to indicate that this is load-bearing:

> This fix reorders NewRemoteClusterServiceWatcher so that an object is returned even when there's an error, so cleanup on that object can be performed.

But the return value is not used at the call-site when an error is returned:

https://github.com/linkerd/linkerd2/blob/cf2999df42dd72802ce4eb60db6abdd9dc6efdca/multicluster/cmd/service-mirror/main.go#L306-L319

So, how does this change fix the problem exactly? How do we avoid introducing another problem like this. Can you add a comment so we don't easily run into this problem again?

Comment (olix0r) [reply multicluster/service-mirror/cluster_watcher.go:210]: OH! this is setting a global value I don't think this is a sound pattern. Instead, the caller should use:

```go
 	 cw, err = servicemirror.NewRemoteClusterServiceWatcher( 
	 	ctx, 
	 	namespace, 
	 	controllerK8sAPI, 
	 	cfg, 
	 	&link, 
	 	requeueLimit, 
	 	repairPeriod, 
	 	ch, 
	 	enableHeadlessSvc, 
	 ) 
	 if err != nil { 
	 	return fmt.Errorf("unable to create cluster watcher: %w", err) 
	 }
     clusterWatcher = cw
```

This removes the need for the change to NewRemoteClusterServiceWatcher.

Comment (alpeb) [reply multicluster/service-mirror/cluster_watcher.go]: If we don't modify NewRemoteClusterServiceWatcher to return `rcsw` on an error, the caller won't be able to perform the gauges cleanup. Actually I've just thought of something else; we should be able to perform the cleanup directly inside NewRemoteClusterServiceWatcher before returning the error. I've just pushed that, LMKWYT.

Comment (olix0r) [reply multicluster/service-mirror/cluster_watcher.go]: I think this makes sense. Let's add a comment above this line explaining that the remoteAPI registers gauges and they must be explicitly unregistered on error. https://github.com/linkerd/linkerd2/pull/11875/files#diff-58391f2b0ac5849326792fbaf12a8e4aa8b06886acbe9fda308357d131ed38dcR172

**Review by olix0r — APPROVED** [review]
