### PR TITLE
Fix resync bug + service selection annotations

### LINKED ISSUE #4451: service-mirror: Incorrect service export with multiple gateways
I've got a _dev_ cluster running, splitting services between two remote clusters, _east_ and _west_ (as configured by https://github.com/olix0r/l2-k3d-multi/tree/f54d406b1061ba6d9455f92100ec9bea8f57151b).

I notice that the _west_ gateway sees requests destined for the _east_ cluster (i.e. with the cluster domain `east.k3d.example.com`).

Inspecting the _dev_ cluster (where the service-mirror is running), I see:
```
:; kubectl --context=k3d-dev -n emojivoto get endpoints emoji-svc-{east,west}
NAME             ENDPOINTS                         AGE
emoji-svc-east   172.24.0.6:4180,172.24.0.6:4180   6h37m
emoji-svc-west   172.24.0.6:4180,172.24.0.6:4180   6h37m
```
So, both service's endpoints are configured with the same gateway IP!

Inspecting the secrets, I see that the secrets have the correct configuration:
```
:; kubectl --context=k3d-dev -n linkerd-multicluster get secrets cluster-credentials-{east,west} -o yaml | sed -ne 's/.*  kubeconfig: //p' | base64 -d
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://172.24.0.4:6443
  name: k3d-east
contexts:
- context:
    cluster: k3d-east
    user: linkerd-service-mirror
  name: k3d-east
current-context: k3d-east
kind: Config
preferences: {}
users:
- name: linkerd-service-mirror
  user:
    token: ...
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://172.24.0.6:6443
  name: k3d-west
contexts:
- context:
    cluster: k3d-west
    user: linkerd-service-mirror
  name: k3d-west
current-context: k3d-west
kind: Config
preferences: {}
users:
- name: linkerd-service-mirror
  user:
    token: ...
```

Furthermore, the _east_ service is configured with the identity of the _west_ gateway:
```
:; kubectl --context=k3d-dev -n emojivoto describe endpoints emoji-svc-east
Name:         emoji-svc-east
Namespace:    emojivoto
Labels:       mirror.linkerd.io/cluster-name=east
              mirror.linkerd.io/mirrored-service=true
              mirror.linkerd.io/remote-gateway-name=linkerd-gateway
              mirror.linkerd.io/remote-gateway-ns=linkerd-multicluster
Annotations:  mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com
              mirror.linkerd.io/remote-svc-fq-name: emoji-svc.emojivoto.svc.east.k3d.example.com
Subsets:
  Addresses:          172.24.0.6
  NotReadyAddresses:  <none>
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    prom  4180  TCP
    grpc  4180  TCP

Events:  <none>
```

### PR DESCRIPTION
**Pull request by zaharidichev**
THis PR addresses two problems: 

- when a resync happens (or the mirror controller is restarted) we incorrectly classify the remote gateway as a mirrored service that is not mirrored anymore and we delete it
- when updating services due to a gateway update, we need to select only the services for the particular cluster

The latter fixes #4451

### CODE REVIEW

**Comment by alpeb** [comment]
I redeployed the service mirror controller (after resetting the resync timeout), and something's going on with the probe:
```
I0521 16:04:05.476468       1 shared_informer.go:227] caches populated                                                                                                                                                                                                            
time="2020-05-21T16:04:05Z" level=info msg="caches synced"                                                                                                                                                                                                                        
time="2020-05-21T16:04:05Z" level=debug msg="Received: OprhanedServicesGcTriggered: {}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                   time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-dst, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=destination,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                                 time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-web, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=web,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                                         time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-grafana, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=grafana,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                                 time="2020-05-21T16:04:05Z" level=debug msg="Probe Manager: received event: MirroredServicePaired: {serviceName: backend-one-svc-macbook, serviceNamespace: multicluster-test, gatewaySpec: GatewaySpec: {gatewayName: linkerd-gateway, gatewayNamespace: linkerd-multicluster, clusterName: macbook, addresses: [[192.168.0.240]], incomingPort: 4180, resourceVersion: 77032, identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local, probeConfig: ProbeConfig: {path: /health, port: 4181, periodInSeconds: 3}}}"          time="2020-05-21T16:04:05Z" level=debug msg="Creating probe worker linkerd-multicluster-linkerd-gateway-macbook"                                                                                                                                                                  time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-identity, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=identity,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                               time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: kube-dns, namespace: kube-system, annotations: [[]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                             time="2020-05-21T16:04:05Z" level=debug msg="Starting probe worker" probe-key=linkerd-multicluster-linkerd-gateway-macbook                                                                                                                                                        time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: backend-two-svc, namespace: multicluster-test, annotations: [[]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-proxy-injector, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=proxy-injector,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                   time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-sp-validator, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=sp-validator,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                       time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: kubernetes, namespace: default, annotations: [[]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                               time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-gateway, namespace: linkerd-multicluster, annotations: [[mirror.linkerd.io/probe-period=3,mirror.linkerd.io/probe-port=4181,linkerd.io/created-by=linkerd/cli git-8b0de4a6,mirror.linkerd.io/gateway-identity=linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local,mirror.linkerd.io/multicluster-gateway=true,mirror.linkerd.io/probe-path=/health]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook       time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-controller-api, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=controller,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook                                                                                                                                                                                                       time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-tap, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=tap,linkerd.io/control-plane-ns=linkerd]]}}
" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: backend-one-svc, namespace: multicluster-test, annotations: [[mirror.linkerd.io/gateway-name=linkerd-gateway,mirror.linkerd.io/gateway-ns=linkerd-multicluster]], labels [[]]}}" apiAddr
ess="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: OnAddCalled: {svc: Service: {name: linkerd-prometheus, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=prometheus,linkerd.io/control-plane-
ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-dst, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=destination,link
erd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-web, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=web,linkerd.io/c
ontrol-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-grafana, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=grafana,link
erd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-identity, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=identity,li
nkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: kube-dns, namespace: kube-system, annotations: [[]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: backend-two-svc, namespace: multicluster-test, annotations: [[]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-proxy-injector, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=proxy
-injector,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-sp-validator, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=sp-vali
dator,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: kubernetes, namespace: default, annotations: [[]], labels [[]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-controller-api, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=contr
oller,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-tap, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=tap,linkerd.io/c
ontrol-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:05Z" level=debug msg="Received: ConsiderGatewayUpdateDispatch: {maybeGateway: Service: {name: linkerd-prometheus, namespace: linkerd, annotations: [[linkerd.io/created-by=linkerd/cli edge-20.5.3]], labels [[linkerd.io/control-plane-component=prometheu
s,linkerd.io/control-plane-ns=linkerd]]}}" apiAddress="https://192.168.0.227:6443" cluster=macbook
time="2020-05-21T16:04:11Z" level=debug msg="Gateway returned unexpected status 503. Marking as unhealthy" probe-key=linkerd-multicluster-linkerd-gateway-macbook
```
Event though I can hit it from a pod without issues:
```
$ curl http://linkerd-gateway-macbook.linkerd-multicluster.svc.cluster.local:4181/health
healthy
```

File: controller/cmd/service-mirror/cluster_watcher.go [hunk 1]
```diff
@@ -834,6 +834,14 @@ func getGatewayMetadata(annotations map[string]string) *gatewayMetadata {
...
 	return nil
 }
+
+func isGateway(annotations map[string]string) bool {
+	if annotations != nil {
+		_, hasAnnotation := annotations[consts.MulticlusterGatewayAnnotation]
+		return hasAnnotation
+	}
+	return false
+}
```
Comment (olix0r) [inline controller/cmd/service-mirror/cluster_watcher.go:844]:
```suggestion
}

```

File: controller/cmd/service-mirror/cluster_watcher.go [hunk 2]
```diff
@@ -888,10 +896,24 @@ func (rcsw *RemoteClusterServiceWatcher) handleConsiderGatewayUpdateDispatch(eve
 func (rcsw *RemoteClusterServiceWatcher) createOrUpdateService(service *corev1.Service) error {
 	localName := rcsw.mirroredResourceName(service.Name)
 	localService, err := rcsw.localAPIClient.Svc().Lister().Services(service.Namespace).Get(localName)
-	gtwData := getGatewayMetadata(service.Annotations)
+	var localNotFound = false
```
Comment (olix0r) [inline controller/cmd/service-mirror/cluster_watcher.go:899]: nit: why `var` declaration here vs `localNotFound := false` (as above)?

Comment (olix0r) [reply controller/cmd/service-mirror/cluster_watcher.go:899]: also, tioli, but this would be maybe clearer as `localMissing := false`...

having to reason through double-negation and what is actually meant is a little tricky... I wouldn't say that `localFound := true` -- which is what is implied by `localNotFound := false`...

**Comment by adleong** [comment]
Also: probably want to update the PR title (at least in the final squashed PR) to say "annotations" not "labels".  This actually sent me barking up the wrong tree because I (mistakenly) thought we were using label selectors in our watch on exposed services in the remote cluster.

**Comment by alpeb** [comment]
To followup on my issue above, the remote cluster was in a bad state. Both the gateway and the identity pods proxies were logging cert errors. So I reinstalled Linkerd (using the same certs) and it's fine now. I'll keep it running and see how it goes, but doesn't seem related to multicluster after all.

**Comment by zaharidichev** [comment]
@adleong certainly agree. Will have to revisit that quite soon. I already have a plan how to simplify all that
