### PR TITLE
Skip NET_RAW & NET_ADMIN while copying pod drop capabilities.

### LINKED ISSUE #6254: LinkerD proxy init fails due to Drop capability NET_RAW
### What is the issue?
Pods are in Init:CrashLoopBackOff due to linkerD startup failure.

### How can it be reproduced?
Creating a deployment with the security context to drop NET_RAW capabilities. Even though this is specified for our container, during the deployment this drop capability automatically picks up in the linkerD init container as well and fails the start up.

### Logs, error output, etc
```
          exitCode: 1
          finishedAt: "2019-06-18T14:07:11Z"
          message: |+
            2019/06/18 14:07:11 Tracing this script execution as [1560866831]
            2019/06/18 14:07:11 State of iptables rules before run:
            2019/06/18 14:07:11 > iptables -t nat -vnL
            2019/06/18 14:07:11 < iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
            Perhaps iptables or your kernel needs to be upgraded.

            2019/06/18 14:07:11 Aborting firewall configuration
            Error: exit status 3
```

#### `linkerd check` output

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      tmp.component: test
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        image: hello-world
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          capabilities:
            drop:
                - NET_RAW
        name: test
        ports:
        - containerPort: 8080
          name: test-port
          protocol: TCP
      restartPolicy: Always
```

### Environment

- Kubernetes Version: 1.19.11
- Cluster Environment: AKS
- Host OS: Ubuntu
- Linkerd version: 2.10.0

### Possible solution
N/A

### PR DESCRIPTION
**Pull request by aryan9600**
While copying the container drop capabilities into the sidecars we should
skip NET_RAW and NET_ADMIN as the init containers require them to setup
iptables.

Fixes #6254 

Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>

### CODE REVIEW

**Review by mateiidavid — APPROVED** [review]
Thanks @aryan9600!

All good from my side :) Tested with a deployment whose only pod was stuck in `Init:CrashLoopBackOff` with a `NET_RAW` capability in the container security ctx. The changes took care of the problem.

File: pkg/inject/inject.go [hunk 1]
```diff
@@ -624,6 +624,9 @@ func (conf *ResourceConfig) injectPodSpec(values *podPatch) {
 				values.Proxy.Capabilities.Add = append(values.Proxy.Capabilities.Add, string(add))
 			}
 			for _, drop := range sc.Capabilities.Drop {
+				if string(drop) == "NET_RAW" || string(drop) == "NET_ADMIN" {
```
Comment (adleong) [inline pkg/inject/inject.go:627]: It looks like we first copy the main container's capabilities into the proxy capabilities (to ensure psp compliance) and then later copy those to the proxy-init container's capabilities (see line 669).  I wonder if it would be more correct to keep the proxy's capabilities as they are but remove the dropping of the NET_RAW and NET_ADMIN capabilities from the proxy-init container.  As far as I know, only the proxy-init container needs these capabilities.

Comment (aryan9600) [reply pkg/inject/inject.go:627]: Tried moving the logic to where we populate the init container capabilities, but that didn't work. Upon looking closer, it looked like the sidecar injection never really happened probably because it was rejected by the `ValidatingAdmissionWebhook`. I might be wrong here but I think the psp `linkerd-linkerd-control-plane` which specifies the need for `NET_RAW` and `NET_ADMIN` capabilities validates both the init and proxy containers which is leading to this. Please let me know if I'm making sense here ✌️

Comment (alpeb) [reply pkg/inject/inject.go:627]: It's true that the PSP policy validates the `securityContext` for all the containers in a pod. But the `linkerd-linkerd-control-plane` PSP only applies to pods in the `linkerd` namespace, and what we're trying to address here are user pods (not linkerd's) that attempt to remove these NET_* capabilities. When testing a deployment, if you look at its ReplicaSet description you might see an error about it not being admitted because of a forbidden PSP. Usually this just means the ServiceAccount associated to that pod hasn't been assigned a PSP. Let me know if you'd like me to provide you with PSP resources and an example to make this work :wink:

Comment (kleimkuhler) [reply pkg/inject/inject.go:627]: Hey @aryan9600 I'm not totally sure what issue you were running in to but I got it working with the following diff:

```
diff --git a/pkg/inject/inject.go b/pkg/inject/inject.go
index f6767cf65..3a7b3c579 100644
--- a/pkg/inject/inject.go
+++ b/pkg/inject/inject.go
@@ -624,9 +624,6 @@ func (conf *ResourceConfig) injectPodSpec(values *podPatch) {
                                values.Proxy.Capabilities.Add = append(values.Proxy.Capabilities.Add, string(add))
                        }
                        for _, drop := range sc.Capabilities.Drop {
-                               if string(drop) == "NET_RAW" || string(drop) == "NET_ADMIN" {
-                                       continue
-                               }
                                values.Proxy.Capabilities.Drop = append(values.Proxy.Capabilities.Drop, string(drop))
                        }
                }
@@ -666,7 +663,19 @@ func (conf *ResourceConfig) injectPodSpec(values *podPatch) {
 func (conf *ResourceConfig) injectProxyInit(values *podPatch) {

        // Fill common fields from Proxy into ProxyInit
-       values.ProxyInit.Capabilities = values.Proxy.Capabilities
+       if values.Proxy.Capabilities != nil {
+               values.ProxyInit.Capabilities = &l5dcharts.Capabilities{}
+               values.ProxyInit.Capabilities.Add = values.Proxy.Capabilities.Add
+               values.ProxyInit.Capabilities.Drop = []string{}
+               // The proxy init container needs NET_RAW and NET_ADMIN, so skip those
+               // if they are dropped by the main container.
+               for _, drop := range values.Proxy.Capabilities.Drop {
+                       if string(drop) == "NET_RAW" || string(drop) == "NET_ADMIN" {
+                               continue
+                       }
+                       values.ProxyInit.Capabilities.Drop = append(values.ProxyInit.Capabilities.Drop, string(drop))
+               }
+       }
        values.ProxyInit.SAMountPath = values.Proxy.SAMountPath

        if v := conf.pod.meta.Annotations[k8s.CloseWaitTimeoutAnnotation]; v != "" {
```

Comment (aryan9600) [reply pkg/inject/inject.go:627]: @alpeb thanks for the explanation, that makes sense :D 
@kleimkuhler sorry, turns out i was just being stupid and making a silly error

**Review by alpeb — APPROVED** [review]
Thanks @aryan9600, this looks and tests fine for me :+1:

File: pkg/inject/inject.go [hunk 2]
```diff
@@ -666,7 +663,19 @@ func (conf *ResourceConfig) injectPodSpec(values *podPatch) {
 func (conf *ResourceConfig) injectProxyInit(values *podPatch) {
 
 	// Fill common fields from Proxy into ProxyInit
-	values.ProxyInit.Capabilities = values.Proxy.Capabilities
+	values.ProxyInit.Capabilities = &l5dcharts.Capabilities{}
+	if values.Proxy.Capabilities != nil {
```
Comment (kleimkuhler) [inline pkg/inject/inject.go:667]: @aryan9600 I'm realizing we only need to initialize `values.ProxyInit.Capabilities` if `values.Proxy.Capabilities != nil`:

```
  if values.Proxy.Capabilities != nil {
      values.ProxyInit.Capabilities = &l5dcharts.Capabilities{}
```

**Review by kleimkuhler — COMMENTED** [review]
Aside from this last comment this looks good!

**Review by kleimkuhler — APPROVED** [review]
Thanks @aryan9600!

**Comment by garimakhulbe02** [comment]
Which release has this? We are having [this issue](https://github.com/linkerd/linkerd2/issues/6254). This merge will fix it. Thanks.
