### PR TITLE
policy: validate that `HTTPRoute` paths are absolute 

### LINKED ISSUE #8948: policy: Validate that paths are absolute
the proxy won't handle httproute paths (in URI rewrites or matches) when paths are relative. The policy admission controller and indexer should catch this case and fail to handle routes that deal in paths that do not start in /.

### PR DESCRIPTION
**Pull request by hawkw**
The proxy won't handle `httproute` paths (in URI rewrites or matches)
when paths are relative. The policy admission controller and indexer
should catch this case and fail to handle routes that deal in paths that
do not start in `/`.

This branch adds validation to the policy controller's validating
admission controller and indexer to ensure that all paths in an
`httproute` rule are absolute.

This was implemented by adding some methods in the `api` crate for
testing whether various types in the `httproute` CRD contain relative
paths. These methods are called by both the admission controller and the
indexer.

Depends on #8959
Closes #8948

### CODE REVIEW

**Comment by hawkw** [comment]
One potential question for reviewers: I put functions for checking for the presence of relative paths in the `api` crate. This crate mostly just contains bindings to kube resource types, and not a lot of other code, so I wasn't sure if this was the right place to put them or not. But, this allows those functions to be accessed by both the validating admission controller and the indexer, so it _seemed_ like the right place...

Also, because those functions are in `api`, which doesn't currently depend on `anyhow`, they just return `bool`s, and the actual errors are generated at the higher levels that call into those functions. This means we don't have as much information in the error messages as we could if we generated the errors closer to the actual checks --- we could say "this specific path was not absolute" and indicate where in the `httproute` spec it was. But, I wasn't sure if we wanted to have an `anyhow` dep in the `api` crate --- what do y'all think?

**Review by adleong — APPROVED** [review]

**Comment by olix0r** [comment]
@hawkw i marked this as a draft because it was based on another in-review PR. now that that PR is merged, it has conflicts. Please mark it as ready when it's a reviewable diff :)

**Comment by hawkw** [comment]
> @hawkw i marked this as a draft because it was based on another in-review PR. now that that PR is merged, it has conflicts. Please mark it as ready when it's a reviewable diff :)

Yup, I'm working on updating it now!

**Comment by hawkw** [comment]
This is ready for review now!

File: policy-controller/k8s/api/src/policy/httproute.rs [hunk 1]
```diff
@@ -161,3 +161,60 @@ pub struct HttpRouteStatus {
...
+        match self {
+            HttpRouteFilter::RequestRedirect {
+                ref request_redirect,
+            } => request_redirect_has_relative_paths(request_redirect),
+            _ => false,
+        }
+    }
+}
+
+pub fn parent_ref_targets_server(p: &ParentReference) -> bool {
```
Comment (olix0r) [inline policy-controller/k8s/api/src/policy/httproute.rs:187]: If we're going to split this into a helper, it could take a generic resource type (as the Target types do).

**Review by olix0r — APPROVED** [review]
It seems a little awkward to have a the validation logic spread across the API and indexer... my preference would be have the converters all in one place, but I see that we're calling it from multiple places.

Probably for a followup, but it seems like we should try to re-use the indexer's validation in the admission controller.

**Comment by hawkw** [comment]
@olix0r I also don't really love this factoring, but I wasn't really sure where to put stuff that was depended on by both the validator and indexer besides the `api` crate... would definitely like to revisit this in a follow-up.

File: policy-controller/k8s/api/src/policy/httproute.rs (hunk 1 above)
Comment (hawkw) [reply policy-controller/k8s/api/src/policy/httproute.rs:187]: oh, you mean like this? https://github.com/linkerd/linkerd2/blob/c3d327f9c7cfe3c7ea85df8aaf89036388b63b07/policy-controller/k8s/api/src/policy/target_ref.rs#L192-L206

yeah, we could do that
