### PR TITLE
Fix Tab start button disabled state #2347

### LINKED ISSUE #2347: Tap start button remains disabled even if new resource is selected
### What is the issue?

If you run a Top query on a resource that does not return data, the buttons will be disabled even if you choose a new resource. An Unexpected close error also occurs in the terminal.

### How can it be reproduced?

From Web UI, click Top. 
Enter a namespace (default) and a resource (statefulsets) that will not load data. Click 'Start'. The buttons will be disabled (expected) but will stay disabled if you choose a new resource (unexpected). You have to reload the page to make a new query.

### Logs, error output, etc

In the terminal:
ERRO[0025] Unexpected close error: websocket: close 1011 (internal server error): no pods found for statefulset/

#### `linkerd check` output

```text
Status check results are √
```

### Environment

- Kubernetes Version: v1.10.11
- Linkerd version: Client version: edge-19.2.4
Server version: edge-19.2.4

### Context

May be related to #1679

### PR DESCRIPTION
**Pull request by liquidslr**
Fixes #2347 

Signed-off-by: Gaurav Kumar <gaurav.kumar9825@gmail.com>

### CODE REVIEW

**Comment by liquidslr** [comment]
@scottcarol  please have a look, Also I added.vscode in gitignore

File: .gitignore [hunk 1]
```diff
@@ -2,6 +2,7 @@
 target
 tmp.discovery
 **/.idea
+**/.vscode
```
Comment (scottcarol) [inline .gitignore]: Hi @liquidslr, We typically try to avoid making changes to files that don't specifically pertain to the PR. In this case I would make a [global .gitignore file ](https://help.github.com/en/articles/ignoring-files) on your machine so that this file is unchanged.

Comment (liquidslr) [reply .gitignore]: Sure @scottcarol I will revert the change

File: web/app/js/components/Top.jsx [hunk 2]
```diff
@@ -133,7 +133,7 @@ class Top extends React.Component {
   handleTapStop = () => {
     this.setState({
       tapRequestInProgress: false,
-      tapIsClosing: true
+      tapIsClosing: false
```
Comment (scottcarol) [inline web/app/js/components/Top.jsx]: Thanks for jumping in to this issue. See @klingerf's [comment in issue #2347](https://github.com/linkerd/linkerd2/issues/2347#issuecomment-469353306) - the issue is not solely a UI issue - it may be related to websockets. 

I would suggest starting by investigating the `Unexpected close error` in the terminal - why we are seeing this error, what is being sent and what is being received, and how it compares to the websockets spec.

Comment (liquidslr) [reply web/app/js/components/Top.jsx]: Yeah I read it a few minutes ago, I would take a look at the issue again

Comment (grampelberg) [reply web/app/js/components/Top.jsx]: From the product perspective, I'd like to have the client do a contextual banner in the top/tap fields that explains why the query a user tried to do didn't work. This would be different than the popup in the lower left hand corner, which feels like it is for unknown errors.

I'm sure this could either be implemented by having structured errors that can be switched between (known vs unknown) or as a new message type. @rmars @scottcarol what do you think is the best approach?

Comment (rmars) [reply web/app/js/components/Top.jsx]: @grampelberg yeah, that would be useful. I think a new state field, like `displayError` or something could be used to track errors we can display in a helpful manner to the user, and leave `this.state.error` for unknown errors (which it currently is).

We could have structured errors too, though I think that error handling is ever so slightly different in each file, so it'd be a bit more annoying (or require more refactoring).

For this particular case, would this be for query errors? (e.g. having a malformed query) or would it be for displaying the websocket errors? I've been wanting to add more form validation for a while, this could also go into that sort of banner.

Comment (grampelberg) [reply web/app/js/components/Top.jsx]: Hmmm, are we getting too complicated? The scope of this issue feels like it should just make sure you can start a tap again if any error occurs. A follow up ticket would be to make the error a little more contextual.

Comment (rmars) [reply web/app/js/components/Top.jsx]: Ah yeah, sure! I don't think that needs to be addressed as part of this issue.
Filed https://github.com/linkerd/linkerd2/issues/2461 to track.

Comment (scottcarol) [reply web/app/js/components/Top.jsx]: Is an empty return to a query always an error? In the situation I described in #2347, I ran a Top query on a resource that didn't return data. Are there cases where the combination of namespace/resources available in the select menus would not produce a result from the API, and is that something we could check before sending the request?

screen shot 2019-03-06 at 2 41 56 pm

Comment (liquidslr) [reply web/app/js/components/Top.jsx]: I checked for several cases and noticed that the query which does not returns data are the one's causing problem and every time no data is returned an error is thrown as i mentioned earlier that it has been implemented in such a way. And about knowing whether namespace/resources available in the select menus would not produce a result without sending a request, i am not sure how to implement that.

File: web/app/js/components/Top.jsx [hunk 3]
```diff
@@ -144,13 +144,15 @@ class Top extends React.Component {
     });
   }
 
-  updateTapClosingState(isTapClosing) {
+  updateTapClosingState(isTapClosing, isTapRequestInProgress) {
     this.setState({
-      tapIsClosing: isTapClosing
+      tapIsClosing: isTapClosing,
+      tapRequestInProgress: isTapRequestInProgress
```
Comment (scottcarol) [inline web/app/js/components/Top.jsx]: This is a minor nit, but for consistency's sake I would switch the order of lines 149 and 150 to match the order of `handleTapStop`, to make it more readable later.

File: web/app/js/components/Top.jsx [hunk 4]
```diff
@@ -144,13 +144,15 @@ class Top extends React.Component {
...
     });
   }
 
   render() {
+
```
Comment (scottcarol) [inline web/app/js/components/Top.jsx]: You added an extra space here, which you don't need if you are returning right below the `render()`. See [React Component docs code example](https://reactjs.org/docs/react-component.html)

File: web/app/js/components/TopModule.jsx [hunk 5]
```diff
@@ -103,7 +103,7 @@ class TopModule extends React.Component {
   }
 
   onWebsocketClose = e => {
-    this.updateTapClosingState(false);
+    this.updateTapClosingState(false,false);
```
Comment (scottcarol) [inline web/app/js/components/TopModule.jsx]: You want to add a space before the second `false` to match our style.

File: web/app/js/components/TopModule.jsx [hunk 6]
```diff
@@ -103,7 +103,7 @@ class TopModule extends React.Component {
   }
 
   onWebsocketClose = e => {
```
Comment (rmars) [inline web/app/js/components/TopModule.jsx]: I think we may want to update this method to be

```
  onWebsocketClose = e => {
    this.updateTapClosingState();
    /* We ignore any abnormal closure since it doesn't matter as long as
    the connection to the websocket is closed. This is also a workaround
    where Chrome browsers incorrectly displays a 1006 close code
    https://github.com/linkerd/linkerd2/issues/1630
    */
    if (e.code !== WS_NORMAL_CLOSURE && e.code !== WS_ABNORMAL_CLOSURE) {
      this.setState({
        error: {
          error: `Websocket close error [${e.code}: ${wsCloseCodes[e.code]}] ${e.reason ? ":" : ""} ${e.reason}`
        }
      });
    }
  }
```
We'll need to add these consts near the top of the file:
```
const WS_NORMAL_CLOSURE = 1000;
const WS_ABNORMAL_CLOSURE = 1006;
```

That will allow us to pass any errors on to the default banner handling, which I think is better than nothing until we implement the contextual banner discussed in #2461

File: web/app/js/components/Top.jsx [hunk 7]
```diff
@@ -144,13 +144,15 @@ class Top extends React.Component {
     });
   }
 
-  updateTapClosingState(isTapClosing) {
+  updateTapClosingState(isTapClosing, isTapRequestInProgress) {
```
Comment (rmars) [inline web/app/js/components/Top.jsx]: We only call this from one place, and it's to set both of these to false. We should consider removing the args in this case and just having
```
  updateTapClosingState() {
    this.setState({
      tapIsClosing: false,
      tapRequestInProgress: false
    });
  }
```

**Comment by liquidslr** [comment]
@rmars @scottcarol  incorporated the suggestions made,  please have a look now :-)

File: web/app/js/components/TopModule.jsx [hunk 8]
```diff
@@ -19,6 +19,8 @@ import _throttle from 'lodash/throttle';
 import _values from 'lodash/values';
 import { withContext } from './util/AppContext.jsx';
 
+const WS_NORMAL_CLOSURE = 1000;
+const WS_ABNORMAL_CLOSURE = 1006;
```
Comment (scottcarol) [inline web/app/js/components/TopModule.jsx]: My only styling nit - I'd add a line underneath line 23, since we typically add a new line under blocks of `const` declarations for readability (see `ErrorModal.jsx` for an example).

Comment (liquidslr) [reply web/app/js/components/TopModule.jsx]: Sure  :+1: done !

**Comment by scottcarol** [comment]
Merged to master, thanks again @liquidslr, great job! 🚂
