### PR TITLE
Remove RPS unit, fix Tap and Top in sidebar

### LINKED ISSUE #1651: Small UI tweaks
From the UI review meeting:
- Sidebar: The > v arrows to the right of Deployments/Pods need padding to the right
- Drop RPS unit from RPS column (it will also fix alignment)

### PR DESCRIPTION
**Pull request by rmars**
- Don't display RPS as a unit in RPS column
- Fix tap and top sidebar items not being minimized correctly

Before:

screen shot 2018-09-17 at 11 02 47 am
screen shot 2018-09-17 at 11 06 06 am

After:
screen shot 2018-09-17 at 11 04 23 am
screen shot 2018-09-17 at 11 02 02 am

Fixes #1651

### CODE REVIEW

File: web/app/js/components/Sidebar.jsx [hunk 1]
```diff
@@ -193,14 +193,14 @@ class Sidebar extends React.Component {
 
             <Menu.Item className="sidebar-menu-item" key="/tap">
               <PrefixedLink to="/tap">
-                <i className="fas fa-microscope" />
+                <Icon><i className="fas fa-microscope" /></Icon>
```
Comment (siggy) [inline web/app/js/components/Sidebar.jsx]: this appears to indent Tap and Top more than the other menu elements?

screen shot 2018-09-17 at 11 26 34 am

File: web/app/js/components/MetricsTable.jsx [hunk 2]
```diff
@@ -19,12 +19,12 @@ import { processedMetricsPropType, successRateWithMiniChart } from './util/Metri
...
 const smMetricColWidth = "70px";
 
-const withTooltip = (d, metricName) => {
+const withTooltip = (d, metricName, hideUnit) => {
   return (
     <Tooltip
       title={metricToFormatter["UNTRUNCATED"](d)}
       overlayStyle={{ fontSize: "12px" }}>
-      <span>{metricToFormatter[metricName](d)}</span>
+      <span>{ !hideUnit ? metricToFormatter[metricName](d) : metricToFormatter["NO_UNIT"](d)}</span>
```
Comment (dadjeibaah) [inline web/app/js/components/MetricsTable.jsx]: I think for better readability, it might be good to invert this statement.

```js
hideUnit ? metricToFormatter["NO_UNIT"](d) : metricToFormatter[metricName](d) 
```

File: web/app/js/components/MetricsTable.jsx [hunk 3]
```diff
@@ -130,7 +130,7 @@ const columnDefinitions = (resource, namespaces, onFilterClick, showNamespaceCol
       className: "numeric",
       width: smMetricColWidth,
       sorter: (a, b) => numericSort(a.requestRate, b.requestRate),
-      render: d => withTooltip(d, "REQUEST_RATE")
+      render: d => withTooltip(d, "REQUEST_RATE", true)
```
Comment (siggy) [inline web/app/js/components/MetricsTable.jsx]: do we need the tooltip here? appears to just show the same number, or, `0` if the underlying value is `---`.
screen shot 2018-09-17 at 11 28 41 am

File: web/app/js/components/Sidebar.jsx (hunk 1 above)
Comment (rmars) [reply web/app/js/components/Sidebar.jsx]: ah! good spot

File: web/app/js/components/MetricsTable.jsx (hunk 3 above)
Comment (rmars) [reply web/app/js/components/MetricsTable.jsx]: the tooltip is intended to show the untruncated value of the number, but it doesn't appear to be super useful seeing as we're also just calculating this from total requests divided by time window, and we don't need this to be super accurate anyways. I can remove the tooltipping

File: web/app/js/components/MetricsTable.jsx (hunk 2 above)
Comment (rmars) [reply web/app/js/components/MetricsTable.jsx]: removed!
