### PR TITLE
check: pull trust anchor certificate from linkerd-identity-trust-roots

### LINKED ISSUE #7449: check: pull trust anchor certificate from `linkerd-identity-trust-roots`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the issue?

We introduced `linkerd-identity-trust-roots` as a configmap to help people have more control when it comes to managing trust anchors for their linkerd installation.

It was pointed out that when installing linkerd with `externalCA` and `externalIssuer` options, the check will fail when matching the trust bundle the proxies have with what's stored in linkerd's config. This is also the case when using extensions that have their own checks, e.g `viz`.

```
Cannot connect to Linkerd Viz: Some pods do not have the current trust bundle and must be restarted:
        * grafana-6fbc6dbf86-mz282
        * metrics-api-545b8d457b-jzdq7
        * prometheus-5d747596d-hfdlb
        * tap-85f7b8b69c-z6jxn
        * tap-injector-6fc7ddd46c-68pc6
        * web-75447677d7-cdl2z
Validate the install with: linkerd viz check
```

I think the problem comes from the fact that during installation, linkerd will store the trust root in both `linkerd-config` and `linkerd-identity-trust-roots`. When doing the check, the healthchecker will use the trust from `linkerd-config`. If linkerd is  installed without manually passing in the certificates, then there will be a mismatch.

### How can it be reproduced?

Install linkerd with a CA managed by cert-manager, or with an existing `linkerd-identity-trust-roots`.

### Logs, error output, etc

× viz extension proxies are healthy
    Some pods do not have the current trust bundle and must be restarted:
        * grafana-6fbc6dbf86-mz282
        * metrics-api-545b8d457b-jzdq7
        * prometheus-5d747596d-hfdlb
        * tap-85f7b8b69c-z6jxn
        * tap-injector-6fc7ddd46c-68pc6
        * web-75447677d7-cdl2z
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints

### output of `linkerd check -o short`

```text
N/A
```

### Environment

N/A

### Possible solution

In the healthchecker, fetch the certificates from the trust-root configmap.

### Additional context

_No response_

### Would you like to work on fixing this bug?

_No response_

### PR DESCRIPTION
**Pull request by wim-de-groot**
Fixes #7449 

This PR updates the health checker to use the trust root from the config map `linkerd-identity-trust-roots`. This will prevent a certificate mismatch, when linkerd is installed without manually passing in the certificates.

Signed-off-by: Wim de Groot <34519486+degrootwim@users.noreply.github.com>

### CODE REVIEW

**Review by mateiidavid — APPROVED** [review]
@wim-de-groot thanks a lot for the work. I think a commit wasn't signed so the DCO check is failing. You could either amend your previous commit (`git commit --amend -s`) or rebase all of your commits and sign the rebased commit instead. Cni test failure should be a flakey test, it'll retrigger when you push again; I'd expect it to pass then. 

I tested this locally by [using an external CA with cert-manager](https://github.com/linkerd/linkerd2/issues/7345#issuecomment-979207861) and by installing linkerd with helm. 

Before the change:
```
:; linkerd check --proxy -n emojivoto -oshort
Linkerd core checks
===================

linkerd-identity-data-plane
---------------------------
‼ data plane proxies certificate match CA
    Some pods do not have the current trust bundle and must be restarted:
        * emoji-696d9d8f95-269qd
        * vote-bot-6d7677bb68-rs49v
        * web-5f86686c4d-m64dn
        * voting-ff4c54b8d-rklbf
    see https://linkerd.io/2/checks/#l5d-identity-data-plane-proxies-certs-match-ca for hints
```

After the change nothing was displayed for `linkerd-identity-data-plane`, so everything should work as expected.

Wdyt about perhaps pulling the ConfigMap logic into its own healthchecker method, e.g `fetchTrustBundle()` or something similar? (e.g similar `fetchWebhookCaBundle` on L#1762). Not sure if we'll need to re-use the logic anywhere but it would perhaps make it easier to understand what we're doing there.

Other than that, this looks good to me 👍🏻

**Comment by wim-de-groot** [comment]
> Wdyt about perhaps pulling the ConfigMap logic into its own healthchecker method, e.g `fetchTrustBundle()` or something similar? (e.g similar `fetchWebhookCaBundle` on L#1762)

Would you like fetchTrustBundle() to be a healthchecker method or a function like `FetchCurrentConfiguration`. If you want fetchTrustBundle() to be a healthchecker method than have to call it from `checkDataPlaneProxiesCertificate`.

**Comment by mateiidavid** [comment]
> > Wdyt about perhaps pulling the ConfigMap logic into its own healthchecker method, e.g `fetchTrustBundle()` or something similar? (e.g similar `fetchWebhookCaBundle` on L#1762)
> 
> @mateiidavid would you like fetchTrustBundle() to be a healthchecker method or a function like `FetchCurrentConfiguration`? If you want fetchTrustBundle() to be a healthchecker method than have to call it from `checkDataPlaneProxiesCertificate`.

Probably just a function. My thought was that it'd make it a bit easier to change this kind of logic in the future 🤔

File: pkg/healthcheck/healthcheck.go [hunk 1]
```diff
@@ -1776,6 +1776,13 @@ func (hc *HealthChecker) fetchWebhookCaBundle(ctx context.Context, webhook strin
 	return caBundle, nil
 }
 
+// FetchTrustBundle retrieves the ca-bundle from the config-map linkerd-identity-trust-roots
+func FetchTrustBundle(ctx context.Context, kubeAPI k8s.KubernetesAPI, controlPlaneNamespace string) (string, error) {
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck.go:1780]: Nice! This is exactly what I had in mind :)

**Review by mateiidavid — COMMENTED** [review]
@wim-de-groot thanks for all of your work on this. The change is exactly what I had in mind; I tested everything and it works well.

A bit nitpicky, but I see we have a few more files added to the PR. I think they might be from a rebase or something similar, would it be possible to remove them from the commit? Otherwise it becomes a bit harder to review the PR.

This might be a bit tricky to do, you should be able to remove all of the additional files using `git reset --soft`.

As far as the change itself goes though, this looks good to me 👍🏻

File: pkg/healthcheck/healthcheck.go (hunk 1 above)
Comment (wim-de-groot) [reply pkg/healthcheck/healthcheck.go:1780]: 🙃

**Comment by wim-de-groot** [comment]
> A bit nitpicky, but I see we have a few more files added to the PR.
I pulled the origin/main branch in this pull request for merging purposes, but I do agree on that it does mess up the actual changed files in the commit. I have removed them from the commit. I will take this as a lesson learned for future PRs.

**Review by mateiidavid — APPROVED** [review]
🚢

**Review by kleimkuhler — APPROVED** [review]
Awesome thanks @wim-de-groot

**Comment by wim-de-groot** [comment]
🚀
