### PR TITLE
Fix edges --all-namespaces flag handling

### LINKED ISSUE #5080: linkerd edges for all-namespaces reports less than for specific namespace
### What is the issue?
we had 
linkerd edges deployment -o wide -n apps-sim --cni-namespace infra-linkerd-cni --linkerd-namespace infra-linkerd report quite a few entries
but
linkerd edges deployment -o wide -A --cni-namespace infra-linkerd-cni --linkerd-namespace infra-linkerd (and --all-namespaces) not report any

### How can it be reproduced?
was with our setup, but should be easy to reproduce. gke cluster with linkerd-cni and linkerd. can provide more info as needed. 

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: v1.16.13-gke.401
- Cluster Environment: (GKE, AKS, kops, ...) GKE
- Host OS: Container OS
- Linkerd version: Stable 2.8.1

### PR DESCRIPTION
**Pull request by kleimkuhler**
## Motivations

Closes #5080

## Solution

When the `--all-namespaces` (`-A`) flag is set for the `linkerd edges` command,
ignore the `namespace` value set by default or `-n`.

This is similar to the behavior for `kubectl`. `kubectl get -A -n linkerd pods`
showing pods in all namespaces.

### Behavior changes

With linkerd and emojivoto installed, this results in:

Before:

```
❯ linkerd edges -A pods
No edges found.
```

After:

```
❯ linkerd edges -A pods
SRC                                   DST                                       SRC_NS      DST_NS      SECURED       
vote-bot-6cb9cb9569-wl6w5             web-5d69bcfdb7-mxf8f                      emojivoto   emojivoto   √  
web-5d69bcfdb7-mxf8f                  emoji-7dc976587b-rb9c5                    emojivoto   emojivoto   √  
web-5d69bcfdb7-mxf8f                  voting-bdf4f778c-pjkjg                    emojivoto   emojivoto   √  
linkerd-prometheus-68d6897d75-ghmgm   emoji-7dc976587b-rb9c5                    linkerd     emojivoto   √  
linkerd-prometheus-68d6897d75-ghmgm   vote-bot-6cb9cb9569-wl6w5                 linkerd     emojivoto   √  
linkerd-prometheus-68d6897d75-ghmgm   voting-bdf4f778c-pjkjg                    linkerd     emojivoto   √  
linkerd-prometheus-68d6897d75-ghmgm   web-5d69bcfdb7-mxf8f                      linkerd     emojivoto   √  
linkerd-controller-7d965cf78d-qw6xj   linkerd-prometheus-68d6897d75-ghmgm       linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-controller-7d965cf78d-qw6xj       linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-destination-74dbb9c46b-nkxgh      linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-grafana-5d9fb67dc6-sn2l8          linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-identity-c875b5d58-b756v          linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-proxy-injector-767b55988d-n9r6f   linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-sp-validator-6c8df84fb9-4w8kc     linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-tap-777fbf7656-p87dm              linkerd     linkerd     √  
linkerd-prometheus-68d6897d75-ghmgm   linkerd-web-546c9444b5-68xpx              linkerd     linkerd     √
```

`linkerd edges -A -n linkerd pods` results in all edges as well (the result
above).

The behavior of `linkerd edges pods` does not change and shows edges in the
`default` namespace.

```
❯ linkerd edges pods
No edges found.
```

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

### CODE REVIEW

**Review by alpeb — APPROVED** [review]
LGTM :+1:

**Review by Pothulapati — APPROVED** [review]
Can verify that this works now!

File: controller/api/util/api_utils.go [hunk 1]
```diff
@@ -256,9 +256,12 @@ func BuildStatSummaryRequest(p StatsSummaryRequestParams) (*pb.StatSummaryReques
 // EdgesRequestParams.
 func BuildEdgesRequest(p EdgesRequestParams) (*pb.EdgesRequest, error) {
 	namespace := p.Namespace
-	if namespace == "" && !p.AllNamespaces {
```
Comment (adleong) [inline controller/api/util/api_utils.go:259]: Don't we want to keep this?  Otherwise if no namespace is specified, we would default to All Namespapces instead of defaulting to the default namespace.

Comment (kleimkuhler) [reply controller/api/util/api_utils.go:259]: This was never the case because the Namespace field defaults to "default" and therefore was never empty.

I originally started to fix this issue by changing the default Namespace value to be empty, but this ended up being a smaller change and requires the same sort of check here.

**Review by adleong — APPROVED** [review]
