### PR TITLE
viz: add viz profile command

### LINKED ISSUE #5613: core: profile command's tap source flag does not work when Viz extension is not installed
## What is the issue?

When the Viz extension is not installed, the `profile --tap` command does not
work.

The `--tap` flag outputs a SP based on tap data for the given target source, but
if tap is not running or has not injected the target source, an unhelpful error
is returned.

## How can it be reproduced?

Install linkerd without the Viz extension and try to tap any target:

```
❯ linkerd profile t1-svc --tap deploy/t1 --tap-duration 25s --tap-route-limit 1
Error: HTTP error, status Code [404] (unexpected API response: 404 page not found
)
```

## Possible solutions

The `--tap` flag could check that the Viz extension is installed through the Viz
API's `CheckClientOrExit`, but this would bring a Viz dependency into the core
install.

Maybe introduce a `viz profile` command that only uses tap? There would not be a
`--open-api` or `--proto` flags for this command since they'd belong to the
`profile` command.

Move the `profile` command to the Viz extension? This feels a little unnecessary
though since it's only the `--tap` flag that is broken.

### PR DESCRIPTION
**Pull request by kleimkuhler**
## What this changes

This adds a `viz profile` command that outputs a service profile based off tap
data. It is identical—but fixes—the current `profile --tap` command.

Additionally, it removes the `--tap` flag from the `profile` command since this
depends on the Viz extension being installed in order to tap a service.

## Why

The `profile --tap` command is currently broken since it depends on the Viz
extension being installed, but the `profile` command is part of the core
install.

Closes #5613

Unblocks #5545

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

### CODE REVIEW

**Review by dadjeibaah — COMMENTED** [review]
One super minor comment but otherwise this looks and works great!

File: cli/cmd/profile.go [hunk 1]
```diff
@@ -112,7 +95,6 @@ func newCmdProfile() *cobra.Command {
 			}
 			// performs an online profile generation and access-check to k8s cluster to extract
 			// clusterDomain from linkerd configuration
-			// profile generation based on tap data requires access to k8s cluster
 			if !options.ignoreCluster {
 				var err error
 				k8sAPI, err = k8s.NewAPI(kubeconfigPath, kubeContext, impersonate, impersonateGroup, 0)
```
Comment (Pothulapati) [inline cli/cmd/profile.go:100]: small nit, TIOLI: `k8sAPI` no longer needed for tap generation. we can make it a local variable right?

File: viz/cmd/profile.go [hunk 2]
```diff
@@ -0,0 +1,213 @@
...
+		Example: `  # Generate a profile by watching live traffic.
+  linkerd profile -n emojivoto web-svc --tap deploy/web --tap-duration 10s --tap-route-limit 5
+`,
+		Args: cobra.ExactArgs(1),
+		RunE: func(cmd *cobra.Command, args []string) error {
+			if options.namespace == "" {
+				options.namespace = pkgcmd.GetDefaultNamespace(kubeconfigPath, kubeContext)
+			}
+			options.name = args[0]
+			clusterDomain := "cluster.local"
```
Comment (Pothulapati) [inline viz/cmd/profile.go:81]: Better to have this is a const in `viz/cmd/root.go` so that this can be re-used? just like the core cmd.

**Review by Pothulapati — APPROVED** [review]
LGTM. Also, would it be useful to mention this command in `linkerd profile` help?

File: cli/cmd/profile.go (hunk 1 above)
Comment (kleimkuhler) [reply cli/cmd/profile.go:100]: Yep I can remove the `var k8sAPI *k8s.KubernetesAPI` above.

File: viz/cmd/profile.go (hunk 2 above)
Comment (kleimkuhler) [reply viz/cmd/profile.go:81]: Yep this is added. Replace a use of it in `metrics-api/cmd` as well.

Comment (kleimkuhler) [reply viz/cmd/profile.go:81]: I backed these commits out. There are docker build errors when trying to pipe this through to metrics-api and then we end up only using it in `profile.go`. Because it's only used there, it doesn't seem worth moving it to `root.go` since it's not duplicated anywhere else.

**Review by dadjeibaah — APPROVED** [review]
Thanks for making that change! LGTM 📦 🚢

**Review by adleong — COMMENTED** [review]
other than the comment above when `linkerd-viz` is not installed, this works great!

File: pkg/profiles/openapi.go [hunk 3]
```diff
@@ -109,7 +106,8 @@ func swaggerToServiceProfile(swagger spec.Swagger, namespace, name, clusterDomai
 	return profile
 }
 
-func mkRouteSpec(path, pathRegex string, method string, operation *spec.Operation) *sp.RouteSpec {
+// MkRouteSpec makes a service profile route from an OpenAPI operation.
+func MkRouteSpec(path, pathRegex string, method string, operation *spec.Operation) *sp.RouteSpec {
```
[the remark this answers is not in the document]
Comment (kleimkuhler) [reply pkg/profiles/openapi.go:110]: I'll probably leave this in here. It's used by `swaggerToServiceProfile` in this file quite a few times, so I think making it public in `pkg` package is okay.

File: viz/cmd/profile.go [hunk 4]
```diff
@@ -0,0 +1,213 @@
...
+
+	cmd := &cobra.Command{
+		Use:   "profile [flags] --tap resource (SERVICE)",
+		Short: "Output service profile config for Kubernetes based off tap data",
+		Long:  "Output service profile config for Kubernetes based off tap data.",
+		Example: `  # Generate a profile by watching live traffic.
+  linkerd viz profile -n emojivoto web-svc --tap deploy/web --tap-duration 10s --tap-route-limit 5
+`,
+		Args: cobra.ExactArgs(1),
+		RunE: func(cmd *cobra.Command, args []string) error {
```
[the remark this answers is not in the document]
Comment (kleimkuhler) [reply viz/cmd/profile.go:76]: Ah good catch!

[the remark this answers is not in the document]
Comment (kleimkuhler) [reply viz/cmd/profile.go:77]: Updated:

```
❯ bin/linkerd viz profile -n linkerd dest --tap deploy/linkerd-destination
Cannot connect to Linkerd Viz: could not find the linkerd-viz extension
Validate the install with: linkerd viz check
```

File: pkg/profiles/openapi.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (adleong) [reply pkg/profiles/openapi.go:110]: ah, my thinking was this isn't JUST used by the openapi code, it makes sense to go in `pkg/profiles/profiles.go`.  It's a bit weird for non-openapi code to depend on a function defined in `openapi.go` (not that REALLY matters since it's in the `pkg/profiles` package, it just feels weird)

**Review by adleong — APPROVED** [review]
