### PR TITLE
Bug -  Stat summary api for to and from policy resource targets

### LINKED ISSUE #9243: StatSummary API should probably indicate that HTTPRoutes and AuthorizationPolicies are not valid `--from` targets
### What is the issue?

The `linkerd viz stat` command supports a number of resource types. Some of these resources are both sources of traffic and destinations for traffic (such as Deployments), but others (such as Services) are only destinations for traffic, and are therefore not supported as `--from` arguments (or as the target when a `--to` argument is present) in `linkerd viz stat`.

We've recently added new authorization resources, HTTPRoute and AuthorizationPolicy, as targets in `linkerd viz stat`. However, these resources do not generate outbound traffic, so they cannot be used as `--from` arguments. However, the StatSummary API doesn't currently validate this, the way it does for other resource types that cannot be `--from` arguments.

### How can it be reproduced?

After installing `linkerd viz`, run
```bash
:; linkerd viz stat deploy --from authorizationpolicy/metrics-api -n linkerd-viz
```
or a similar command. Note that the resulting message is "No traffic found", while another resource that cannot be a `--from` argument, such as `Service`s, returns an error indicating that this cannot be a target for `--from`.

### Logs, error output, etc

```bash
# no traffic found error when using authorizationpolicy
:; bin/linkerd viz stat deploy --from authorizationpolicy/metrics-api -n linkerd-viz
No traffic found.

# for comparison, try a service
:; bin/linkerd viz stat deploy --from svc/metrics-api -n linkerd-viz
StatSummary API response error: service is not supported as a target on 'from' queries, or as a target with 'to' queries%      
```

### output of `linkerd check -o short`

```bash
:; bin/linkerd check -oshort
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    unsupported version channel: git-36a21ab5
    see https://linkerd.io/2/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    unsupported version channel: git-36a21ab5
    see https://linkerd.io/2/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-identity-785d4c65db-58rtl (git-36a21ab5)
	* linkerd-destination-66d8b49cb-4sr5v (git-36a21ab5)
	* linkerd-proxy-injector-594fcd4f84-m65bq (git-36a21ab5)
    see https://linkerd.io/2/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* web-67b5dd8fbf-qdj5k (git-36a21ab5)
	* metrics-api-77b5d859f7-bnjkd (git-36a21ab5)
	* tap-84ccbdf6db-96c9w (git-36a21ab5)
	* tap-injector-f6956b69c-r9z74 (git-36a21ab5)
	* prometheus-5f68c49679-sqkvl (git-36a21ab5)
    see https://linkerd.io/2/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

```bash
:; kubectl version -oyaml
clientVersion:
  buildDate: "1980-01-01T00:00:00Z"
  compiler: gc
  gitCommit: c1de2d70269039fe55efb98e737d9a29f9155246
  gitTreeState: archive
  gitVersion: v1.23.9
  goVersion: go1.18.4
  major: "1"
  minor: "23"
  platform: linux/amd64
serverVersion:
  buildDate: "2022-07-19T01:10:03Z"
  compiler: gc
  gitCommit: 990ba0e88c90f8ed8b50e0ccd375937b841b176e
  gitTreeState: clean
  gitVersion: v1.24.3+k3s1
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64

:; bin/linkerd version
Client version: git-36a21ab5
Server version: git-36a21ab5

:; k3d version
k3d version v5.4.4
k3s version v1.21.7-k3s1 (default)

:; uname -a
Linux noctis 5.18.12 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jul 15 08:12:06 UTC 2022 x86_64 GNU/Linux
```

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by pranoyk**
This PR will fix #9243 

I agree to the DCO for all the commits in this PR
Signed-off-by: Pranoy Kumar Kundu [pranoy1998k@gmail.com](mailto:pranoy1998k@gmail.com)

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
I think we can make this simpler and more comprehensive by updating the check on line 90 to check if EITHER of the  selector resource or fromResource are policy resources.

In fact, I think we should be doing this for toResources as well whenever a toResource is specified (for the same reasons).

**Comment by pranoyk** [comment]
> In fact, I think we should be doing this for toResources as well whenever a toResource is specified (for the same reasons).

Are you suggesting we should add a similar check for these two resources whenever its a toResource ?
@adleong

**Comment by adleong** [comment]
@pranoyk That's right.  Whenever either of `--to` or `--from` is specified, we'll use outbound proxy metrics where policy data is not available.

File: pkg/k8s/k8s.go [hunk 1]
```diff
@@ -133,6 +133,7 @@ var resourceNames = []resourceName{
 	{"srvauthz", "serverauthorization", "serverauthorizations"},
 	{"srv", "server", "servers"},
 	{"ap", "authorizationpolicy", "authorizationpolicies"},
+	{"hp", "httproute", "httproutes"},
```
Comment (adleong) [inline pkg/k8s/k8s.go:136]: We have previously discussed adding a shortname for httproute and decided it was not a good idea.

Full context here: https://github.com/linkerd/linkerd2/pull/10030#discussion_r1054768605

Comment (pranoyk) [reply pkg/k8s/k8s.go]: I have removed httproute from resource name for now, but would eventually have to add it under full name. Do we also plan to keep it in plural names ?

Comment (adleong) [reply pkg/k8s/k8s.go]: I think we can just use "httproute" as both the short name and the full name.

File: viz/metrics-api/stat_summary.go [hunk 2]
```diff
@@ -77,8 +77,15 @@ func (s *grpcServer) StatSummary(ctx context.Context, req *pb.StatSummaryRequest
...
-	if req.GetFromResource() != nil && isPolicyResource(req.GetSelector().GetResource()) {
-		return statSummaryError(req, "'from' queries are not supported with policy resources, as they have inbound metrics only"), nil
+	if req.GetFromResource() != nil {
+		if isPolicyResource(req.GetSelector().GetResource()) ||
+			isPolicyResource(req.GetFromResource()) {
+			return statSummaryError(req, "'from' queries are not supported with policy resources, as they have inbound metrics only"), nil
+		}
+	}
+
+	if req.GetToResource() != nil && isPolicyResource(req.GetToResource()){
```
Comment (adleong) [inline viz/metrics-api/stat_summary.go:87]: I think we're missing the case here there is a toResource and the selector is a policy resource.  That should return an error too.

To put it another way: if either `--to` or `--from` are specified, none of the involved resources can be policy resources.

File: viz/cmd/stat.go [hunk 3]
```diff
@@ -188,7 +188,7 @@ If no resource name is specified, displays stats about all resources of the spec
   linkerd viz stat serverauthorization/web-public
 
   # Get all inbound stats to the web-get and web-delete HTTP route resources
-  linkerd viz stat route/web-get route/web-delete
+  linkerd viz stat httproute/web-get httproute/web-delete
```
Comment (adleong) [inline viz/cmd/stat.go:191]: `route` in this example refers to a ServiceProfile route rather than an `HttpRoute` resource.  This ambiguity between ServiceProfile routes and `HttpRoute` is something we plan to clarify in future releases, but for now this example should be left unchanged.

**Comment by pranoyk** [comment]
Hi @adleong Can you please the review the PR ? I think all the required changes are in place now

**Review by adleong — APPROVED** [review]
Looks great!  Thanks!

Please make sure that you also comply with the [DCO](https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) so that we can accept this fix.

**Comment by pranoyk** [comment]
> Looks great! Thanks!
> 
> Please make sure that you also comply with the [DCO](https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) so that we can accept this fix.

Done!

**Review by alpeb — APPROVED** [review]
