### PR TITLE
Fix panic when routes is called in single-namespace mode

### LINKED ISSUE #2119: edge-19.1.2 --single-namespace still using ServiceProfile
### What is the issue?

19.1.2 with single-namespace seems to still be using ServiceProfile somewhere

linkerd-controller fails to start with error (below)

the rest of the pods do start
linkerd-grafana
linkerd-prometheus
linkerd-web
linkerd-deploy

### How can it be reproduced?

Latest release edge-19.1.2, use single-namespace, not full cluster permissions

### Logs, error output, etc

E0121 12:34:21.464259       1 reflector.go:205] github.com/linkerd/linkerd2/controller/gen/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.ServiceProfile: serviceprofiles.linkerd.io is forbidden: User "system:serviceaccount:NAMESPACE:linkerd-controller" cannot list serviceprofiles.linkerd.io in the namespace "NAMESPACE"

### Environment

- Kubernetes Version: 1.10
- Cluster Environment: EKS
- Host OS:
- Linkerd version: edge-19.1.2 

### Additional context

--single namespace manifest is:
 
```
### Controller RBAC ###
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-NAMESPACE-controller
  namespace: NAMESPACE
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods", "endpoints", "services", "replicationcontrollers"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: ["NAMESPACE"]
  verbs: ["list", "get", "watch"]
```

### PR DESCRIPTION
**Pull request by adleong**
Fixes #2119 

When Linkerd is installed in single-namespace mode, the public-api container panics when it attempts to access watch service profiles.

In single-namespace mode, we no longer watch service profiles and return an informative error when the TopRoutes API is called.

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

File: controller/cmd/public-api/main.go [hunk 1]
```diff
@@ -41,25 +41,40 @@ func main() {
...
+			k8sClient,
+			nil,
+			restrictToNamespace,
+			k8s.Deploy,
+			k8s.Pod,
+			k8s.RC,
+			k8s.RS,
+			k8s.Svc,
+		)
+	} else {
```
Comment (siggy) [inline controller/cmd/public-api/main.go]: i realize this pattern was already in place, and exists in proxy-api, but consider a small DRY up like this:
```go
var spClient *spclient.Clientset
restrictToNamespace := ""
resources := []k8s.APIResource{k8s.Deploy, k8s.Pod, k8s.RC, k8s.RS, k8s.Svc}

if *singleNamespace {
	restrictToNamespace = *controllerNamespace
} else {
	spClient, err = k8s.NewSpClientSet(*kubeConfigPath)
	if err != nil {
		log.Fatal(err.Error())
	}

	resources = append(resources, k8s.SP)
}

k8sAPI := k8s.NewAPI(
	k8sClient,
	spClient,
	restrictToNamespace,
	resources...,
)
```

Comment (klingerf) [reply controller/cmd/public-api/main.go]: If you do go this route, mind updating controller/command/proxy-api/main.go to match?
