### PR TITLE
Fix flakey TestGetProfiles

### LINKED ISSUE #3332: Fix flakey TestGetProfiles
in travis:
https://travis-ci.org/linkerd/linkerd2/jobs/577582791#L749-L753

locally:
```bash
$ while go test -count 1 github.com/linkerd/linkerd2/controller/api/destination; do ls > /dev/null ; done
ok  	github.com/linkerd/linkerd2/controller/api/destination	0.586s
...
ok  	github.com/linkerd/linkerd2/controller/api/destination	0.602s
time="2019-08-27T16:06:13-07:00" level=error msg="A request match must have a field set" test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=error msg="A response match must have a field set" test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=error msg="Range maximum cannot be smaller than minimum" test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="waiting for caches to sync"
time="2019-08-27T16:06:13-07:00" level=info msg="caches synced"
time="2019-08-27T16:06:13-07:00" level=info msg="waiting for caches to sync"
time="2019-08-27T16:06:13-07:00" level=info msg="caches synced"
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on endpoint [ns/name1:8989]" component=endpoints-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=warning msg="failed to retrieve replicaset from k8s ns/rs-1: replicaset.apps \"rs-1\" not found"
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on endpoint [ns/name1:8989]" component=endpoints-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="waiting for caches to sync"
time="2019-08-27T16:06:13-07:00" level=info msg="caches synced"
time="2019-08-27T16:06:13-07:00" level=info msg="waiting for caches to sync"
time="2019-08-27T16:06:13-07:00" level=info msg="caches synced"
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on service ns/name1" component=traffic-split-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on profile other/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on profile other/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on profile ns/name1" component=traffic-split-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="waiting for caches to sync"
time="2019-08-27T16:06:13-07:00" level=info msg="caches synced"
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on service ns/name1" component=traffic-split-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on profile client-ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Establishing watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on profile client-ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1ec8140
time="2019-08-27T16:06:13-07:00" level=info msg="Stopping watch on profile ns/name1" component=traffic-split-watcher test=0x1ec8140
--- FAIL: TestGetProfiles (0.33s)
    --- FAIL: TestGetProfiles/Returns_server_profile (0.11s)
        server_test.go:228: Expected 1 or 2 updates but got 3: [retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > > ]
FAIL
FAIL	github.com/linkerd/linkerd2/controller/api/destination	0.624s
```

## Stack traces

In the failing case, the 3rd update comes from a different code path than the first two:

### First update

```
SEND 1: [retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > > ]
goroutine 28 [running]:
runtime/debug.Stack(0x57, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/linkerd/linkerd2/controller/api/destination.(*bufferingGetProfileStream).Send(0xc0003da2a0, 0x31b2220, 0x102ec61, 0xc0000317f8)
	/Users/sig/code/linkerd2/controller/api/destination/server_test.go:143 +0x132
github.com/linkerd/linkerd2/controller/api/destination.(*profileTranslator).Update(0xc0003e44e0, 0x0)
	/Users/sig/code/linkerd2/controller/api/destination/profile_translator.go:49 +0x14e
github.com/linkerd/linkerd2/controller/api/destination.(*trafficSplitAdaptor).publish(0xc000438ae0)
	/Users/sig/code/linkerd2/controller/api/destination/traffic_split_adaptor.go:70 +0x439
github.com/linkerd/linkerd2/controller/api/destination.(*trafficSplitAdaptor).Update(0xc000438ae0, 0x0)
	/Users/sig/code/linkerd2/controller/api/destination/traffic_split_adaptor.go:39 +0x3f
github.com/linkerd/linkerd2/controller/api/destination.(*primaryProfileListener).Update(0xc00059bc30, 0x0)
	/Users/sig/code/linkerd2/controller/api/destination/fallback_profile_listener.go:72 +0xb2
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*profilePublisher).subscribe(0xc000438cc0, 0x24998e0, 0xc00059bc30)
	/Users/sig/code/linkerd2/controller/api/destination/watcher/profile_watcher.go:175 +0xd0
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*ProfileWatcher).Subscribe(0xc0003e8480, 0x2271211, 0x5, 0xc0003d0160, 0x1c, 0x24998e0, 0xc00059bc30, 0x5, 0xc0003d0160)
	/Users/sig/code/linkerd2/controller/api/destination/watcher/profile_watcher.go:78 +0x141
github.com/linkerd/linkerd2/controller/api/destination.(*server).GetProfile(0xc000438a80, 0xc0001806e0, 0x24ec8a0, 0xc0003da2a0, 0x0, 0x0)
	/Users/sig/code/linkerd2/controller/api/destination/server.go:203 +0xca4
github.com/linkerd/linkerd2/controller/api/destination.TestGetProfiles.func1(0xc000308100)
	/Users/sig/code/linkerd2/controller/api/destination/server_test.go:221 +0x19a
testing.tRunner(0xc000308100, 0x2306b30)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
time="2019-09-03T17:47:45-07:00" level=info msg="Establishing watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1f22d80
```

### Second update

Identical to first update except for `backupProfileListener`:

```
SEND 2: [retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > > ]
goroutine 28 [running]:
runtime/debug.Stack(0x115, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/linkerd/linkerd2/controller/api/destination.(*bufferingGetProfileStream).Send(0xc0003da2a0, 0xc00063e180, 0x1b, 0xc0000317e8)
	/Users/sig/code/linkerd2/controller/api/destination/server_test.go:143 +0x132
github.com/linkerd/linkerd2/controller/api/destination.(*profileTranslator).Update(0xc0003e44e0, 0xc0002ac000)
	/Users/sig/code/linkerd2/controller/api/destination/profile_translator.go:58 +0x122
github.com/linkerd/linkerd2/controller/api/destination.(*trafficSplitAdaptor).publish(0xc000438ae0)
	/Users/sig/code/linkerd2/controller/api/destination/traffic_split_adaptor.go:72 +0x408
github.com/linkerd/linkerd2/controller/api/destination.(*trafficSplitAdaptor).Update(0xc000438ae0, 0xc00029ca00)
	/Users/sig/code/linkerd2/controller/api/destination/traffic_split_adaptor.go:39 +0x3f
github.com/linkerd/linkerd2/controller/api/destination.(*backupProfileListener).Update(0xc00059bc40, 0xc00029ca00)
	/Users/sig/code/linkerd2/controller/api/destination/fallback_profile_listener.go:93 +0xb5
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*profilePublisher).subscribe(0xc0000e7200, 0x24998a0, 0xc00059bc40)
	/Users/sig/code/linkerd2/controller/api/destination/watcher/profile_watcher.go:175 +0xd0
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*ProfileWatcher).Subscribe(0xc0003e8480, 0x228f010, 0x2, 0xc0003d0320, 0x1c, 0x24998a0, 0xc00059bc40, 0x2, 0xc0003d0320)
	/Users/sig/code/linkerd2/controller/api/destination/watcher/profile_watcher.go:78 +0x141
github.com/linkerd/linkerd2/controller/api/destination.(*server).GetProfile(0xc000438a80, 0xc0001806e0, 0x24ec8a0, 0xc0003da2a0, 0x0, 0x0)
	/Users/sig/code/linkerd2/controller/api/destination/server.go:216 +0x106a
github.com/linkerd/linkerd2/controller/api/destination.TestGetProfiles.func1(0xc000308100)
	/Users/sig/code/linkerd2/controller/api/destination/server_test.go:221 +0x19a
testing.tRunner(0xc000308100, 0x2306b30)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
time="2019-09-03T17:47:46-07:00" level=info msg="Stopping watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1f22d80
```

### Third update (causes failure)

Note this originates from `k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)`

```
SEND 3: [retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > > ]
goroutine 126 [running]:
runtime/debug.Stack(0x1d3, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/linkerd/linkerd2/controller/api/destination.(*bufferingGetProfileStream).Send(0xc000410660, 0xc000324ba0, 0x1b, 0xc00061ca28)
	/Users/sig/code/linkerd2/controller/api/destination/server_test.go:143 +0x132
github.com/linkerd/linkerd2/controller/api/destination.(*profileTranslator).Update(0xc000497320, 0xc0004a6a00)
	/Users/sig/code/linkerd2/controller/api/destination/profile_translator.go:58 +0x122
github.com/linkerd/linkerd2/controller/api/destination.(*trafficSplitAdaptor).publish(0xc000324a80)
	/Users/sig/code/linkerd2/controller/api/destination/traffic_split_adaptor.go:72 +0x408
github.com/linkerd/linkerd2/controller/api/destination.(*trafficSplitAdaptor).Update(0xc000324a80, 0xc000196500)
	/Users/sig/code/linkerd2/controller/api/destination/traffic_split_adaptor.go:39 +0x3f
github.com/linkerd/linkerd2/controller/api/destination.(*backupProfileListener).Update(0xc0002e7af0, 0xc000196500)
	/Users/sig/code/linkerd2/controller/api/destination/fallback_profile_listener.go:93 +0xb5
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*profilePublisher).update(0xc00035cd20, 0xc000196500)
	/Users/sig/code/linkerd2/controller/api/destination/watcher/profile_watcher.go:207 +0x125
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*ProfileWatcher).addProfile(0xc00003cc80, 0x2241a40, 0xc000196500)
	/Users/sig/code/linkerd2/controller/api/destination/watcher/profile_watcher.go:103 +0x86
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/Users/sig/code/go/pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/controller.go:195
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
	/Users/sig/code/go/pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/shared_informer.go:554 +0x26d
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc000471e38, 0x102e3bf, 0xc0002d7480)
	/Users/sig/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93/pkg/util/wait/wait.go:203 +0xde
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/Users/sig/code/go/pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/shared_informer.go:548 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000613768)
	/Users/sig/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000471f68, 0xdf8475800, 0x0, 0x1, 0xc0000c6720)
	/Users/sig/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/sig/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00036a880)
	/Users/sig/code/go/pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/shared_informer.go:546 +0x9c
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000166fb0, 0xc0004c0760)
	/Users/sig/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/Users/sig/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93/pkg/util/wait/wait.go:69 +0x62
time="2019-09-03T17:47:53-07:00" level=info msg="Stopping watch on profile ns/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1f22d80
time="2019-09-03T17:47:53-07:00" level=info msg="Stopping watch on profile other/name1.ns.svc.mycluster.local" component=profile-watcher test=0x1f22d80
time="2019-09-03T17:47:53-07:00" level=info msg="Stopping watch on profile ns/name1" component=traffic-split-watcher test=0x1f22d80
--- FAIL: TestGetProfiles (1.12s)
    --- FAIL: TestGetProfiles/Returns_server_profile (1.12s)
        server_test.go:237: Got 3: [retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > > ]
        server_test.go:239: Expected 1 or 2 updates but got 3: [retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c" > > metrics_labels:<key:"route" value:"route1" > timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2 min_retries_per_second:10 ttl:<seconds:10 > > ]
```

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #3332

Fixes the very rare test failure
```
--- FAIL: TestGetProfiles (0.33s)
    --- FAIL: TestGetProfiles/Returns_server_profile (0.11s)
            server_test.go:228: Expected 1 or 2 updates but got 3:
            [retry_budget:<retry_ratio:0.2 min_retries_per_second:10
            ttl:<seconds:10 > >  routes:<condition:<path:<regex:"/a/b/c"
            > > metrics_labels:<key:"route" value:"route1" >
            timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2
            min_retries_per_second:10 ttl:<seconds:10 > >
            routes:<condition:<path:<regex:"/a/b/c" > >
            metrics_labels:<key:"route" value:"route1" >
            timeout:<seconds:10 > > retry_budget:<retry_ratio:0.2
            min_retries_per_second:10 ttl:<seconds:10 > > ]
            FAIL
            FAIL  github.com/linkerd/linkerd2/controller/api/destination
            0.624s
```
that occurs when a third unexpected stream update occurs, when the fake
API takes more time to notify its listeners about the resources created.

For all the nasty details check #3332

### CODE REVIEW

File: controller/api/destination/server_test.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ spec:
 	if err != nil {
 		t.Fatalf("NewFakeAPI returned an error: %s", err)
 	}
-	log := logging.WithField("test", t.Name)
+	log := logging.WithField("test", t.Name())
```
Comment (alpeb) [inline controller/api/destination/server_test.go]: This was causing an error to be added in the log output: `logrus_error="can not add field \"test\"`

Comment (adleong) [reply controller/api/destination/server_test.go]: Looks like we do this a lot:

```
$ ag 'WithField\("test", t.Name\)'
controller/tap/handlers_test.go
57:				log:    logrus.WithField("test", t.Name),

controller/api/destination/profile_translator_test.go
436:			log:    logging.WithField("test", t.Name),
456:			log:    logging.WithField("test", t.Name),
476:			log:    logging.WithField("test", t.Name),
492:			log:    logging.WithField("test", t.Name),
512:			log:    logging.WithField("test", t.Name),
528:			log:    logging.WithField("test", t.Name),
544:			log:    logging.WithField("test", t.Name),
560:			log:    logging.WithField("test", t.Name),
580:			log:    logging.WithField("test", t.Name),

controller/api/destination/watcher/ip_watcher_test.go
430:			endpoints := NewEndpointsWatcher(k8sAPI, logging.WithField("test", t.Name))
431:			watcher := NewIPWatcher(k8sAPI, endpoints, logging.WithField("test", t.Name))

controller/api/destination/watcher/profile_watcher_test.go
75:			watcher := NewProfileWatcher(k8sAPI, logging.WithField("test", t.Name))

controller/api/destination/endpoint_translator_test.go
105:		logging.WithField("test", t.Name),

controller/api/destination/server_test.go
100:	log := logging.WithField("test", t.Name)

controller/api/destination/watcher/endpoints_watcher_test.go
471:			watcher := NewEndpointsWatcher(k8sAPI, logging.WithField("test", t.Name))

controller/api/destination/watcher/traffic_split_watcher_test.go
88:			watcher := NewTrafficSplitWatcher(k8sAPI, logging.WithField("test", t.Name))
```

We should probably fix all of these (in a separate PR)

Comment (alpeb) [reply controller/api/destination/server_test.go]: Good catch, will make a note :+1:
