### PR TITLE
Fix panic in install --ignore-cluster

### LINKED ISSUE #8364: `linkerd install --ignore-cluster` is panicking
### What is the issue?

The `--ignore-cluster` flag is causing a panic

### How can it be reproduced?

```
$ bin/linkerd install --ignore-cluster
```

### Logs, error output, etc

```
$ bin/linkerd install --ignore-cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1981ddd]

goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.install({0x219c3e0, 0xc000056118}, 0x0, {0x2182680, 0xc00000e018}, 0xc0008a7d60?, {0xc0003fc580?, 0xc0000d2900?, 0xc0008a7d38?}, 0x0, ...)
        /home/alpeb/linkerd2/cli/cmd/install.go:160 +0x7d
github.com/linkerd/linkerd2/cli/cmd.newCmdInstall.func1(0xc000379b80?, {0xc00035d600?, 0x1?, 0x1?})
        /home/alpeb/linkerd2/cli/cmd/install.go:131 +0x2e8
github.com/spf13/cobra.(*Command).execute(0xc000379b80, {0xc00035d5d0, 0x1, 0x1})
        /home/alpeb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x312c8c0)
        /home/alpeb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/alpeb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/alpeb/linkerd2/cli/main.go:37 +0x273
```

### output of `linkerd check -o short`

NA

### Environment

Edge-22.4.1

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by adleong**
Fixes #8364 

When `linkerd install` is called with the `--ignore-cluster`, we pass `nil` for the `k8sAPI`.  This causes a panic when using this client for validation.  We add a conditional so that we skip this validation when the `k8sAPI` is `nil`.

### CODE REVIEW

File: cli/cmd/install_test.go [hunk 1]
```diff
@@ -244,6 +244,19 @@ func TestRender(t *testing.T) {
 	}
 }
 
+func TestIgnoreClutster(t *testing.T) {
```
Comment (alpeb) [inline cli/cmd/install_test.go:247]:
```suggestion
func TestIgnoreCluster(t *testing.T) {
```

**Review by alpeb — APPROVED** [review]
LGTM, just one typo :+1:
