### PR TITLE
Fix reporting of injected resources

### LINKED ISSUE #1676: ensure linkerd inject provides stderr feedback for list inputs
`linkerd inject` can take a list of k8s objects, but it appears to only provide stderr feedback to one of the list elements:
```bash
kubectl get -n emojivoto deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -
...
hostNetwork: pods do not use host networking...............................[ok]
sidecar: pods do not have a proxy or initContainer already injected........[ok]
supported: at least one resource injected..................................[ok]
udp: pod specs do not include UDP ports....................................[ok]

Summary: 1 of 1 YAML document(s) injected
  deployment/web
```

### PR DESCRIPTION
**Pull request by alpeb**
When reporting resources provided as a list, it was picking just one
item from the list and ignoring the rest.

Fixes #1676

Signed-off-by: Alejandro Pedraza <alejandro.pedraza@gmail.com>

### CODE REVIEW

**Comment by grampelberg** [comment]
This PR gets me *so* excited. Now my demos will make more sense!

**Comment by alpeb** [comment]
Thanks for the review! :+1: 
@siggy  Indeed, passing that slice by ref felt a little weird. I've incorporated your changes.
@klingerf I have enhanced the test as per your instructions :tada:

File: cli/cmd/inject.go [hunk 1]
```diff
@@ -566,20 +571,20 @@ func injectResource(bytes []byte, options *injectOptions, report *injectReport)
...
 		// in the list (instead of just marshaling the injected pod template).
-
-		// TODO: generate an injectReport per list item
-		return injectList(bytes, options, report)
-
+		return injectList(bytes, options)
 	}
 
+	report := injectReport{}
+	report.name = fmt.Sprintf("%s/%s", strings.ToLower(meta.Kind), om.Name)
```
Comment (klingerf) [inline cli/cmd/inject.go]: TIOLI -- you could set the name field here on initialization, rather than as a separate operation:

```
	report := injectReport{
		name: fmt.Sprintf("%s/%s", strings.ToLower(meta.Kind), om.Name),
	}
```

Comment (alpeb) [reply cli/cmd/inject.go]: Good catch :+1:
