### PR TITLE
cli: skip pods that have `NodeShutdown` status

### LINKED ISSUE #8010: linkerd check uses failed/shutdown/completed pods instead of running pods
### What is the issue?

We're running linkerd on GKE using preemptible VMs, which means every 24 hours we are essentially running fresh hardware. 

This seems to cause an issue for `linkerd check` and possibly some of the internal pieces where it continually references the pods which have been shutdown instead of the new pods started by the service. If I remove the failed/shutdown pods, all checks pass.

The same situation happens with linkerd viz check.

### How can it be reproduced?

1. New 3 node cluster in 3 zones on GKE using preemptive VMs
2. Deploy linkerd in HA mode
3. Deploy linkerd viz

### Logs, error output, etc

Output from `linkerd check`:
```
linkerd check
Linkerd core checks
===================

linkerd-control-plane-proxy
---------------------------
× control plane proxies are healthy
    The "linkerd-destination-786dddb996-gh2lq" pod is not running
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-healthy for hints

Status check results are ×
```

Output from `get pods`: 

```
❯ k get pods -n linkerd
NAME                                     READY   STATUS         RESTARTS   AGE
linkerd-destination-786dddb996-4t6zj     0/4     Completed      0          25h
linkerd-destination-786dddb996-5r5zh     0/4     Completed      0          28h
linkerd-destination-786dddb996-6mlnx     4/4     Running        0          4h47m
linkerd-destination-786dddb996-6zp9f     0/4     Completed      0          4h52m
linkerd-destination-786dddb996-dxg59     4/4     Running        0          41m
linkerd-destination-786dddb996-fvqhg     0/4     Completed      0          61m
linkerd-destination-786dddb996-gh2lq     0/4     NodeShutdown   0          41m
linkerd-destination-786dddb996-pbbn6     0/4     Completed      0          28h
linkerd-destination-786dddb996-tpkdp     0/4     Completed      0          25h
linkerd-destination-786dddb996-tr4qh     4/4     Running        0          68m
linkerd-destination-786dddb996-v8vnd     0/4     NodeShutdown   0          41m
linkerd-identity-558c65db5f-25mck        2/2     Running        0          69m
linkerd-identity-558c65db5f-4g2f5        0/2     Completed      0          25h
linkerd-identity-558c65db5f-5vhkd        0/2     NodeShutdown   0          41m
linkerd-identity-558c65db5f-ctfk2        0/2     Completed      0          28h
linkerd-identity-558c65db5f-djfd2        2/2     Running        0          41m
linkerd-identity-558c65db5f-ffzw4        0/2     Completed      0          25h
linkerd-identity-558c65db5f-mmw7t        0/2     Completed      0          28h
linkerd-identity-558c65db5f-mw6h5        0/2     NodeShutdown   0          41m
linkerd-identity-558c65db5f-nshhz        2/2     Running        0          4h47m
linkerd-identity-558c65db5f-pcqws        0/2     Completed      0          59m
linkerd-identity-558c65db5f-rpb2m        0/2     Completed      0          4h52m
linkerd-identity-558c65db5f-t9fjm        0/2     NodeShutdown   0          62m
linkerd-proxy-injector-87f75ddbd-b5kc2   0/2     Completed      0          25h
linkerd-proxy-injector-87f75ddbd-ddqxv   2/2     Running        0          4h47m
linkerd-proxy-injector-87f75ddbd-fppbq   2/2     Running        0          70m
linkerd-proxy-injector-87f75ddbd-g4blb   0/2     Completed      0          4h52m
linkerd-proxy-injector-87f75ddbd-mzc6b   2/2     Running        0          41m
linkerd-proxy-injector-87f75ddbd-pjd4g   0/2     Completed      0          61m
linkerd-proxy-injector-87f75ddbd-q6hjl   0/2     Completed      0          25h
linkerd-proxy-injector-87f75ddbd-rpmvf   0/2     NodeShutdown   0          41m
linkerd-proxy-injector-87f75ddbd-vb69x   0/2     Completed      0          28h
linkerd-proxy-injector-87f75ddbd-wv4nx   0/2     Completed      0          28h
linkerd-proxy-injector-87f75ddbd-zmdbm   0/2     NodeShutdown   0          41m
```

I would expect it to check the status of `linkerd-destination-786dddb996-6mlnx`?

### output of `linkerd check -o short`

See above

### Environment

- Kubernetes 1.22
- Env: GKE
- Linkerd 2.11

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

_No response_

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #8010.

Pods that have `NodeShutdown` status should be skipped during validation as they will not have a running proxy container.

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

File: pkg/healthcheck/healthcheck.go [hunk 1]
```diff
@@ -2829,3 +2826,15 @@ func containsProxy(pod corev1.Pod) bool {
 	}
 	return false
 }
+
+// shouldSkip returns true if a Pod should be skipped when validating status
+// as it would not have a proxy container running.
+func shouldSkip(status string) bool {
```
Comment (kleimkuhler) [inline pkg/healthcheck/healthcheck.go:2832]: It seemed better to keep a list of statuses we want to skip rather than growing the conditional.

To deal with a list of statuses—and not introduce a loop label—I moved things it into a separate function.

File: pkg/healthcheck/healthcheck.go [hunk 2]
```diff
@@ -2795,10 +2795,7 @@ func CheckPodsRunning(pods []corev1.Pod, namespace string) error {
 	}
 	for _, pod := range pods {
 		status := k8s.GetPodStatus(pod)
-
-		// Skip validating meshed pods that are in the `Completed` or
-		// `Shutdown` state as they do not have a running proxy
-		if status == "Completed" || status == "Shutdown" {
+		if shouldSkip(status) {
```
Comment (adleong) [inline pkg/healthcheck/healthcheck.go:2798]: TIOLI: consider

```
switch status {
case "Completed", "Shutdown", "NodeShutdown":
    continue
}
```

**Review by adleong — APPROVED** [review]

File: pkg/healthcheck/healthcheck.go (hunk 2 above)
Comment (kleimkuhler) [reply pkg/healthcheck/healthcheck.go:2798]: I like that 👍

**Review by mateiidavid — APPROVED** [review]
