### PR TITLE
viz: only tap pods that have tap explicitly enabled

### LINKED ISSUE #5544: Tap controller should exclude pods with tap disabled
If you run `linkerd viz tap` targeting a workload which has tap disabled or has not been injected by the tap-injector, the tap command simply waits and produces no output.

In some sense, this behavior is correct.  However, it can be unexpected, and users will encounter this situation more frequently now that the tap-injector is no longer part of the default proxy-injector.  

To remedy this, the tap controller can attempt to determine if a target pod is tapable by examining the environment variables of its proxy sidecar.  If a target pod is not tapable, it should be excluded from the list of tap targets.  If the list of tap targets is empty, the tap controller should return a helpful error message to the user informing them that there are no tapable pods in the target workload and to ensure that the pods exist and have been injected by the tap-injector.

Note that with https://github.com/linkerd/linkerd2/issues/5325#issuecomment-760575199 implemented, the `linkerd viz check --proxy` command can be used to diagnose this.

### PR DESCRIPTION
**Pull request by kleimkuhler**
## What this changes

This allows the tap controller to inform `tap` users when pods either have tap
disabled or tap is not enabled yet.

## Why

When a user taps a resource that has not been admitted by the Viz extension's
`tap-injector`, tap is not explicitly disabled but it is also not enabled.
Therefore, the `tap` command hangs and provides no feedback to the user.

Closes #5544

## How

A new `viz.linkerd.io/tap-enabled` annotation is introduced which is
automatically added by the Viz extension's `tap-injector`. This annotation is
added to a pod when it is able to be tapped; this means that the pod and the
pod's namespace do not have the `config.linkerd.io/disable-tap` annotation
added.

When a user attempts to tap a resource, the tap controller now looks for this
new annotation; if the annotation is present on the pod then that pod is
tappable.

If the annotation is not present or tap is explicitly disabled, an error is
returned.

## UI changes

Multiple errors can now occur when trying to tap a resource:

1. There are no pods for the resource.
2. There are pods for the resource, but tap is disabled via pod or namespace
   annotation.
3. There are pods for the resource, but tap is not yet enabled because the
   `tap-injector` did not admit the resource.

Errors are now handled as shown below:

Tap is disabled:

```
❯ bin/linkerd viz tap deploy/test
Error: no pods to tap for deployment/test
pods found with tap disabled via the config.linkerd.io/disable-tap annotation
```

Tap is not enabled:

```
❯ bin/linkerd viz tap deploy/test
Error: no pods to tap for deployment/test
pods found with tap not enabled; try restarting resource so that it can be injected
```

There are a mix of pods with tap disabled or tap not enabled:

```
❯ bin/linkerd viz tap deploy/test
Error: no pods to tap for deployment/test
pods found with tap disabled via the config.linkerd.io/disable-tap annotation
pods found with tap not enabled; try restarting resource so that it can be injected
```

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

### CODE REVIEW

File: controller/tap/server.go [hunk 1]
```diff
@@ -94,13 +99,18 @@ func (s *GRPCTapServer) TapByResource(req *pb.TapByResourceRequest, stream pb.Ta
...
+		errStrings := []string{}
+		errStr := fmt.Errorf("no pods to tap for %s/%s", res.GetType(), res.GetName())
+		errStrings = append(errStrings, errStr.Error())
+		if tapDisabled {
+			errStr = fmt.Errorf("pods found with tap disabled via the %s annotation", pkgK8s.ProxyDisableTapAnnotation)
+			errStrings = append(errStrings, errStr.Error())
 		}
-		return status.Errorf(codes.NotFound, "no pods found for %s/%s", resType, resName)
+		if tapNotEnabled {
+			errStr = fmt.Errorf("pods found with tap not enabled; try restarting resource so that it can be injected")
```
Comment (Pothulapati) [inline controller/tap/server.go:110]: Once this is updated, I can update the error message to instead ask for `viz check` where the restart injector message can be displayed full list of failed injected pods.

**Review by Pothulapati — APPROVED** [review]
LGTM.

**Review by dadjeibaah — APPROVED** [review]
LGTM! 📦 🚢
