### PR TITLE
Fix the debug message in endpoints watcher

### LINKED ISSUE #1606: Destination service debug logs have memory addresses instead of useful info
I turned on debug logging in the destination service, but it doesn't really help with debugging because it looks like this:

```
time="2018-09-06T21:54:16Z" level=debug msg="Updating world1.default:7778 to [0xc4204e86c0 0xc4204e8720 0xc4204e8790 0xc4204e87f0]"
time="2018-09-06T21:54:16Z" level=debug msg="Updating world1.default:7778 to [0xc42001cd30 0xc42001cd90 0xc42001ce10]"
time="2018-09-06T21:54:27Z" level=debug msg="Updating world1.default:7778 to [0xc42071e0f0 0xc42071e150 0xc42071e1c0]"
time="2018-09-06T21:54:37Z" level=debug msg="Updating world1.default:7778 to [0xc42071e6b0 0xc42071e710 0xc42071e780]"
time="2018-09-06T21:54:41Z" level=debug msg="Updating world1.default:7778 to [0xc42071f350 0xc42071f3b0 0xc42071f420 0xc42071f480]"
time="2018-09-06T21:54:41Z" level=debug msg="Updating world1.default:7778 to [0xc42071fc80 0xc42071fce0 0xc42071fd50]"
time="2018-09-06T21:54:43Z" level=debug msg="Updating world1.default:7778 to [0xc42062edb0 0xc42062ee10 0xc42062ee80]"
time="2018-09-06T21:54:55Z" level=debug msg="Updating world1.default:7778 to [0xc4206b4850 0xc4206b4ab0 0xc4206b4b20 0xc4206b4b90]"
```

We should be able to clean those up pretty easily.

### PR DESCRIPTION
**Pull request by alenkacz**
This is how the log line looks like after this change `Updating name1.ns:8989 to [{address:ip:<ipv4:183059183 > port:8989 , pod:ns.name1-f748fb6b4-hpwpw}, {address:ip:<ipv4:183064820 > port:8989 , pod:ns.name1-f748fb6b4-6vcmw}]`

Closes #1606

Signed-off-by: Alena Varkockova <varkockova.a@gmail.com>

### CODE REVIEW

File: controller/destination/listener.go [hunk 1]
```diff
@@ -26,6 +28,10 @@ type updateAddress struct {
 	pod     *coreV1.Pod
 }
 
+func (ua updateAddress) String() string {
+	return fmt.Sprintf("{address:%v, pod:%s.%s}", ua.address, ua.pod.Namespace, ua.pod.Name)
```
Comment (dadjeibaah) [inline controller/destination/listener.go]: Since `ua.address` is the integer representation of an IP address, we probably could convert it to a more readable version using `addr.ProxyAddressToString(...)` The "toString" function would look like this:

```go
func (ua updateAddress) String() string {
	return fmt.Sprintf("{address:%v, pod:%s.%s}", addr.ProxyAddressToString(ua.address), ua.pod.Namespace, ua.pod.Name)
}
```

With this version, the log lines will end up looking like this:

```bash
Updating emoji-svc.emojivoto:8080 to [{address:10.1.0.178:8080, pod:emojivoto.emoji-6b9cfb4f46-pnl92}]
```

**Comment by alenkacz** [comment]
@dadjeibaah great suggestion, thanks. I've fixed that :)
