### PR TITLE
Split linkerd viz authz out of StatSummary

### LINKED ISSUE #9144: `linkerd viz auth` sometimes incorrectly displays the default route
### What is the issue?

On `edge-22.8.2`, running the `linkerd viz authz` command for a deployment appears to occasionally show an incorrect route. When all traffic is directed to a particular HTTP  route, that route will typically show up in the route list, but sometimes, the output will instead show the default route, even when no traffic is actually hitting the default route.

### How can it be reproduced?

1. Check out https://github.com/hawkw/routekicking at hawkw/routekicking@640665b5db4a1d7acd15732b0185ff84f1ac81e7
2. Set up the cluster (assuming `k3d`):
   ```shell
   :; just setup
   ```
3. Create `hokay` deployment, `curl` pod, and policies:
    ```shell
    :; just apply manifests/hokay.yml &&
       just apply manifests/curl-authz.yml &&
       just apply manifests/policy.yml &&
       just apply manifests/hello-rt.yml
    ```
4. Generate some load:
    ```shell
    :; while true; do just curl authz /hello; sleep 0.5; done
    ```
5. In another terminal, run
    ```shell
    :; just watch-authz deploy/hokay
    ```
   it may be necessary to wait a few seconds to see the weird behavior

### Logs, error output, etc

[asciicast](https://asciinema.org/a/TJH6Dw347oM8OwOalqcYUXP4R?t=8)

### output of `linkerd check -o short`

```shell
:; just linkerd check -o short
/home/eliza/Code/routekicking/.linkerd2/bin/linkerd --context k3d-routekicking check -o short
Status check results are √
```

### Environment

Kubernetes version:
```shell
:; kubectl version -oyaml
clientVersion:
  buildDate: "1980-01-01T00:00:00Z"
  compiler: gc
  gitCommit: c1de2d70269039fe55efb98e737d9a29f9155246
  gitTreeState: archive
  gitVersion: v1.23.9
  goVersion: go1.18.4
  major: "1"
  minor: "23"
  platform: linux/amd64
serverVersion:
  buildDate: "2021-11-29T16:40:13Z"
  compiler: gc
  gitCommit: ac70570999c566ac3507d2cc17369bb0629c1cc0
  gitTreeState: clean
  gitVersion: v1.21.7+k3s1
  goVersion: go1.16.10
  major: "1"
  minor: "21"
  platform: linux/amd64

WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
Linkerd version:
```shell
:; just linkerd version
/home/eliza/Code/routekicking/.linkerd2/bin/linkerd --context k3d-routekicking version
Client version: edge-22.8.2
Server version: edge-22.8.2
```
`k3d` version:
```shell
:; k3d version
k3d version v5.4.4
k3s version v1.21.7-k3s1 (default)
```

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

_No response_

### LINKED ISSUE #9149: Show default servers in linkerd viz authz output
### What problem are you trying to solve?

The `linkerd viz authz` command lists metrics for all Servers of the given resource.  However, the default Server (which is used when no Server resource has been created) is not shown.  This leaves us with a blind spot when trying to reason about traffic for which there is no explicit server and can hide denials caused by the default policy.

### How should the problem be solved?

The `linkerd viz authz` command should list the default Server for each resource in addition to the Server resources.

### Any alternatives you've considered?

N/A

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

_No response_

### PR DESCRIPTION
**Pull request by adleong**
Fixes #9149
Fixes #9144 

The `linkerd viz authz` command uses the metrics-api StatSummary gRPC method, the same gRPC method used by `linkerd viz stat`.  This method is very complex and because it was designed for the use case of `linkerd viz stat`, it has certain limitations when it is used for `linkerd viz authz` such as #9149 and #9144.  These stem from the fact that the metrics processing which happens in StatSummary is keyed off of the resource and when there are multiple metrics samples per resource (such as when there are multiple httproutes for a server, for example) this leads to key conflicts and data in maps being overwritten.

Rather than trying to bend StatSummary into a use-case it was never intended for, we instead create a new gRPC endpoint called Authz specifically for the `linkerd viz authz` use-case.  This method returns authz related stats for the given workload resource, with separate rows for all combinations of server/route/authz which have metrics.  The updated output of `linkerd viz authz` looks like this:

```console
# with default-deny, before creating policy resources
> linkerd viz authz -n emojivoto po
ROUTE          SERVER        AUTHORIZATION                          UNAUTHORIZED  SUCCESS     RPS  LATENCY_P50  LATENCY_P95  LATENCY_P99  
default        default:deny                                               1.0rps    0.00%  0.0rps          0ms          0ms          0ms  
proxy-metrics  proxy-admin   authorizationpolicy/prometheus-scrape        0.0rps  100.00%  0.4rps          1ms          1ms          1ms  
proxy-probes   proxy-admin   authorizationpolicy/proxy-probes             0.0rps  100.00%  0.8rps          1ms          1ms          1ms  

# then, after creating policy resources
> linkerd viz authz -n emojivoto po
ROUTE          SERVER       AUTHORIZATION                          UNAUTHORIZED  SUCCESS     RPS  LATENCY_P50  LATENCY_P95  LATENCY_P99  
default        emoji-grpc   authorizationpolicy/emoji-grpc               0.0rps  100.00%  2.0rps          1ms          1ms          1ms  
proxy-metrics  proxy-admin  authorizationpolicy/prometheus-scrape        0.0rps  100.00%  0.4rps          1ms          1ms          1ms  
proxy-probes   proxy-admin  authorizationpolicy/proxy-probes             0.0rps  100.00%  0.8rps          1ms          1ms          1ms  
default        voting-grpc  authorizationpolicy/voting-grpc              0.0rps   80.00%  1.0rps          1ms          1ms          1ms  
default        web-http     authorizationpolicy/web-public               0.0rps   90.83%  2.0rps          2ms          2ms          3ms
```

Since StatSummary is no longer attempting to handle this use-case, we also simplify some of the groupBy queries that it used.

### CODE REVIEW

File: viz/cmd/authz.go [hunk 1]
```diff
@@ -87,104 +85,82 @@ func NewCmdAuthz() *cobra.Command {
...
-							server,
-							unauthorized,
-							unauthorized,
-							"-",
-							fmt.Sprintf("%.1frps", getRequestRate(row.SrvStats.DeniedCount, 0, row.TimeWindow)),
-							"-",
-							"-",
-							"-",
-						})
+				if row.GetStats().GetSuccessCount()+row.GetStats().GetSuccessCount()+row.GetSrvStats().GetDeniedCount() > 0 {
```
Comment (mateiidavid) [inline viz/cmd/authz.go:131]: tinyy bit confused why we're adding the success count twice here.

**Review by mateiidavid — APPROVED** [review]
Looks good! Although I didn't manage to reproduce the behaviour seen in 9144, code looks good and output looks good too (super handy to see stats for the default server).

Before

```
:; linkerd viz authz deploy/hokay
ROUTE  SERVER        AUTHORIZATION_POLICY  SERVER_AUTHORIZATION  SUCCESS     RPS  LATENCY_P50  LATENCY_P95  LATENCY_P99
hello  hokay-server  hello-policy                                100.00%  1.6rps          1ms          1ms          1ms
```

And after

```
:; bin/linkerd viz authz deploy/hokay
ROUTE    SERVER                       AUTHORIZATION                     UNAUTHORIZED  SUCCESS     RPS  LATENCY_P50  LATENCY_P95  LATENCY_P99
default  default:all-unauthenticated  default/all-unauthenticated             0.0rps  100.00%  0.1rps          1ms          1ms          1ms
probe    default:all-unauthenticated  default/probe                           0.0rps  100.00%  0.2rps          1ms          1ms          1ms
hello    hokay-server                 authorizationpolicy/hello-policy        0.0rps  100.00%  0.8rps          1ms          1ms          1ms

```

File: viz/cmd/authz.go (hunk 1 above)
Comment (adleong) [reply viz/cmd/authz.go:131]: great question!  the answer is because this is a mistake 😂 it's supposed to be adding the successes, failures, and denials to determine if there are any metrics to display.

**Review by kleimkuhler — APPROVED** [review]
Overall this looks good to me! One small question about simplifying getting a field value, but otherwise 👍
