### PR TITLE
Fix injector not emitting skip events properly

### LINKED ISSUE #8634: Injector does not emit skip events when a workload is patched with annotations only
### What is the issue?

When a workload cannot be injected (for whatever reason), the `proxy-injector` emits an event with the reason for skipping injection.

https://github.com/linkerd/linkerd2/blob/8d382779a5499c0bfcbb03ce2dcabac8bd356423/controller/proxy-injector/webhook.go#L158-L181

This is really useful for debugging and figuring out what's wrong. Workloads may receive an annotation patch (typically for opaque ports) even if they are not injected. When an annotation patch is generated, we also admit the workload:

https://github.com/linkerd/linkerd2/blob/8d382779a5499c0bfcbb03ce2dcabac8bd356423/controller/proxy-injector/webhook.go#L143-L155

Since annotation patches return early, we never emit skipped events. Without the skip reason, investigations get a bit harder since people have to look at the spec and figure out on their own where things went wrong.

### How can it be reproduced?

An easy repro would be to deploy a workload that has `automountServiceAccount=false` and has a target port included in the default list of opaque ports; in those cases, annotation patches will be generated but injection will be skipped.

For example, the [`mariadb`](https://artifacthub.io/packages/helm/bitnami/mariadb) bitnami chart seems to not be injected by default since its serviceAccountToken is not automatically mounted.

An easy repro:

```sh
linkerd install | kubectl apply -f -
kubectl annotate ns default linkerd.io/inject=enabled
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/mariadb
```

However, this should also work with nginx as long as the namespace is annoated with `config.linkerd.io/opaque-ports` and it contains in the spec something that would trigger injection to be skipped (e.g `hostNetwork=true` or `automountServiceAccountToken=false`).

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by mateiidavid**
A resource that cannot be injected -- for a variety of reasons, such as
using the host network, or not mounting a SA token when token projection
is disabled -- may still have an annotation patch if the resource's
endpoints have ports marked as opaque.

When an annotation patch is generated but an injection patch is not, the
injector will not emit an event and consider the resource as "injected",
when in fact it does not have the sidecar. This can make it hard to
investigate issues where resources that are supposed to be injected are
not because the failure is not obvious.

This change refactors and simplifies the logic by emitting an event
whenever a resource is not injected, regardless of whether an annotation
patch is generated for it. This should provide better visibility in case
of failures. Furthermore, the change refactors the code to avoid too
many early returns and make it easier to trace the codepath through the
function. The initial assumption that an annotation patch should not
increment injection skipped admission response has been left intact; in
other words, an annotation patch will not count in the metrics as a
skip, but an event with the skip reason is still emitted.

Fixes #8634

Signed-off-by: Matei David <matei@buoyant.io>

### Validation
---

To validate, I used the same steps I had for the repro in #8634. I deployed `bitnami/mariadb` in the cluster; I installed in a test cluster using `stable-2.11.1` that _does not include projected tokens_. Since `mariadb`'s SA does not automount, the pod is never injected. We receive an annotation patch for its opaque ports but not further information why injection failed:

```yaml
# Autoomount is false hence why injection is skipped
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-06-09T12:08:14Z"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.0.12
  name: my-release-mariadb
  namespace: default
  resourceVersion: "1237318"
  uid: 92269811-7170-4dab-a792-4f8cce55675c
secrets:
- name: my-release-mariadb-token-q4pb7
```

```
# injector logs
time="2022-06-09T12:08:15Z" level=info msg="received pod/my-release-mariadb-0"
time="2022-06-09T12:08:15Z" level=info msg="annotation patch generated for: pod/my-release-mariadb-0"

# pod state, not injected
my-release-mariadb-0               1/1     Running                 0          48m   10.42.0.65   k3d-demo-server-0   <none>           <none>

# No events
48m         Normal    Created                 pod/my-release-mariadb-0                          Created container mariadb
48m         Normal    Started                 pod/my-release-mariadb-0                          Started container mariadb
```

After fix, I had to change the spec for the deployment to use `hostNetwork=true` to have injection be skipped. In current edge versions we use projected tokens so `automountServiceAccountToken` does not have to explicitly set to true.

```
# injector logs are same as before, we generate the patch and skip injection
time="2022-06-09T12:50:53Z" level=info msg="received pod/my-release-mariadb-0"
time="2022-06-09T12:50:53Z" level=info msg="annotation patch generated for: pod/my-release-mariadb-0"

# pod is not injected
my-release-mariadb-0   1/1     Running   0          8m9s

# we now get an event though
8m26s       Normal    InjectionSkipped          statefulset/my-release-mariadb                    Linkerd sidecar proxy injection skipped: , hostNetwork is enabled
8m26s       Normal    SuccessfulCreate          statefulset/my-release-mariadb                    create Pod my-release-mariadb-0 in StatefulSet my-release-mar
```

Quick note, output in the event is messed because I tried to change how we process the string to use `strings.TrimPrefix` instead of returning a slice when creating readable messages. I reverted the change back to how it was since it didn't seem to do what I expected it to do.

### CODE REVIEW

File: controller/proxy-injector/webhook.go [hunk 1]
```diff
@@ -131,52 +131,51 @@ func Inject(linkerdNamespace string) webhook.Handler {
 			}, nil
 		}
 
+		// Resource could not be injected with the sidecar, format the reason
+		// for injection being skipped to emit an event
+		var readableReasons string
+		for _, reason := range reasons {
+			readableReasons = readableReasons + ", " + inject.Reasons[reason]
```
Comment (adleong) [inline controller/proxy-injector/webhook.go:138]: I know this is just moved from below, but this might be a good opportunity to clean this up by using strings.Join

File: controller/proxy-injector/webhook.go [hunk 2]
```diff
@@ -131,52 +131,51 @@ func Inject(linkerdNamespace string) webhook.Handler {
...
+		}
 		if len(patchJSON) != 0 {
+			// If resource needs to be patched with annotations (e.g opaque
+			// ports), then admit the request with the relevant patch
 			log.Infof("annotation patch generated for: %s", report.ResName())
 			log.Debugf("annotation patch: %s", patchJSON)
 			proxyInjectionAdmissionResponses.With(admissionResponseLabels(ownerKind, request.Namespace, "false", "", report.InjectAnnotationAt, configLabels)).Inc()
 			patchType := admissionv1beta1.PatchTypeJSONPatch
-			return &admissionv1beta1.AdmissionResponse{
+			admissionResp = &admissionv1beta1.AdmissionResponse{
```
Comment (adleong) [inline controller/proxy-injector/webhook.go:164]: I think using early returns instead of an `else if` block actually makes the flow clearer and is more idiomatic.

Comment (mateiidavid) [reply controller/proxy-injector/webhook.go]: Yeah, I agree. It just seemed a bit redundant to me to return the same thing twice at the end. I've reverted back to how things were 👍🏻

**Review by adleong — APPROVED** [review]

**Review by alpeb — APPROVED** [review]
LGTM :+1:
