### PR TITLE
Fix `linkerd install --help` config values URL

### LINKED ISSUE #8911: `linkerd install --help` prints invalid URL
### What is the issue?

`linkerd install --help` prints invalid URL:

```
A full list of configurable values can be found at https://www.github.com/linkerd/linkerd2/tree/main/charts/linkerd2/README.md
```

This link leads to a 404.

### How can it be reproduced?

1. `linkerd install --help`
2. click/copy paste/follow the link https://www.github.com/linkerd/linkerd2/tree/main/charts/linkerd2/README.md

### Logs, error output, etc

HTTP 404

### output of `linkerd check -o short`

```text
$ linkerd check -o short
Linkerd core checks
===================

linkerd-existence
-----------------
× 'linkerd-config' config map exists
    configmaps "linkerd-config" not found
    see https://linkerd.io/2.11/checks/#l5d-existence-linkerd-config for hints

Status check results are ×
```

### Environment

macOS, `linkerd` is installed via Homebrew.

### Possible solution

Fix the link :)

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #8911 

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

**Review by mateiidavid — APPROVED** [review]

File: cli/cmd/install.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ control plane.`,
   linkerd install | kubectl apply -f -
 
 The installation can be configured by using the --set, --values, --set-string and --set-file flags.
-A full list of configurable values can be found at https://www.github.com/linkerd/linkerd2/tree/main/charts/linkerd2/README.md`,
+A full list of configurable values can be found at https://www.github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/README.md`,
```
Comment (olix0r) [inline cli/cmd/install.go:108]: While, this is definitely an improvement, it still seems fraught to have a link from released CLI versions to the `main` branch of the repo, for exactly the same reasons that caused this link to break previously.

It would be better to at least link to the published artifacts like https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-control-plane; but even this is difficult because of the edge/stable distinction. Do we publish this information on linkerd.io's docs? Or perhaps we can refer to linkerd's docs more generally?

Comment (adleong) [reply cli/cmd/install.go:108]: What about linking to https://artifacthub.io/packages/helm/linkerd2/linkerd2#values ?

Comment (olix0r) [reply cli/cmd/install.go:108]: @adleong That's the old chart being replaced in 2.12

Comment (adleong) [reply cli/cmd/install.go:108]: https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane#values then, with the expectation that the chart will be published during the release?

File: cli/cmd/install.go [hunk 2]
```diff
@@ -105,7 +105,7 @@ control plane.`,
   linkerd install | kubectl apply -f -
 
 The installation can be configured by using the --set, --values, --set-string and --set-file flags.
-A full list of configurable values can be found at https://www.github.com/linkerd/linkerd2/tree/main/charts/linkerd2/README.md`,
+A full list of configurable values can be found at https://www.artifacthub.io/packages/helm/linkerd2/linkerd2#values`,
```
Comment (adleong) [inline cli/cmd/install.go:108]: That link isn't working for me, and it targets the old chart.  Should this be https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-control-plane ?

Comment (adleong) [reply cli/cmd/install.go:108]: should we have some logic to conditionally set `linkerd2-edge` vs `linkerd2` depending on if this is a stable build?

Comment (kleimkuhler) [reply cli/cmd/install.go:108]: Oh weird I added `www` after copying the URL but it doesn't like that; I'll remove it. We could point it to the edge but it seems like a better idea to point it to stable for now.

Comment (adleong) [reply cli/cmd/install.go:108]: The weird thing about that is the linkerd-control-plane chart hasn't had a stable release yet.  Which means that if we link to https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane there's nothing there yet.  So all the edge releases until the stable will have a broken link.  And, going forward, as we add new values in future edges, they won't be reflected in the stable docs.

**Review by olix0r — APPROVED** [review]

**Comment by kleimkuhler** [comment]
In preparation for the `linkerd-control-plane` chart being introduced in the soon-to-be-released stable, I've changed the help text to point to that chart.

**Review by adleong — APPROVED** [review]
