### PR TITLE
Issue 2276: Do not log error when timeout is blank

### LINKED ISSUE #2276: proxy-api logs errors when route timeout isn't set
When a route does not specify a timeout, the proxy-api defaults to the default timeout and logs an error:

```
time="2019-02-13T16:29:12Z" level=error msg="failed to parse duration for route POST /io.linkerd.proxy.destination.Destination/GetProfile: time: invalid duration "
```

We should not log any error when the timeout is blank.  Additionally, having service profile name and namespace in logs like this could be helpful.

### Environment

- Linkerd version: stable-2.2.0

### PR DESCRIPTION
**Pull request by kleimkuhler**
# Problem

When a route does not specify a timeout, the proxy-api defaults to the default
timeout and logs an error:

```
time="2019-02-13T16:29:12Z" level=error msg="failed to parse duration for route POST /io.linkerd.proxy.destination.Destination/GetProfile: time: invalid duration"
```

# Solution

We now check if a route timeout is blank. If it is not set, it is set to
`DefaultRouteTimeout`. If it is set, we try to parse it into a `Duration`.

A request was made to improve logging to include the service profile and
namespace as well.

# Validation

With valid service profiles installed, edit the `.yaml` to include an invalid
`timeout`:

```
...
name: GET /
timeout: foo
```

We should now see the following errors:

```
proxy-api time="2019-02-13T22:27:32Z" level=error msg="failed to parse duration for route 'GET /' in service profile 'webapp.default.svc.cluster.local' in namespace 'default': time: invalid duration foo"
```

This error does not show up when `timeout` is blank.

Fixes #2276

Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>

### CODE REVIEW

File: pkg/profiles/profiles.go [hunk 1]
```diff
@@ -105,10 +105,19 @@ func ToRoute(route *sp.RouteSpec) (*pb.Route, error) {
...
-		log.Errorf("failed to parse duration for route %s: %s", route.Name, err)
-		timeout = DefaultRouteTimeout
+	timeout := DefaultRouteTimeout
+	if route.Timeout != "" {
+		timeout, err = time.ParseDuration(route.Timeout)
+		if err != nil {
+			log.Errorf(
+				"failed to parse duration for route '%s' in service profile '%s' in namespace '%s': %s",
+				route.Name,
+				profile.ObjectMeta.Name,
```
Comment (adleong) [inline pkg/profiles/profiles.go]: I might be mistaken, but I think you can just do `profile.Name` and `profile.Namespace`.

Comment (kleimkuhler) [reply pkg/profiles/profiles.go]: > I might be mistaken, but I think you can just do `profile.Name` and `profile.Namespace`.

Right - thanks!
