### PR TITLE
Validate `--default-inbound-policy` values

### LINKED ISSUE #9148: Add validation for the --default-inbound-policy flag
### What problem are you trying to solve?

The `linkerd install` command supports a `--deault-inbound-policy` flag.  However, this flag accepts any string value, even if it's not a supported policy mode.  This can make it difficult to know exactly what the supported values are or can allow unexpected behavior when an incorrect value is supplied and no error feedback is generated:

```console
> linkerd install --default-inbound-policy=farts
```

yields no errors.

### How should the problem be solved?

Validate that the value provided is one of the supported policy modes.

### Any alternatives you've considered?

Suffer.

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

_No response_

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #9148

With this change, the value of `—default-inbound-policy` is verified to be one of the accepted values. 

When the value is not an accepted value we now error

```shell
$ linkerd install --default-inbound-policy=everybody
Error: --default-inbound-policy must be one of: all-authenticated, all-unauthenticated, cluster-authenticated, cluster-unauthenticated, deny
Usage:
  linkerd install [flags]
...
```

A unit test has also been added.

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

File: cli/cmd/options.go [hunk 1]
```diff
@@ -622,6 +627,16 @@ func validateProxyValues(values *l5dcharts.Values) error {
 	return nil
 }
 
+func validatePolicy(policy string) error {
+	validPolicies := []string{"all-authenticated", "all-unauthenticated", "cluster-authenticated", "cluster-unauthenticated", "deny"}
```
Comment (hawkw) [inline cli/cmd/options.go:631]: tiny nit: since this is a fixed size array, should we use 
```suggestion
	validPolicies := [...]string{"all-authenticated", "all-unauthenticated", "cluster-authenticated", "cluster-unauthenticated", "deny"}
```
here rather than a slice?

i was going to suggest that it should be a constant, but i learned Go does not have `const` arrays

File: cli/cmd/options.go [hunk 2]
```diff
@@ -622,6 +627,16 @@ func validateProxyValues(values *l5dcharts.Values) error {
...
+	for _, p := range validPolicies {
+		if p == policy {
+			return nil
+		}
+	}
+	return fmt.Errorf("--default-inbound-policy must be one of: %s", strings.Join(validPolicies, ", "))
```
Comment (hawkw) [inline cli/cmd/options.go:637]: nit, take it or leave it: should we include the invalid value here?
```suggestion
	return fmt.Errorf("--default-inbound-policy must be one of: %s (got %s)", strings.Join(validPolicies, ", "), policy)
```

**Review by hawkw — APPROVED** [review]
looks good to me! couple of very small suggestions, but none of them are blockers.

**Review by adleong — APPROVED** [review]

File: cli/cmd/options.go (hunk 1 above)
Comment (kleimkuhler) [reply cli/cmd/options.go:631]: I'm going to keep this as a slice mainly because of the error formatting below. `strings.Join` has to take a slice, so if this was changed to an array it would just be converted to a slice later anyways (`strings.Join(validPolicies[:], ", ")`).
