### PR TITLE
Deprecate `topologyKeys` and add support for endpoint slices `Hints`.

### LINKED ISSUE #6637: Deprecate `topologyKeys` API in endpoints watcher
Upgrading to `k8s.io/api@v0.22.0` requires deprecating the `topologyKeys` API in the service spec. The following dep bump PRs that depend on this are currently failing: #6615, #6616, #6617, #6618, #6619.

When these are all grouped into a single change, the errors are more specific: `controller/api/destination/watcher/endpoints_watcher.go:468:55: newService.Spec.TopologyKeys undefined (type "k8s.io/api/core/v1".ServiceSpec has no field or method TopologyKeys)`.

It looks like we should now look at the endpoints object `hints` field as documented [here](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/)

### PR DESCRIPTION
**Pull request by kleimkuhler**
## background

In order to upgrade `client-go` and other related libraries to `v0.22.0`, we had to address the deprecation of the service's `TopologyKeys` field. This field and it's related feature have been deprecated and superseded by [Topology Aware Hints](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2433-topology-aware-hints/README.md).

The goal of topology aware hints is to to provide a simpler way for users to prefer endpoints by basing decisions soely off the node's `topology.kubernetes.io/zone` label. If a node is in `zone-a`, then it should prefer endpoints that _should_ be consumed by clients in `zone-a`.

kube-proxy (and now the destination controller) know that an endpoint _should_ be consumed by clients in certain zones if its `Hints.ForZones` field is set with a zone value that matches that of the client.

For example, the endpoint slice controller may add the following hint to an endpoint:
```
- addresses: ["1.1.1.1"]
  zone: "zone-a"
  hints:
    zone: "zone-b"
```

The above endpoint is an endpoint that is located in `zone-a` but should be consumed by clients in `zone-b`.

## changes

Now that topological preference is not a concept, we can remove it from the `servicePublisher` and `portPublisher` structs. The fields were only there so that it could be populated down to individual addresses.

The `Hints` field is only present on endpoints that belong to an `EndpointSlice`, so use of this field is limited to the `endpointSliceToAddresses` function.

When endpoint slices are translated to an `AddressSet` now, for each address (endpoint) we make sure to copy the `Hints.ForZones` field if it is present. This field is only present if it's set by the endpoint slice controller and it has [several safeguards](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/#safeguards).

After `endpointSliceToAddresses` has translated an endpoint slice into an `AddressSet` and updated the endpoint translator's `availableEndpoints`, filtering takes place and is the crux of this change.

For each potential address that we have to consider in `availableEndpoints`, we make sure to only return a set of addresses who's consumption zone (zones in `forZones` field) match that of the node's zone. That way, we only communicate with endpoints that have been labeled by the endpoint slice controller for the current node we're on.

This allows us to remove the ordering/hierarchy of topological region and considering the `*` value.

## testing

I've added a unit test which creates an endpoint translator tied to a node in `west-1a` and asserts that it only handles updates for addresses that should be consumed by clients in `west-1a`.

Closes #6637

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

### CODE REVIEW

File: controller/api/destination/endpoint_translator.go [hunk 1]
```diff
@@ -383,29 +380,23 @@ func toWeightedAddr(address watcher.Address, opaquePorts, skippedInboundPorts ma
...
+		return "", err
 	}
-
 	for k, v := range node.Labels {
-		if k == corev1.LabelHostname ||
-			k == corev1.LabelZoneFailureDomainStable ||
-			k == corev1.LabelZoneRegionStable {
-			nodeTopology[k] = v
+		if k == corev1.LabelTopologyZone {
+			return v, nil
```
Comment (mateiidavid) [inline controller/api/destination/endpoint_translator.go:390]: Now that we only have one label that we're after perhaps we can just do a quicker lookup in the map rather than traverse it.

```suggestion
// take out 'for' loop
v, ok := node.Labels[corev1.LabelTopologyZone]
```

File: controller/api/destination/watcher/endpoints_watcher.go [hunk 2]
```diff
@@ -49,14 +49,13 @@ type (
 		OwnerKind         string
 		Identity          string
 		AuthorityOverride string
-		TopologyLabels    map[string]string
+		ForZones          []discovery.ForZone
```
Comment (mateiidavid) [inline controller/api/destination/watcher/endpoints_watcher.go:52]: quite cool they have a type for this

**Review by mateiidavid — COMMENTED** [review]
Everything looks great to me so far, I'll do another in-depth review with some manual testing (especially to test the new constraints). One thing that I thought about as I was looking through the code: the slice controller will add these zonal hints on endpoints only when we put this annotation on the service `you can activate Topology Aware Hints for a Service by setting the service.kubernetes.io/topology-aware-hints=auto`. Is this something we want to consider? Perhaps we can use it instead of a feature gate? Don't have any concrete plans just wanted to see if you have any thoughts on it.

File: .github/workflows/integration_tests.yml [hunk 3]
```diff
@@ -86,6 +86,9 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
+    - uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
+      with:
+        go-version: '1.16'
```
Comment (kleimkuhler) [inline .github/workflows/integration_tests.yml:91]: We're already using go 1.16 in [go.mod](https://github.com/linkerd/linkerd2/blob/a866aa416c09fafdf384eaba3ac8aa5c74678c19/go.mod#L3), but the ubuntu 20.04 image defaults to go 1.15. This ensures we use go 1.16 which is required for upgrading these dependencies.

**Comment by adleong** [comment]
Do we need to keep support for topologyKeys for a deprecation cycle?  Per https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2433-topology-aware-hints/README.md#interoperability, kube-proxy will use topologyKeys instead of hints if topologyKeys are defined.  As written here, any topologyKeys behavior would abruptly stop being respected when this is released.

Am I understanding correctly that endpoint hints don't have any notion of fallback?  i.e. if hints are defined for all endpoints but there are no available endpoints for the client's zone, we should treat that as if no endpoints are available at all?

**Comment by adleong** [comment]
I tested this by spinning up a 3 node kind cluster with topology aware hints enabled using this kind config:

```yaml
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=zone-a"
- role: worker
  image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=zone-b"
- role: worker
  image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=zone-c"
featureGates:
#  ServiceTrafficPolicy: true
  TopologyAwareHints: true
```

I then deployed emojivoto to the cluster, scaled the web deployment to 6 replicas, and annotated the web-svc with 

```
k -n emojivoto annotate svc/web-svc service.kubernetes.io/topology-aware-hints=auto
```

I checked that zone hints were correctly being set on the endpoints slices:

```console
> k get -n emojivoto endpointslices/web-svc-k49sk -ojsonpath='{range .endpoints[*]}{.hints}{"\n"}{end}'
{"forZones":[{"name":"zone-a"}]}
{"forZones":[{"name":"zone-a"}]}
{"forZones":[{"name":"zone-c"}]}
{"forZones":[{"name":"zone-c"}]}
{"forZones":[{"name":"zone-b"}]}
{"forZones":[{"name":"zone-b"}]}
```

Then I tried querying the destination controller with the destination client script, setting the source node name in the context token:

```console
> go run controller/script/destination-client/main.go -method get -path web-svc.emojivoto.svc.cluster.local:80 --token '{"nodeName":"alex-worker2"}'
```

(Note that this required a small update to the destination client script to add the `--token` flag and have it set the context token in the Get request)

Unfortunately, this returned all 6 addresses instead of just the 2 that were hinted to be for alex-worker2 (aka zone-c).  

There are a lot of steps here, so it's possible that I did something wrong.  @kleimkuhler do you see the same behavior, or is this filtering down correctly for you?

**Comment by kleimkuhler** [comment]
After some off-GH discussion the reason this was not working in the comment above is that the destination service did not have the EndpointSlice feature turned on.

After installing a cluster with `--set enableEndpointSlices=true` or running locally and passing the `-enable-endpoint-slices` flag, this works as expected.

A separate issue will be opened to investigate if its worth enabling this by default now that EndpointSlices are enabled by default on our minimum version of 1.20.

File: controller/api/destination/endpoint_translator.go [hunk 4]
```diff
@@ -110,58 +109,56 @@ func (et *endpointTranslator) sendFilteredUpdate(set watcher.AddressSet) {
...
-		srcLocality, ok := et.nodeTopologyLabels[pref]
-		if !ok {
-			continue
+	// If any address does not have a hint, then all hints are ignored and all
+	// available addresses are returned. This replicates kube-proxy behavior
+	// documented in the KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2433-topology-aware-hints/README.md#kube-proxy
+	for _, address := range et.availableEndpoints.Addresses {
+		if len(address.ForZones) == 0 {
+			return watcher.AddressSet{
+				Addresses: allAvailEndpoints,
```
Comment (adleong) [inline controller/api/destination/endpoint_translator.go:128]: Any reason that we create this copy of `et.availableEndpoints.Addresses` instead of just returning `et.availableEndpoints.Addresses` here directly?

File: controller/api/destination/endpoint_translator.go [hunk 5]
```diff
@@ -110,58 +109,56 @@ func (et *endpointTranslator) sendFilteredUpdate(set watcher.AddressSet) {
...
+	if len(filtered) > 0 {
+		et.log.Debugf("Filtered from %d to %d addresses", len(et.availableEndpoints.Addresses), len(filtered))
+		return watcher.AddressSet{
+			Addresses: filtered,
+			Labels:    et.availableEndpoints.Labels,
 		}
 	}
 
-	// if we have no filtered endpoints or the '*' preference then no topology pref is satisfied
+	// If there were no filtered addresses then the empty set is returned.
```
Comment (adleong) [inline controller/api/destination/endpoint_translator.go:153]: I think safeguard 5 here means that we should return the full address set: https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/#safeguards

Comment (kleimkuhler) [reply controller/api/destination/endpoint_translator.go:153]: Yep good catch.

**Comment by kleimkuhler** [comment]
@mateiidavid If you don't mind giving this another review it's mostly been a while but has also changed a little since your initial approval.

**Review by adleong — APPROVED** [review]
Nice!

File: controller/api/destination/watcher/endpoints_watcher.go [hunk 6]
```diff
@@ -755,8 +732,8 @@ func (pp *portPublisher) endpointSliceToAddresses(es *discovery.EndpointSlice) A
 					continue
 				}
 
-				for k, v := range endpoint.Topology {
-					address.TopologyLabels[k] = v
+				if endpoint.Hints != nil {
+					address.ForZones = endpoint.Hints.ForZones
```
Comment (mateiidavid) [inline controller/api/destination/watcher/endpoints_watcher.go:736]: Very nitpicky, but I wonder if it's better to clone this here? Not sure there are any real performance implications since the address set should be shortlived (and I assume garbage cleaned at some point).

**Review by mateiidavid — APPROVED** [review]
Manually tested this (thank you @adleong for the steps)! I set up a `kind` cluster with 2 nodes (the config is in one of my earlier comments), after scaling the `web` deployment to 6 replicas, I got 3 hinted for "zone-a" and 3 hinted for "zone-b".

```json
{"forZones":[{"name":"zone-a"}]}
{"forZones":[{"name":"zone-a"}]}
{"forZones":[{"name":"zone-a"}]}
{"forZones":[{"name":"zone-b"}]}
{"forZones":[{"name":"zone-b"}]}
{"forZones":[{"name":"zone-b"}]}
```

I tested by running the destination client and destination service locally:
```
go run controller/script/destination-client/main.go -method get -path web-svc.emojivoto.svc.cluster.local:80 --token '{"nodeName":"topology-zone-test-worke
r"}'
INFO[0000] labels: map[namespace:emojivoto service:web-svc]
INFO[0000] - 10.244.1.17:8080
INFO[0000]   - labels: map[control_plane_ns:linkerd deployment:web pod:web-568649f897-s2hrp pod_template_hash:568649f897 serviceaccount:web]
INFO[0000]   - protocol hint: H2
INFO[0000]   - identity: dns_like_identity:{name:"web.emojivoto.serviceaccount.identity.linkerd.cluster.local"}
INFO[0000] - 10.244.1.19:8080
INFO[0000]   - labels: map[control_plane_ns:linkerd deployment:web pod:web-568649f897-5w44h pod_template_hash:568649f897 serviceaccount:web]
INFO[0000]   - protocol hint: H2
INFO[0000]   - identity: dns_like_identity:{name:"web.emojivoto.serviceaccount.identity.linkerd.cluster.local"}
INFO[0000] - 10.244.1.18:8080
INFO[0000]   - labels: map[control_plane_ns:linkerd deployment:web pod:web-568649f897-7v9vv pod_template_hash:568649f897 serviceaccount:web]
INFO[0000]   - protocol hint: H2
INFO[0000]   - identity: dns_like_identity:{name:"web.emojivoto.serviceaccount.identity.linkerd.cluster.local"}
```

All returned addresses were hinted for "zone-b", which this node belongs to, e.g:
```yaml
- addresses:
  - 10.244.1.17
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: zone-b
```

Looks and works great!
