### PR TITLE
Fix linkerd check --proxy failure on Jobs

### LINKED ISSUE #6128: linkerd `check --proxy` appears to fail on Completed Job Pods
### What is the issue?
I've successfully got kubernetes CronJobs to work with linkerd-proxy injection by using the linkerd-away wrapper, however if I check the proxy status in the target namespace `linkerd check --proxy -n <namespace>` the linkerd CLI will never exit.  It appears to be stuck checking the proxy container in the "Completed" Pod that is no longer running.

Using `--verbose` mode does not yield any more information.
Output continues to be `         | waiting for check to complete` until linkerd-cli is kill (ctrl-C).

### How can it be reproduced?
 - Run a "Batch" Pod (CronJob or Job) with the linkerd-await so it exits properly.
 - run linkerd-cli to check the proxy status: `linkerd check --proxy -n <target namespace>`
 - wait and nothing happens until you either delete all Completed Pods or manually terminate linkerd CLI.

### Environment

- Kubernetes Version:  v1.19.6 (DigitalOcean) / v1.19.9 (GCP)
- Cluster Environment: DOKS (DigitalOcean) / GCP
- Host OS: Debian GNU/Linux 10 (buster) - DigitalOcean / Container-Optimized OS from Google
- Linkerd version: 2.10.1  (install via Helm)

### Possible solution
Delete all completed Job Pods before running `linker check --proxy`

### Expected Behaviour
linkerd check should detect that a Pod is no longer running and skip the proxy check on that pod.

### PR DESCRIPTION
**Pull request by dadjeibaah**
When `linkerd check --proxy` is run in a given namespace, the check
command ensures that all pods within that namespace have a running proxy
and that and the pod is in a `Running` status.

This however, is not necessarily true when dealing with CronJobs or Jobs
as these resources create pods that run their containers for a short period
of time and then terminate. When these pods terminate, they get placed
in a `Completed` phase and their sidecars are no longer running. This
causes an issue in `linkerd check --proxy` because that command expects
that pods will always be in a running state.

This change effectively skips checking the proxy status of a pod if that
pod is in a `Completed` phase as a pod no longer has an actively running
proxy

Fixes #6128

Signed-off-by: Dennis Adjei-Baah <dennis@buoyant.io>

### CODE REVIEW

File: pkg/healthcheck/healthcheck.go [hunk 1]
```diff
@@ -2500,6 +2500,12 @@ func validateDataPlanePods(pods []corev1.Pod, targetNamespace string) error {
 
 	for _, pod := range pods {
 		status := k8s.GetPodStatus(pod)
+		// Skip validing meshed pods that are in the `Completed` state
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck.go:2503]: nit:

```suggestion
		// Skip validating meshed pods that are in the `Completed` state
```

File: pkg/healthcheck/healthcheck_test.go [hunk 2]
```diff
@@ -1645,6 +1645,65 @@ func TestValidateDataPlanePods(t *testing.T) {
...
 		}
 	})
+
+	// This test relates to https://github.com/linkerd/linkerd2/issues/6128
+	t.Run("Returns nil if some pods are in the Succeeded phase and their proxies are no longer ready", func(t *testing.T) {
+		pods := []corev1.Pod{
+			{
+				ObjectMeta: metav1.ObjectMeta{Name: "emoji-d9c7866bb-7v74n"},
+				Status: corev1.PodStatus{
+					Phase: "Succeeded",
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck_test.go:1655]: Do we need to specify `Reason: "Completed"` here? IIUC a pod's status is `completed` when its phase is `Succeeded` and the reason is `Completed`, it seems the test pass without it though so not sure but would love to hear more about it, pod statuses are still a bit foreign to me.

**Review by mateiidavid — APPROVED** [review]
Looks good! I haven't managed to reproduce the issue unfortunately but the logic seems good in relation to the issue filed 👍🏻

File: pkg/healthcheck/healthcheck_test.go (hunk 2 above)
Comment (dadjeibaah) [reply pkg/healthcheck/healthcheck_test.go:1655]: Thanks for pointing this out. It looks like this test isn't quite right so I'll be fixing that in the next commit. However, the test can still fail if we don't include the `Reason: Completed` field. It definitely wouldn't hurt to include that since that is closer to what we'd get in an actual environment.

**Comment by dadjeibaah** [comment]
@mateiidavid, agreed that testing this was a little bit of a challenge. They way I did it was I created a small batch program that waited for 30 seconds and then quit. I then published that in its own namespace and ran linkerd check proxy on that namespace.

Here are the files I used
https://gist.github.com/dadjeibaah/3d1a09cb7971b8fb2820b29892cf5711

**Review by olix0r — APPROVED** [review]
