### PR TITLE
fix(multicluster): make service cleanup logic respect namespaces

### LINKED ISSUE #15200: Service mirror cleanup logic does not respect namespaces
### What is the issue?

We have two headless multi-cluster services with the same name (and thus the same `mirror.linkerd.io/headless-mirror-svc-name` label on all endpoint mirror services) in two different namespaces. These services front a StatefulSet with differing numbers of replicas. On reconcile, the service mirror controller seems to be deleting the endpoint mirror services for pods that are healthy in the remote cluster. I'd expect the service mirror to leave the endpoint mirror services for the healthy pods alone.

I also posted about this issue in the Slack channel [here](https://linkerd.slack.com/archives/C89RTCWJF/p1776779919651119).

### How can it be reproduced?

1.  Create two headless services and StatefulSets with the same name in two separate namespaces in the remote cluster.
2. Set the number of replicas to 1 and 2 for the first and second STS, respectively.
3. On reconcile, check that there is only 1 endpoint mirror service in the local cluster for the namespace with 2 replicas. The endpoint mirror service for the second replica will be missing or created and then quickly deleted.

This pattern doesn't happen on every reconcile but you should notice a lot of churn for the 2nd replica's endpoint mirror service.

### Logs, error output, etc

Controller logs:
```
time="2026-04-21T13:49:36Z" level=info msg="Creating a new endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-2-gke-us-central1-prod for exported headless service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1" cluster=gke-us-central1-prod
time="2026-04-21T13:49:36Z" level=info msg="Creating a new endpoints object for endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-2-gke-us-central1-prod" cluster=gke-us-central1-prod
time="2026-04-21T13:49:36Z" level=info msg="Creating a new endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-3-gke-us-central1-prod for exported headless service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1" cluster=gke-us-central1-prod
time="2026-04-21T13:49:36Z" level=info msg="Creating a new endpoints object for endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-3-gke-us-central1-prod" cluster=gke-us-central1-prod
time="2026-04-21T13:49:36Z" level=info msg="Creating a new endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-4-gke-us-central1-prod for exported headless service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1" cluster=gke-us-central1-prod
time="2026-04-21T13:49:37Z" level=info msg="Creating a new endpoints object for endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-4-gke-us-central1-prod" cluster=gke-us-central1-prod
time="2026-04-21T13:49:37Z" level=info msg="Creating a new endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-1-gke-us-central1-prod for exported headless service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1" cluster=gke-us-central1-prod
time="2026-04-21T13:49:37Z" level=info msg="Creating a new endpoints object for endpoint mirror service gf-lw-production-usa-t2j9zb/c4t2a-xl-gpt-1-1-gke-us-central1-prod" cluster=gke-us-central1-prod
```

Kubernetes audit logs showing the creations and deletions:
```
DEFAULT 2026-04-21T13:49:36.350154Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: create] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-2-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.create", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:36.748156Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: create] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-3-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.create", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:37.143899Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: create] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-4-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.create", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:37.552828Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: create] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-1-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.create", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:38.769550Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: delete] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-2-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.delete", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:38.972733Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: delete] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-4-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.delete", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:39.178539Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: delete] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-3-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.delete", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
DEFAULT 2026-04-21T13:49:39.374535Z [resource.labels.clusterName: production] [protoPayload.serviceName: Kubernetes Apiservice Requests] [protoPayload.methodName: delete] [protoPayload.resourceName: core/v1/namespaces/gf-lw-production-usa-t2j9zb/services/c4t2a-xl-gpt-1-1-gke-us-central1-prod] [protoPayload.authenticationInfo.principalEmail: system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod] audit_log, method: "io.k8s.core.v1.services.delete", principal_email: "system:serviceaccount:linkerd-multicluster:linkerd-service-mirror-gke-us-central1-prod"
``` 

### output of `linkerd check -o short`

N/A

### Environment

- Kubernetes version: 1.33.5
- Linkerd version: edge-26.4.1

### Possible solution

The issue occurs in [this line](https://github.com/linkerd/linkerd2/blob/f039635d7b218f12a2ea9fc15bbad4e5196022d1/multicluster/service-mirror/cluster_watcher_headless.go#L145) because it lists all services matching the `mirror.linkerd.io/headless-mirror-svc-name` label across the whole cluster. Because the[ endpoint mirrors set](https://github.com/linkerd/linkerd2/blob/f039635d7b218f12a2ea9fc15bbad4e5196022d1/multicluster/service-mirror/cluster_watcher_headless.go#L98-L137) only contains the names of services in the namespace of the exported service, it ends up deleting other services in the cluster with the same label if they don't appear in the map. In the case of the reproduction, it deletes the endpoint mirror service for the second replica of the STS.

Restricting this list call to just the namespace of the exported service will fix the issue.

### Additional context

_No response_

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by cbond-cohere**
createOrUpdateHeadlessEndpoints and handleRemoteServiceUnexported compare a list of namespace-level endpoint mirror services to a cluster-wide list of services that match the headless mirror name. This results in unintended service deletion when multiple headless mirror services of the same name exist in different namespaces. Fix this by restricting the list call to the namespace of the exported service.

Fixes https://github.com/linkerd/linkerd2/issues/15200

### CODE REVIEW

**Review by maxbrunet — APPROVED** [review]
LGTM, thank you for debugging and fixing this!

File: multicluster/service-mirror/cluster_watcher_headless.go [hunk 1]
```diff
@@ -142,7 +142,7 @@ func (rcsw *RemoteClusterServiceWatcher) createOrUpdateHeadlessEndpoints(ctx con
 	}
 
 	// Fetch all Endpoint Mirror services that belong to the same Headless Mirror
-	endpointMirrorServices, err := rcsw.localAPIClient.Svc().Lister().List(labels.Set(matchLabels).AsSelector())
+	endpointMirrorServices, err := rcsw.localAPIClient.Svc().Lister().Services(exportedService.Namespace).List(labels.Set(matchLabels).AsSelector())
```
Comment (unleashed) [inline multicluster/service-mirror/cluster_watcher_headless.go:145]: Not very familiar with this code, but there's this other listing of headless mirror services at [cluster_watcher.go:566](https://github.com/linkerd/linkerd2/blob/main/multicluster/service-mirror/cluster_watcher.go#L566) in `handleRemoteServicesUnexported`, which seems to be the same pattern. Should that also get a similar fix?

Comment (cbond-cohere) [reply multicluster/service-mirror/cluster_watcher_headless.go:145]: Thanks for pointing that out, that would cause a similar issue on mirror service delete. I can push a fix for that as well.

Comment (cbond-cohere) [reply multicluster/service-mirror/cluster_watcher_headless.go:145]: Pushed a fix and added a test case for this as well.

Comment (unleashed) [reply multicluster/service-mirror/cluster_watcher_headless.go:145]: Thanks!

**Review by adleong — APPROVED** [review]
Great find and nice fix!

**Comment by adleong** [comment]
It looks like there's a lint error where one of the test parameter can be removed.

**Comment by cbond-cohere** [comment]
> It looks like there's a lint error where one of the test parameter can be removed.

Thanks @adleong! I ended up putting in an ignore directive for these warnings since other functions in the test suite ignore this particular check. Happy to remove the parameters altogether if you prefer.
