### PR TITLE
Integration tests: Warn (instead of erroring) upon pod restarts

### LINKED ISSUE #4595: CI: restart count flakiness
We frequently see CI flakiness that manifests as:

```
--- FAIL: TestResourcesPostInstall (46.26s)
    uninstall_test.go:54: Error validating pods for deploy [linkerd-grafana]:
        Container [linkerd-proxy] in pod [linkerd-grafana-65b4cf7cdb-skjnm] in namespace [l5d-integration] has restart count [1]
FAIL
found unexpected warning event: reason: [Failed] Object: [linkerd-grafana-65b4cf7cdb-skjnm] Message: [Error: failed to create containerd task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo "/run/containerd/io.containerd.grpc.v1.cri/containers/linkerd-proxy/io/643455312/linkerd-proxy-stdout" failed: context deadline exceeded]
FAIL	command-line-arguments	91.725s
FAIL
```

What causes these restarts?

If they are innocuous, should these assertions be removed/relaxed/

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #4595

Don't have integration tests fail whenever a pod is detected to have
restarted just once. For now we'll be just logging this out and creating
a warning annotation for it.

### CODE REVIEW

File: testutil/kubernetes_helper.go [hunk 1]
```diff
@@ -26,6 +27,19 @@ type KubernetesHelper struct {
 	retryFor   func(time.Duration, func() error) error
 }
 
+// RestartCountError is returned by CheckPods() whenever a pod has restarted exactly one time.
+// Consumers should log this type of error instead of failing the test.
+// This is to alleviate CI flakiness stemming from a containerd bug.
+// See https://github.com/kubernetes/kubernetes/issues/89064
+// See https://github.com/containerd/containerd/issues/4068
+type RestartCountError struct {
+	s string
```
Comment (adleong) [inline testutil/kubernetes_helper.go:36]: should we call this field `message`, `reason`, or something similar?
