### PR TITLE
Issue individual warnings for nodes missing podCIDRs

### LINKED ISSUE #7760: Change `clusterNetworks` check to be stricter
### What problem are you trying to solve?

Our `clusterNetworks` healthcheck will iterate through the nodes in the cluster and check whether the `podCIDR` value, taken from the node spec, matches the values used for Linkerd's control plane.

Some Kubernetes distributions do not expose a value for this field; to make sure the check doesn't fail, we skip the node. If all nodes are skipped, we issue a warning that the check itself was skipped, leaving it up to the operator/user to decide what to do with this information.

We should be a bit stricter here, if at least one node is skipped, we should issue a warning. I'm not sure how likely it is for this configuration to not be uniformly applied to all nodes, but it would be good to be a bit more defensive and have a tighter check in place.

### How should the problem be solved?

The code for this check can be found below:

https://github.com/linkerd/linkerd2/blob/f9ba4eb1ead68d6a9fe9daa85ee9b3ce7d617626/pkg/healthcheck/healthcheck.go#L1864-L1884

If at least one node in the set has a `podCIDR` field, then `podCIDRExists` is set to true. As a result, no skip message will be printed. We should flip this logic around. I think for the purpose of this issue, we should continue to verify the networks and just issue a warning if at least one (but not all) isn't verfiable.

We could add some additional metadata in the warning perhaps, like the node name that doesn't expose the field. 

### Any alternatives you've considered?

N/A

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

_No response_

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #7760

This introduces a new warning check that ensures we can verify the cluster networks. This check is separate from the existing `cluster networks contains all node podCIDRs` because unlike this existing check which results in an error, this new check is just a warning.

When a node is missing the field

```
$ linkerd check -o short
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
        k3d-k3s-default-agent-0
        k3d-k3s-default-server-0
        k3d-k3s-default-agent-1
    see https://linkerd.io/2/checks/#l5d-cluster-networks-verified for hints
```

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

File: pkg/healthcheck/healthcheck.go [hunk 1]
```diff
@@ -1857,10 +1857,13 @@ func (hc *HealthChecker) checkClusterNetworks(ctx context.Context) error {
 		}
 	}
 	var badPodCIDRS []string
+	var nodesSkipped []string
+	var errStrings []string
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck.go:1861]: We could probably inline some of these declarations if we're not using the shorthand `:=`, it might make everything look a bit cleaner imo.

```suggestion
	var nodesSkipped, errStrings []string
```

File: pkg/healthcheck/healthcheck.go [hunk 2]
```diff
@@ -1857,10 +1857,13 @@ func (hc *HealthChecker) checkClusterNetworks(ctx context.Context) error {
...
 	var podCIDRExists bool
 	for _, node := range nodes {
 		podCIDR := node.Spec.PodCIDR
 		if podCIDR == "" {
+			nodesSkipped = append(nodesSkipped, node.Name)
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck.go:1866]: Is it necessary to loop through the nodes again? Can't we append to the list of errors in this main loop? I think we might be able to simplify this by not requiring an additional array just for the nodes.

```suggestion
if podCIDR == "" {
            err := fmt.Sprintf("node %s does not expose podCIDRs so clusterNetworks could not be verified", node.Name)
			errStrings = append(errStrings, err)
}
```

File: pkg/healthcheck/healthcheck.go [hunk 3]
```diff
@@ -1873,14 +1876,25 @@ func (hc *HealthChecker) checkClusterNetworks(ctx context.Context) error {
...
 		// DigitalOcean for example, doesn't expose spec.podCIDR (#6398)
 		return &SkipError{Reason: podCIDRUnavailableSkipReason}
 	}
+	// If there is at least one node that does not expose a podCIDR, issue a
+	// warning that clusterNetworks could not be completely verified.
+	if len(nodesSkipped) != 0 {
+		for _, node := range nodesSkipped {
+			errStrings = append(errStrings, fmt.Sprintf("node %s does not expose podCIDRs so clusterNetworks could not be verified", node))
+		}
+	}
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck.go:1890]: Think we can get rid of this based on my other suggestion?

File: pkg/healthcheck/healthcheck.go [hunk 4]
```diff
@@ -1873,14 +1876,25 @@ func (hc *HealthChecker) checkClusterNetworks(ctx context.Context) error {
...
 	if len(badPodCIDRS) > 0 {
 		sort.Strings(badPodCIDRS)
-		return fmt.Errorf("node has podCIDR(s) %v which are not contained in the Linkerd clusterNetworks.\n\tTry installing linkerd via --set clusterNetworks=\"%s\"",
-			badPodCIDRS, strings.Join(badPodCIDRS, "\\,"))
+		s := fmt.Sprintf("node has podCIDR(s) %v which are not contained in the Linkerd clusterNetworks.\n\tTry installing linkerd via --set clusterNetworks=\"%s\"", badPodCIDRS, strings.Join(badPodCIDRS, "\\,"))
+		errStrings = append(errStrings, s)
+	}
+	if len(errStrings) > 0 {
+		return fmt.Errorf(strings.Join(errStrings, "\n    "))
```
Comment (mateiidavid) [inline pkg/healthcheck/healthcheck.go:1897]: nit: we can just return a new error here since we're not really formatting anything.

```suggestion
		return errors.New(strings.Join(errStrings, "\n    "))
```

File: pkg/healthcheck/healthcheck.go (hunk 2 above)
Comment (kleimkuhler) [reply pkg/healthcheck/healthcheck.go:1866]: Yea good call.

**Review by mateiidavid — APPROVED** [review]
Looks great! 🚢

**Comment by adleong** [comment]
This generates an error, rather than a warning, right?  Ideally, we'd be able to generate a warning for when the podCIDR is missing (and therefore unverifiable) vs an error if the podCIDR is present but not contained within the cluster networks setting.  Unfortunately, I don't think we have a mechanism to change the warning/error level of a check depending on the result.  

What about this:

* Keep the existing cluster networks check as-is (error level, skipped if no nodes have podCIDR field)
* Add an additional check which verifies that all nodes have a podCIDR field (warning level)

**Comment by kleimkuhler** [comment]
I've split the checks and now we just issue a warning when cluster networks cannot be verified.

**Review by adleong — APPROVED** [review]
LGTM :+1:

The error message `the following nodes do not expose a podCIDR` is pretty cryptic on it's own so let's make sure we get good docs at that hint url which explain what this means and what to do about it.

**Comment by kleimkuhler** [comment]
Documented by linkerd/website#1301
