### PR TITLE
cli: restrict repair cmd with the same server version

### LINKED ISSUE #5917: linkerd repair segfault in 2.10.0
### What is the issue?

```text
$ linkerd repair
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17d910a]

goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.resetVersion(0xc000240500, 0x1210, 0x1300)
	/linkerd-build/cli/cmd/repair.go:123 +0x7a
github.com/linkerd/linkerd2/cli/cmd.newCmdRepair.func1(0xc00045ab00, 0x2d55fc8, 0x0, 0x0, 0x0, 0x0)
	/linkerd-build/cli/cmd/repair.go:65 +0x469
github.com/spf13/cobra.(*Command).execute(0xc00045ab00, 0x2d55fc8, 0x0, 0x0, 0xc00045ab00, 0x2d55fc8)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2d092a0, 0xc00018c010, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/linkerd-build/cli/main.go:34 +0x19f
```

### How can it be reproduced?

Running the repair command while upgrading a cluster from 2.9.2 to 2.10.0

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.9.2 but the latest stable version is 2.10.0
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.9.2 but cli running stable-2.10.0
    see https://linkerd.io/checks/#l5d-version-control for hints
```

### Environment

- Kubernetes Version: v1.17.11
- Cluster Environment: kops 
- Host OS: Debian stretch
- Linkerd version: 2.10.0

### Possible solution

Using linkerd version 2.9.4, the repair command works.

### Additional context

Non-helm.

```text
$ linkerd version
Client version: stable-2.10.0
Server version: stable-2.9.2
```

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #5917

Currently, When a repair cmd is ran with a CLI that is different
from the server version. This means it is possible for the cmd
to fail as the `Values` struct changes between versions.

This PR updates the cmd to restrict it to the version that the
server is on, but as the repair cmd is avialable only on `2.9.4`
we fall-back on to that version in the suggestion when the server
version is `2.9` or 2.8`.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Review by dadjeibaah — COMMENTED** [review]
This is looking good. When I run this command on a newer control plane version i.e. `21.3.3`, I still get the error message to download the CLI to match the server version. IIUC, there shouldn't be an issue with me running this command against `edge-21.3.3` since its `Values` struct is the same as the version in `2.9.4`, Is that correct?

When I do run it against a newer control plane version I get:
```
Error: Please run the repair command with a CLI version as that of the server.
Run `LINKERD2_VERSION="edge-21.3.3"; curl -sL https://run.linkerd.io/install | sh` to install the server version of the CLI
Usage:
  linkerd repair [flags]

Examples:
  linkerd repair | kubectl apply -f -

Flags:
  -h, --help   help for repair

Global Flags:
      --api-addr string            Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)
      --as string                  Username to impersonate for Kubernetes operations
      --as-group stringArray       Group to impersonate for Kubernetes operations
      --cni-namespace string       Namespace in which the Linkerd CNI plugin is installed (default "linkerd-cni")
      --context string             Name of the kubeconfig context to use
      --kubeconfig string          Path to the kubeconfig file to use for CLI requests
  -L, --linkerd-namespace string   Namespace in which Linkerd is installed ($LINKERD_NAMESPACE) (default "linkerd")
      --verbose                    Turn on debug logging

exit status 1
```

Version info:
```
Client version: git-90501cca
Server version: edge-21.3.3
```

File: cli/cmd/repair.go [hunk 1]
```diff
@@ -43,6 +47,31 @@ linkerd upgrade.`,
...
+			if err != nil {
+				return err
+			}
+			serverVersion, err = healthcheck.GetServerVersion(cmd.Context(), publicClient)
+			if err != nil {
+				return err
+			}
+
+			if serverVersion != clientVersion {
+				twoPointEightOrNineRegex, err := regexp.Compile("stable-2.[8-9].*")
```
[the remark this answers is not in the document]
Comment (Pothulapati) [reply cli/cmd/repair.go:63]: Yeah Makes sense. It was weird to name it this

File: cli/cmd/repair.go [hunk 2]
```diff
@@ -43,6 +47,31 @@ linkerd upgrade.`,
...
+				if err != nil {
+					return err
+				}
+				helperVersion := serverVersion
+				// Use 2.9.4 CLI version for all 2.9 versions
+				if twoPointEightOrNineRegex.Match([]byte(serverVersion)) {
+					helperVersion = "stable-2.9.4"
+				}
+				return fmt.Errorf("Please run the repair command with a CLI version as that of the server.\nRun `LINKERD2_VERSION=\"%s\"; curl -sL https://run.linkerd.io/install | sh` to install the server version of the CLI", helperVersion)
```
[the remark this answers is not in the document]
Comment (Pothulapati) [reply cli/cmd/repair.go:72]: It is the reverse right? on a CLI that has the same version as the control-plane

[the remark this answers is not in the document]
Comment (dadjeibaah) [reply cli/cmd/repair.go]: Ah yea, you are right, it should be reversed.

**Review by dadjeibaah — COMMENTED** [review]
LGTM! 📦 🚢 Thanks for making those updates

File: cli/cmd/repair.go [hunk 3]
```diff
@@ -43,6 +47,31 @@ linkerd upgrade.`,
...
+			if err != nil {
+				return err
+			}
+			serverVersion, err = healthcheck.GetServerVersion(cmd.Context(), publicClient)
+			if err != nil {
+				return err
+			}
+
+			if serverVersion != clientVersion {
+				versionRegex, err := regexp.Compile("stable-2.[8-9].*")
```
Comment (adleong) [inline cli/cmd/repair.go:63]: Consider using MustCompile and putting this regex in a global rather than a local.

File: cli/cmd/repair.go [hunk 4]
```diff
@@ -43,6 +47,31 @@ linkerd upgrade.`,
...
+			publicClient, err := public.NewExternalClient(cmd.Context(), controlPlaneNamespace, k8sAPI)
+			if err != nil {
+				return err
+			}
+			serverVersion, err = healthcheck.GetServerVersion(cmd.Context(), publicClient)
+			if err != nil {
+				return err
+			}
+
+			if serverVersion != clientVersion {
```
Comment (adleong) [inline cli/cmd/repair.go:62]: This is probably too strict, right?  There should be no incompatibility between 2.9.3 and 2.9.3, for example.  Or between most close edge versions.

Comment (Pothulapati) [reply cli/cmd/repair.go:62]: Yeah, It is strict. My thinking is that its impossible to know when we change config even btw edges and hence this way of doing it gets the correct new config always.

Any ideas on how to be a bit more relaxed without having to sacrifice correctness?

Comment (adleong) [reply cli/cmd/repair.go:66]: Can we find the specific edge and stable versions where the breakage occurred?

Comment (Pothulapati) [reply cli/cmd/repair.go:66]: I don't think there is a direct way where we track what changes between versions in Values.yaml. 

We can see if the conversions actually error and fall back based on that but that would mean that we are compromising correctness i.e where some values got replaced but no error.

File: cli/cmd/repair.go [hunk 5]
```diff
@@ -43,6 +51,27 @@ linkerd upgrade.`,
...
+			// Check if the CLI version matches with that of the server
+			clientVersion := version.Version
+			var serverVersion string
+			publicClient, err := public.NewExternalClient(cmd.Context(), controlPlaneNamespace, k8sAPI)
+			if err != nil {
+				return err
+			}
+			serverVersion, err = healthcheck.GetServerVersion(cmd.Context(), publicClient)
+			if err != nil {
+				return err
```
Comment (alpeb) [inline cli/cmd/repair.go:63]: Given these are not errors related to the commands flags, can you echo the error and do `os.Exit(1)` like we started doing with the other CLI commands? (and while you're at it do the same for the other returns above and below :wink: )

File: cli/cmd/repair.go [hunk 6]
```diff
@@ -43,6 +51,27 @@ linkerd upgrade.`,
...
+			}
+
+			if serverVersion != clientVersion {
+				helperVersion := serverVersion
+				// Use 2.9.4 CLI version for all 2.9 versions
+				if versionRegex.Match([]byte(serverVersion)) {
+					helperVersion = "stable-2.9.4"
+				}
+				return fmt.Errorf("Please run the repair command with a CLI that has the same version as the control plane.\nRun `LINKERD2_VERSION=\"%s\"; curl -sL https://run.linkerd.io/install | sh` to install the server version of the CLI", helperVersion)
```
Comment (alpeb) [inline cli/cmd/repair.go:72]: TIOLI: May I suggest doing instead `curl -sL https://run.linkerd.io/install | LINKERD2_VERSION=\"%s\" sh` to avoid leaking that env var into the current environment?

Comment (alpeb) [reply cli/cmd/repair.go:72]: OTOH, if `helperVersion` falls back to `stable-2.9.4` with say a server at `stable-2.8.1`, the message will be confusing ("has the same version"...)

File: cli/cmd/repair.go [hunk 7]
```diff
@@ -3,17 +3,25 @@ package cmd
...
+	"github.com/linkerd/linkerd2/pkg/healthcheck"
 	"github.com/linkerd/linkerd2/pkg/k8s"
+	"github.com/linkerd/linkerd2/pkg/version"
 	"github.com/spf13/cobra"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"sigs.k8s.io/yaml"
 )
 
+var (
+	versionRegex = regexp.MustCompile("stable-2.[8-9].*")
```
Comment (alpeb) [inline cli/cmd/repair.go:22]: Why considering `stable-2.8.*`? I think this should only apply to `stable-2.9.*`.

Comment (Pothulapati) [reply cli/cmd/repair.go:22]: Because there is no repair cmd in `2.8` and if the cmd suggests then prob they might except that sub cmd to exist. WDYT?

File: cli/cmd/repair.go (hunk 5 above)
Comment (Pothulapati) [reply cli/cmd/repair.go]: Updated and made it simpler by moving it into a separate function instead

File: cli/cmd/repair.go (hunk 7 above)
Comment (Pothulapati) [reply cli/cmd/repair.go]: Okay, That makes sense. Updated to fail and suggest upgrading for versions below `2.9`

**Comment by Pothulapati** [comment]
Okay, Did more research on the repair cmd and usage.

- Obv, `repair` is always executed from a CLI with version `2.9.4` & above, as that's when the cmd was added.
- It's hard to track changes in `Values` struct btw versions. My suggestion would be to be strict at default, but still provide `--force` if users want to go ahead and do it without matching CLI and Server Versions. (This is present in the PR already).

Now, Let's see what the suggestion should be.

- As repair is available from `2.9.4` and above in the CLI, For every server version matching from `2.9.4` & above, We could suggest the users to just use the matching CLI except for `2.9.(0-3) where we suggest `2.9.4` exclusively.
- For versions below `2.9`, We would instead suggest users to upgrade to `2.9.4` directly as there would be no lose of the config in that case.

**Review by adleong — COMMENTED** [review]
I experimented with the following diff, which fixes the panic:

```
diff --git a/cli/cmd/repair.go b/cli/cmd/repair.go
index f6b13751..5c7b5b15 100644
--- a/cli/cmd/repair.go
+++ b/cli/cmd/repair.go
@@ -8,6 +8,7 @@ import (
        "github.com/golang/protobuf/ptypes"
        pb "github.com/linkerd/linkerd2/controller/gen/config"
        "github.com/linkerd/linkerd2/pkg/charts/linkerd2"
+       pkgConfig "github.com/linkerd/linkerd2/pkg/config"
        "github.com/linkerd/linkerd2/pkg/k8s"
        "github.com/spf13/cobra"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
@@ -51,10 +52,16 @@ linkerd upgrade.`,

                        values := linkerd2.Values{}

-                       valuesRaw, ok := config.Data["values"]
+                       valuesStr, ok := config.Data["values"]
                        if !ok {
                                return errors.New("values not found in linkerd-config")
                        }
+                       valuesRaw := []byte(valuesStr)
+
+                       valuesRaw, err = pkgConfig.RemoveGlobalFieldIfPresent(valuesRaw)
+                       if err != nil {
+                               return fmt.Errorf("Failed to process values from linkerd-config: %s", err)
+                       }

                        err = yaml.Unmarshal([]byte(valuesRaw), &values)
                        if err != nil {
```

However, even though this diff successfully fixes the panic, my testing revealed that running a 2.10 repair on a 2.9 install has other problems.  Namely, because certain fields in the Values struct had moved, the repair command was now incorrectly identifying those fields as having been overridden and including them in the overrides.

So, finally, I agree with you that it really only makes sense to run `repair` with the same version that is running on the server.  This is awkward, but it's a consequence of how repair works and the fact that we don't have any versioning for the Values struct.

File: cli/cmd/repair.go [hunk 8]
```diff
@@ -32,80 +49,121 @@ linkerd upgrade.`,
...
+	if err != nil {
+		return fmt.Errorf("Failed to render overrides: %s", err)
+	}
+
+	fmt.Print(string(overrides))
+
+	return nil
 }
 
 // resetVersion sets all linkerd version fields to the chart's default version
```
[the remark this answers is not in the document]
Comment (Pothulapati) [reply cli/cmd/repair.go:169]: > setting them to a new empty struct if they do not already exist.

Setting them to a empty struct just sets all the sub fields to be nil values, which does not seem to help in any way. Instead, I gated the assignments. WDYT?

File: cli/cmd/repair.go [hunk 9]
```diff
@@ -119,8 +177,25 @@ func resetVersion(values *linkerd2.Values) error {
...
+			values.Proxy.Image.Version = defaults.Proxy.Image.Version
+		}
+	}
+
+	if values.ProxyInit != nil {
+		if values.ProxyInit.Image != nil {
+			values.ProxyInit.Image.Version = defaults.ProxyInit.Image.Version
+		}
+	}
+
```
Comment (alpeb) [inline cli/cmd/repair.go:198]: All these nested `if`s can be un-nested, right?

File: cli/cmd/repair.go [hunk 10]
```diff
@@ -32,80 +49,121 @@ linkerd upgrade.`,
...
+		return errors.New("values not found in linkerd-config")
 	}
 
-	return cmd
+	err = yaml.Unmarshal([]byte(valuesRaw), &values)
+	if err != nil {
+		return fmt.Errorf("Failed to load values from linkerd-config: %s", err)
+	}
+
+	// Reset version fields
```
Comment (alpeb) [inline cli/cmd/repair.go:126]: No need to add a comment when the function name is explicit enough :wink:

File: cli/cmd/repair.go (hunk 6 above)
Comment (alpeb) [reply cli/cmd/repair.go]: The command I suggested works for me in Linux, but might not in other systems. If so, I think it's fine to leave it as you initially had it, and not complicating things by unsetting the var at the end.

**Review by alpeb — COMMENTED** [review]
I'm not sure the code reflects the logic you posted above...

- If version <= ` 2.8.1` then you instruct to upgrade. That's fine.
- If version >= `2.9.0`  then you instruct to install the `2.9.4` CLI, which doesn't match your following statement:
> As repair is available from 2.9.4 and above in the CLI, For every server version matching from 2.9.4 & above, We could suggest the users to just use the matching CLI except for 2.9.(0-3) where we suggest 2.9.4` exclusively.

File: cli/cmd/repair.go (hunk 10 above)
Comment (Pothulapati) [reply cli/cmd/repair.go:126]: This was already there 😁

**Comment by Pothulapati** [comment]
@alpeb Yep, Sorry Missed that. Updated now 

- If version <= ` 2.)0-8).*` then you instruct to upgrade. 
- If version  is `2.9.(0-4)`  then you instruct to install the `2.9.4` CLI,
- else, use the same version, as the CLI

**Review by alpeb — APPROVED** [review]
Thanks @Pothulapati , this LGTM :+1:

**Review by adleong — APPROVED** [review]
