### PR TITLE
Fix CNI config parsing

### LINKED ISSUE #3941: CNI binary cannot parse its config
The CNI  binary fails to parse its config with the following error: 

```
Events:
  Type     Reason                  Age   From                         Message
  ----     ------                  ----  ----                         -------
  Normal   Scheduled               23s   default-scheduler            Successfully assigned linkerd/linkerd-identity-f5489f6c6-xng67 to kind-control-plane
  Warning  FailedCreatePodSandBox  22s   kubelet, kind-control-plane  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "14b5f0fe54676b0dbdc1b947cee2c2548fc0339dc11b0aaea976a50
7c9265534": linkerd-cni: failed to parse network configuration: json: cannot unmarshal number into Go struct field ProxyInit.linkerd.inbound-ports-to-ignore of type string
  Warning  FailedCreatePodSandBox  8s    kubelet, kind-control-plane  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ac4bf990578a0cefef6256bd9ce56e9095e1be645be94d1e07d000a
789e1e7e6": linkerd-cni: failed to parse network configuration: json: cannot unmarshal number into Go struct field ProxyInit.linkerd.inbound-ports-to-ignore of type string
```

This was likely introduced in #3766. Apart from fixing that, it would be great if a test is added.

### PR DESCRIPTION
**Pull request by zaharidichev**
This PR addreses the problem introduced after #3766. It also uses an unreleased dependency of linkerd-proxy-init, so it is blocked on a new release of https://github.com/linkerd/linkerd2-proxy-init. So do not merge until then, please :) 

Fixes #3941

### CODE REVIEW

File: cli/cmd/install-cni-plugin.go [hunk 1]
```diff
@@ -140,11 +147,11 @@ func (options *cniPluginOptions) buildValues() (*cnicharts.Values, error) {
 	}
 
 	for _, p := range options.ignoreInboundPorts {
-		ignoreInboundPorts = append(ignoreInboundPorts, fmt.Sprintf("%d", p))
+		ignoreInboundPorts = append(ignoreInboundPorts, "%s", p)
 	}
 	ignoreOutboundPorts := []string{}
 	for _, p := range options.ignoreOutboundPorts {
-		ignoreOutboundPorts = append(ignoreOutboundPorts, fmt.Sprintf("%d", p))
+		ignoreOutboundPorts = append(ignoreOutboundPorts, "%s", p)
```
Comment (alpeb) [inline cli/cmd/install-cni-plugin.go]: Are these changes intended?

Comment (zaharidichev) [reply cli/cmd/install-cni-plugin.go]: no not at all...

Comment (zaharidichev) [reply cli/cmd/install-cni-plugin.go]: at least not in this way

File: charts/linkerd2-cni/templates/cni-plugin.yaml [hunk 2]
```diff
@@ -143,8 +143,24 @@ data:
         "outgoing-proxy-port": {{.Values.outboundProxyPort}},
         "proxy-uid": {{.Values.proxyUID}},
         "ports-to-redirect": [{{.Values.portsToRedirect}}],
-        "inbound-ports-to-ignore": [{{.Values.ignoreInboundPorts}}],
-        "outbound-ports-to-ignore": [{{.Values.ignoreOutboundPorts}}],
+        "inbound-ports-to-ignore": [
```
[the remark this answers is not in the document]
Comment (zaharidichev) [reply charts/linkerd2-cni/templates/cni-plugin.yaml]: @adleong We are doing similar/same thing right here: https://github.com/linkerd/linkerd2/blob/master/charts/linkerd2/templates/_config.tpl#L33. And it had a problem that I attempted to fix in #3957

[the remark this answers is not in the document]
Comment (zaharidichev) [reply charts/linkerd2-cni/templates/cni-plugin.yaml]: @adleong I did refactor it and pulled the logic out so we can reuse it. We can reuse the same function in #3957 as well.

File: cli/cmd/install-cni-plugin.go [hunk 3]
```diff
@@ -139,13 +146,7 @@ func (options *cniPluginOptions) buildValues() (*cnicharts.Values, error) {
...
 	}
 
-	for _, p := range options.ignoreInboundPorts {
-		ignoreInboundPorts = append(ignoreInboundPorts, fmt.Sprintf("%d", p))
-	}
-	ignoreOutboundPorts := []string{}
-	for _, p := range options.ignoreOutboundPorts {
-		ignoreOutboundPorts = append(ignoreOutboundPorts, fmt.Sprintf("%d", p))
-	}
+	ignoreInboundPorts = append(ignoreInboundPorts, options.ignoreInboundPorts...)
```
Comment (alpeb) [inline cli/cmd/install-cni-plugin.go]: :tada:

File: charts/linkerd2-cni/templates/cni-plugin.yaml [hunk 4]
```diff
@@ -143,8 +143,12 @@ data:
...
+          {{- include "util.splitStringList" .Values.ignoreInboundPorts -}}
+        ],
+        "outbound-ports-to-ignore": [
+          {{- include "util.splitStringList" .Values.ignoreOutboundPorts -}}
+        ],
```
Comment (alpeb) [inline charts/linkerd2-cni/templates/cni-plugin.yaml]: These includes need to be updated, in light of the util->helper recent change

Comment (alpeb) [reply charts/linkerd2-cni/templates/cni-plugin.yaml]: Actually my problem was elsewhere... the requirements file name is misspelled, and it's missing the `dependencies:` line. Even so, it might be better to replace this `util` prefix with `partials`...

Comment (zaharidichev) [reply charts/linkerd2-cni/templates/cni-plugin.yaml]: Thanks! Also needed to `dep up` the cni chart in `helm-build` apparently otherwise it fails

**Comment by zaharidichev** [comment]
@adleong yes, it is
