### PR TITLE
Fix wrong `skipped` message of `linkerd inject` for a namespace

### LINKED ISSUE #10231: [cli] `linkerd inject` show "skipped" for a Namespace
### What is the issue?

Running `kubectl get ns <namespace> -o yaml | linkerd inject -` shows `namespace "<namespace>" skipped` on stderr. However, it does appear that the annotation gets applied and spit out as YAML as expected.

The linkerd [docs](https://linkerd.io/2.12/tasks/adding-your-service/#meshing-a-service-with-annotations) note that you can apply the `linkerd.io/inject: enabled` annotation to a `Namespace`. (Yes, I realize this could be done using `kubectl annotate`, but the `linkerd inject` route seems more stable and explicit.)

Is `linkerd inject` meant to be used on `Namespace` YAML, or only directly on Deployment/StatefulSet/Pod resources?

### How can it be reproduced?

```
kubectl get ns <namespace> -o yaml | linkerd inject -
```

### Logs, error output, etc

```
$ kubectl get ns airflow -o yaml | linkerd inject -

...

namespace "airflow" skipped
```

### output of `linkerd check -o short`

```
$ linkerd check -o short
Status check results are √
```

### Environment

- Amazon EKS 1.24

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

no

### PR DESCRIPTION
**Pull request by mikutas**
Fixes #10231

### CODE REVIEW

File: cli/cmd/inject.go [hunk 1]
```diff
@@ -166,32 +166,32 @@ func (rt resourceTransformerInject) transform(bytes []byte) ([]byte, []inject.Re
...
 	if rt.allowNsInject && conf.IsNamespace() {
 		bytes, err = conf.AnnotateNamespace(rt.overrideAnnotations)
 		report.Annotated = true
-		return bytes, reports, err
+		return bytes, []inject.Report{*report}, err
 	}
 	if conf.HasPodTemplate() {
-		conf.AppendPodAnnotations(rt.overrideAnnotations)
-		report.Annotated = true
+		if len(rt.overrideAnnotations) > 0 {
```
Comment (alpeb) [inline cli/cmd/inject.go:184]: This can be collapsed into a single `if` statement

**Review by alpeb — COMMENTED** [review]
Great fix! Just one tiny nit below.

**Review by alpeb — APPROVED** [review]

**Review by mateiidavid — APPROVED** [review]
