### PR TITLE
Ignore pods with status.phase=Succeeded when watching IP addresses

### LINKED ISSUE #5394: Traffic stops when two pods have the same IP address
### What is the issue?

Traffic to a pod stops when the pod has the same IP address as another pod with state `Completed`.

When I take a look at `target.addr":"100.96.43.254:8080` from the logs and do `kubectl get po -A -owide | grep 100.96.43.254` I get the two pods with the same IP address:

```
default         h-cortex-injixo-6c4f975874-n47fb                                      3/3     Running     0          40m     100.96.43.254    ip-172-21-2-50.eu-west-1.compute.internal    <none>           <none>
default         h-custom-integrations-interflex-month-balances-1608003600-42242       0/1     Completed   0          31h     100.96.43.254    ip-172-21-2-50.eu-west-1.compute.internal    <none>           <none>
```
See: https://github.com/kubernetes/kubernetes/issues/92697

When I delete one of the pods the problem is gone. This problem has occurred at least 3 times in the last 24hrs.

### Logs, error output, etc

```
fastly-ingress-7cb9d8f8d4-wtxb4:linkerd-proxy {"timestamp":"[   384.647220s]","level":"INFO","fields":{"message":"Connection closed","error":"Service in fail-fast"},"target":"linkerd2_app_core::serve","span":{"peer.addr":"100.96.0.146:49428","target.addr":"100.96.43.254:8080","name":"accept"},"spans":[{"name":"outbound"},{"peer.addr":"100.96.0.146:49428","target.addr":"100.96.43.254:8080","name":"accept"}],"threadId":"ThreadId(1)"}
fastly-ingress-7cb9d8f8d4-xp7w2:linkerd-proxy {"timestamp":"[   219.444015s]","level":"WARN","fields":{"message":"Could not fetch profile","error":"status: Unknown, message: \"http2 error: protocol error: unexpected internal error encountered\", details: [], metadata: MetadataMap { headers: {} }"},"target":"linkerd2_service_profiles::client","span":{"name":"outbound"},"spans":[{"name":"outbound"}],"threadId":"ThreadId(1)"}
fastly-ingress-7cb9d8f8d4-xp7w2:linkerd-proxy {"timestamp":"[   219.448108s]","level":"WARN","fields":{"message":"Could not fetch profile","error":"status: Unknown, message: \"http2 error: protocol error: unexpected internal error encountered\", details: [], metadata: MetadataMap { headers: {} }"},"target":"linkerd2_service_profiles::client","span":{"name":"outbound"},"spans":[{"name":"outbound"}],"threadId":"ThreadId(1)"}
... 
The WARN log line is repeated about 300 times
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system
√ multiple replicas of control plane pods

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √

```

### Environment

- Kubernetes Version: v1.18.13
- Cluster Environment: kops on AWS
- Host OS: Ubuntu 20.04 LTS
- Linkerd version: Client version: stable-2.9.1, Server version: stable-2.9.1

### PR DESCRIPTION
**Pull request by fpetkovski**
Ignore pods with status.phase=Succeeded when watching IP addresses

When a pod terminates successfully, some CNIs will assign its IP address
to newly created pods. This can lead to duplicate pod IPs in the same
Kubernetes cluster.

Filter out pods which are in a Succeeded phase since they are not 
routable anymore.

Fixes #5394

### CODE REVIEW

File: controller/api/destination/watcher/ip_watcher.go [hunk 1]
```diff
@@ -285,10 +303,18 @@ func (iw *IPWatcher) getOrNewServiceSubscriptions(clusterIP string) *serviceSubs
 			pods := []*corev1.Pod{}
 			for _, obj := range objs {
 				if pod, ok := obj.(*corev1.Pod); ok {
-					// Skip pods with HostNetwork.
-					if !pod.Spec.HostNetwork {
-						pods = append(pods, pod)
+					// Skip pods with HostNetwork
+					if pod.Spec.HostNetwork {
```
Comment (fpetkovski) [inline controller/api/destination/watcher/ip_watcher.go:307]: Not 100% sure if this change is need. Looking forward to any feedback

File: controller/api/destination/watcher/ip_watcher.go [hunk 2]
```diff
@@ -285,10 +303,18 @@ func (iw *IPWatcher) getOrNewServiceSubscriptions(clusterIP string) *serviceSubs
...
+						continue
 					}
+
+					// Ignore terminated pods,
+					// their IPs can be reused for new Running pods
+					if podTerminated(pod) {
```
Comment (fpetkovski) [inline controller/api/destination/watcher/ip_watcher.go:313]: Not 100% sure if this change is need. Looking forward to any feedback

Comment (adleong) [reply controller/api/destination/watcher/ip_watcher.go:313]: I think we want to omit terminated pods any time we are using the pod ip index.  So yes, I think this makes sense.

**Comment by adleong** [comment]
This looks great to me.   @kforsthoevel are you able to test this branch and confirm if it fixes #5394 for you?

**Comment by kforsthoevel** [comment]
Thanks. We will try it out after the holidays.

**Comment by thomaspeitz** [comment]
@adleong - Is there any chance that you improve your build process by pushing the branch images? - Or are they already pushed and I do not see them. - The ones used during building seem to be tagged correctly but not pushed.

That would help us a lot to test it. Else we would build / push those images ourselves.

Greetings :)

**Comment by kleimkuhler** [comment]
@thomaspeitz It's not exactly what you're asking for, but we do have something like this available if you clone the repo.

There is a script `bin/install-pr` that will install the images uploaded during the CI process and load them into a local cluster. We use this for testing PRs which sounds like what you're trying to do here.

For this PR, I can test in a k3d cluster with the following:

```
❯ env GITHUB_TOKEN='..' bin/install-pr --k3d 5412
..
INFO[0004] DONE                                         
/home/kevin/Projects/linkerd/linkerd2

Linkerd CLI available:
/home/kevin/Projects/linkerd/linkerd2/target/release/linkerd2-cli-git-65f0d802-linux-amd64
```

Then you can install it and test:

```
./target/release/linkerd2-cli-git-65f0d802-linux-amd64 install |kubectl apply -f -
```

The value of `GITHUB_TOKEN` is your GitHub personal access token. If you don't pass `--k3d` or `--kind`, it assumes a regular k8s cluster.

**Comment by thomaspeitz** [comment]
Thanks for your input!

We will continue tomorrow and give you feedback as soon as possible.

**Comment by thomaspeitz** [comment]
We upgraded to newest edge version, replaced the destination container with the updated controller image and now monitor closely logs in case any problem happen. We get back to you beginning next week with test results (or earlier in cases of problems). Thanks for your work! :)

**Comment by kforsthoevel** [comment]
@adleong, @fpetkovski The patch is running for almost a week now and we haven't see the error anymore. It seems to have fixed the issue. 

Thank you for the quick fix.

**Review by kleimkuhler — APPROVED** [review]
Looks great, thanks @fpetkovski

**Review by adleong — APPROVED** [review]
Awesome!  Thanks @kforsthoevel for confirming!

**Comment by kivagant-ba** [comment]
What version includes the fix?

**Comment by kleimkuhler** [comment]
This only recently merged so it is not part of a release yet. We do edge releases at the end of each week, so `edge-20.1.2` will include it, and that should be available by Thursday or Friday.

**Comment by kivagant-ba** [comment]
Another question: can the fix be included as a hotfix into last couple of stable versions without having everyone to upgrade to a release with all of the new functionality? It is a quite critical bug that causes issues when pods cannot even start because liveness probes cannot pass. Or hidden issues when traffic cannot be balanced properly (I guess this is what is happening when we see the WARNs in logs).

**Comment by kleimkuhler** [comment]
@kivagant-ba Sure, we'll release a `stable-2.9.2` with this fix. I'll leave a comment here when it has been released; I'm going to start prepping it today.

**Comment by kleimkuhler** [comment]
`stable-2.9.2` has been released with this fix.

**Comment by kivagant-ba** [comment]
Thank you, @kleimkuhler !
