### PR TITLE
Fix Docker runtime check to happen only during install

### LINKED ISSUE #8583: Ability to run pre-checks with with docker container runtime
### What problem are you trying to solve?

It seems like there is no way to run pre-checks when using docker container runtime. One, can only check post installation as shown [here](https://linkerd.io/2.11/tasks/troubleshooting/#l5d-proxy-init-run-as-root).

```bash
➜  ~ linkerd check --pre
there are nodes using the docker container runtime and proxy-init container must run as root user.
try installing linkerd via --set proxyInit.runAsRoot=true
```

### How should the problem be solved?

Maybe introduce an optional flag to check runtime

```bash
➜  ~ linkerd check --pre --runtime docker
```

### Any alternatives you've considered?

No

### How would users interact with this feature?

```bash
➜  ~ linkerd check --pre --runtime docker
```

### Would you like to work on this feature?

maybe

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #8583 

Even though #7468 removed the Docker container runtime check from `linkerd check --pre` to `linkerd install` runtime error, we still do a dry run of the installation so that we can render the control plane manifests. Therefore, we still hit this check which results in not being able to run `linkerd check --pre` when nodes are using the Docker container runtime. This fixes the issue by introducing a `dryRun` flag that we check beforehand.

```shell
❯ kubectl get nodes docker-desktop -o jsonpath='{.status.nodeInfo.containerRuntimeVersion}'
docker://20.10.16

❯ bin/linkerd check --pre
Linkerd core checks
===================
...
```

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
It's pretty hard to keep track of all the things that the `installControlPlane` function does, because it does sort of an unexpected combination of things, and I think it gets even more confusing with a boolean to conditionally modify this behavior.

It looks like `installControlPlane` mainly does 3 things:
* creates the valuesOverrides from the Helm-style `--set` flags
* does various validations (including the docker runtime validation)
* renders the manifests (by calling `renderControlPlane`)

For this step of `check --pre` specifically, we only want the rendered manifests so that we can extract information from them, we don't actually want to do the various validations at that point (certain other validations are already performed as part of other pre-checks).  Can we move the creation of `valuesOverrides` out so that the code in the `check --pre` codepath can just call `renderControlPlane` directly and skip all of these unwanted validations?

**Comment by kleimkuhler** [comment]
Ok it just calls `renderControlPlane` now. This also changes where we error out with `linkerd check --pre`, but I think it's in a good way.

Currently, if Linkerd is installed we see

```shell
$ linkerd check --pre
Can't install the Linkerd control plane in the 'linkerd' namespace. Reason: ConfigMap/linkerd-config already exists.
Run the command `linkerd upgrade`, if you are looking to upgrade Linkerd.
```

Now, we still run the full checks, but still see similar feedback

```shell
$ bin/linkerd check --pre
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

pre-kubernetes-setup
--------------------
× control plane namespace does not already exist
    The "linkerd" namespace already exists
    see https://linkerd.io/2/checks/#pre-ns for hints
× can create non-namespaced resources
    ...
√ can create ServiceAccounts
...

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    unsupported version channel: dev-f89cfae7-kevin
    see https://linkerd.io/2/checks/#l5d-version-cli for hints

Status check results are ×
```

To revert this behavior — and just print the `linkerd-config` error — I can add back the `checkNoConfig` that happens before `renderControlPlane`.

File: cli/cmd/check.go [hunk 1]
```diff
@@ -268,20 +266,25 @@ func getExtensionCheckFlags(lf *pflag.FlagSet) []string {
 }
 
 func renderInstallManifest(ctx context.Context) (*charts.Values, string, error) {
+	// Create the default values.
```
Comment (adleong) [inline cli/cmd/check.go:269]: the placement of this comment is a bit misleading since the API isn't used in the creation of the default values.

**Review by adleong — APPROVED** [review]

**Review by mateiidavid — APPROVED** [review]
