### PR TITLE
viz: fix uninstall for legacy linkerd-viz (#6213)

### LINKED ISSUE #6213: Linkerd viz uninstall doesn't handle legacy extension name (`linkerd-viz`)
### What is the issue?

Prior to 15d1809bd043192bb21cacbc96112cce35bf384f, linkerd viz resources were named `linkerd-viz`:
https://github.com/linkerd/linkerd2/blob/1e5722104e3b9dcf59d7c136cb090c270de02c79/viz/cmd/root.go#L13-L14

With that change, the `linkerd viz uninstall` feature looks for resources called `viz` , and will pretend that there's nothing else to be removed:

https://github.com/linkerd/linkerd2/blob/7af97e68f8f9c3dad791bcc1df6e9c165e537995/viz/cmd/root.go#L14-L15
https://github.com/linkerd/linkerd2/blob/7af97e68f8f9c3dad791bcc1df6e9c165e537995/viz/cmd/uninstall.go#L41

Unfortunately, `linkerd uninstall` looks for things differently, so the two sides disagree about the state of the world, leading to confusion and frustration.

### How can it be reproduced?

Set up a linkerd + viz install using a binary from before 15d1809bd043192bb21cacbc96112cce35bf384f

### Logs, error output, etc

See https://github.com/linkerd/linkerd2/issues/5994#issuecomment-852436253 and https://github.com/linkerd/linkerd2/issues/5994#issuecomment-852452212

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-06-03T17:54:46Z
    see https://linkerd.io/2.10/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2021-06-03T18:39:11Z
    see https://linkerd.io/2.10/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
√ sp-validator webhook has valid cert
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2021-06-03T18:39:06Z
    see https://linkerd.io/2.10/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 21.1.1 but the latest edge version is 21.5.3
    see https://linkerd.io/2.10/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running edge-21.1.1 but cli running stable-2.10.2
    see https://linkerd.io/2.10/checks/#l5d-version-control for hints

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √

Linkerd extensions checks
=========================

linkerd-linkerd-viz
-------------------
‼ Linkerd extension command linkerd-linkerd-viz exists
    exec: "linkerd-linkerd-viz": executable file not found in $PATH
    see https://linkerd.io/2.10/checks/#extensions for hints

Status check results are √
```

### Environment

- Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1400", GitCommit:"ec68c7064ea987ad0c7fb63930df96bdefeb93c4", GitTreeState:"clean", BuildDate:"2021-04-07T09:20:04Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
- Cluster Environment: GKE
- Host OS: macOS
- Linkerd version:
```
Client version: stable-2.10.2
Server version: edge-21.1.1
```

### Possible solution

I'm going to provide a PR

### Additional context

https://linkerd.slack.com/archives/C89RTCWJF/p1622580594353800?thread_ts=1622579764.353700&cid=C89RTCWJF

### PR DESCRIPTION
**Pull request by jsoref**
Prior to 15d1809bd043192bb21cacbc96112cce35bf384f, the name for viz objects was
`linkerd-viz` and people may still want to uninstall them using the current version of linkerd.

To support this, an additional code path is included when the fast path fails to
suggest things to remove.

Tested with my broken cluster.

Fixes #6213

Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>

### CODE REVIEW

File: viz/cmd/uninstall.go [hunk 1]
```diff
@@ -38,5 +38,10 @@ func uninstallRunE(ctx context.Context) error {
 		return err
 	}
 
-	return pkgCmd.Uninstall(ctx, k8sAPI, fmt.Sprintf("%s=%s", k8s.LinkerdExtensionLabel, ExtensionName))
+	err = pkgCmd.Uninstall(ctx, k8sAPI, fmt.Sprintf("%s=%s", k8s.LinkerdExtensionLabel, ExtensionName))
+	if err == nil {
+		return nil
+	}
```
Comment (mateiidavid) [inline viz/cmd/uninstall.go:44]: I'm not quite sure this would work well, given that the `Uninstall()` command has more than one point of failure. An uninstall in this case may fail if the resources are not found, the clientset cannot be initialised properly or the resources cannot be rendered. 

In case of an error, by this logic we will re-attempt the uninstall but with the legacy label instead of the current one. I think we should either handle the error returned by `Uninstall` a bit more gracefully here; this would help us avoid any confusion down the line and adhere a bit more to Go's failure handling standards. 

Dealing with the error gracefully here can be a bit tedious (since we don't have different error types) so instead here is what I would do:

```suggestion
        extensionReq, err := labels.NewRequirement(k8s.LinkerdExtensionLabel, selection.In, []string{ExtensionName, LegacyExtensionName})
        if err != nil {
                return err
        }

        selector := labels.NewSelector().Add(*extensionReq)
        return pkgCmd.Uninstall(ctx, k8sAPI, selector.String())

```

We can make a bit more use of the selector provided by client-go (` "k8s.io/apimachinery/pkg/labels"`) and check that our key (`linkerd.io/extension` in this case) is in ['viz', 'linkerd-viz']. We can then turn the selector into a string and pass it to `Uninstall`.

An alternative way of doing this would be to build a label selector with the two values, turn it into a map and then finally into a string. Client-go again offers a few functions to make the conversion easier but this just seems a bit too complicated imo.

Let me know what you think.

**Review by mateiidavid — COMMENTED** [review]
Hey @jsoref thanks for raising the issue and offering to fix this!

This looks good to me but I would do it a bit differently; I shared my thoughts in the comment below.

File: viz/cmd/uninstall.go (hunk 1 above)
Comment (jsoref) [reply viz/cmd/uninstall.go:44]: My change certainly didn't feel great, especially since it was an all errors case, and I didn't have a great sense of how to distinguish.

I will take anything that works. I'm not remotely picky.

Please pretend that I don't really speak golang or k8s, which is a sufficiently good approximation.



(I think one test may have failed which was a good indication that my quick hack wasn't great.)

In GitHub, the indentation of your changes looks off, not sure why.

**Review by kleimkuhler — APPROVED** [review]
This looks good to me! Thanks for working through this @jsoref really appreciate it.

**Review by mateiidavid — APPROVED** [review]
Thank you!
