### PR TITLE
Use a shared informer when getting node topology

### LINKED ISSUE #5684: Linkerd 2.9 destination component high latency and node topology request failures
### What is the issue?
After upgrading to Linkerd 2.9.2 from 2.7.1 we started seeing random cross deployment communication problems in our  EKS production cluster during peak hours. There are no known issues with services availability, all pods are running. Disabling linkerd proxy injection from a deployment helps to fix the issue. Looking into linkerd-proxy logs we see that many connections are in "fail-fast" mode. After analysing Linkerd Grafana Health dashboard we found that linkerd-destination P95 latency is very high during these times - taking several seconds and often up to 5 seconds. Looking into linkerd-destination logs we see that there are many errors like "Failed to get node topology for node ..." and errors time period match perfectly with incident times.
We have quickly checked the code and it looks like that recent "Topology-Aware Service Routing" feature has introduced increased dependency on Kubernetes API server and in the case of API performance or availability issues it might have an impact on inter-pod communication.
After downgrading Linkerd back to 2.7.1 described problems are gone.

### How can it be reproduced?
Make linkerd-destination node topology requests to Kubernetes API server fail.

### Logs, error output, etc

linkerd-proxy logs:
```
2021-02-02 19:48:19 | [ 252.710896s] WARN ThreadId(01) outbound:accept{peer.addr=10.178.14.208:36092 target.addr=172.20.160.126:33011}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
2021-02-02 19:48:19 | [ 239.922485s] WARN ThreadId(01) outbound:accept{peer.addr=10.178.15.59:53530 target.addr=172.20.81.231:8080}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
2021-02-02 19:48:19 | [ 239.901097s] WARN ThreadId(01) dst: linkerd2_reconnect::service: Service failed error=channel closed
2021-02-02 19:48:18 | [ 251.676478s] WARN ThreadId(01) outbound:accept{peer.addr=10.178.14.208:34412 target.addr=172.20.81.231:8080}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
2021-02-02 19:48:17 | [ 236.835768s] WARN ThreadId(01) outbound:accept{peer.addr=10.178.10.116:35232 target.addr=172.20.160.126:33011}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
2021-02-02 19:48:17 | [ 236.824725s] WARN ThreadId(01) outbound:accept{peer.addr=10.178.10.116:35228 target.addr=172.20.160.126:33011}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
```

linkerd-destination logs
```
2021-02-02 19:48:18 | time="2021-02-02T19:48:18Z" level=error msg="Failed to send address update: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" addr=":8086" component=endpoint-translator remote="127.0.0.1:35458" service="billingservce.default.svc.cluster.local:80"
2021-02-02 19:48:18 | time="2021-02-02T19:48:18Z" level=error msg="Failed to get node topology for node ip-10-178-13-170.eu-west-1.compute.internal: context canceled" addr=":8086" component=endpoint-translator remote="127.0.0.1:35458" service="billlingservice.default.svc.cluster.local:80"
2021-02-02 19:48:17 | time="2021-02-02T19:48:17Z" level=error msg="Failed to send address update: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" addr=":8086" component=endpoint-translator remote="127.0.0.1:35458" service="orderservice.default.svc.cluster.local:8080"
2021-02-02 19:48:17 | time="2021-02-02T19:48:17Z" level=error msg="Failed to get node topology for node ip-10-178-15-76.eu-west-1.compute.internal: context canceled" addr=":8086" component=endpoint-translator remote="127.0.0.1:35458" service="orderservice.default.svc.cluster.local:8080"
2021-02-02 19:48:17 | time="2021-02-02T19:48:17Z" level=error msg="Failed to send address update: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" addr=":8086" component=endpoint-translator remote="127.0.0.1:35458" service="billingservice.default.svc.cluster.local:80"
2021-02-02 19:48:17 | time="2021-02-02T19:48:17Z" level=error msg="Failed to get node topology for node ip-10-178-15-254.eu-west-1.compute.internal: context canceled" addr=":8086" component=endpoint-translator remote="127.0.0.1:35458" service="billingservice.default.svc.cluster.local:80"
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: EKS
- Host OS: Amazon Linux 2
- Linkerd version: 2.9.2

### PR DESCRIPTION
**Pull request by fpetkovski**
Getting information about node topology queries the k8s api directly.
In an environment with high traffic and high number of pods, the
k8s api server can become overwhelmed or start throttling requests.

This MR introduces a node informer to resolve the bottleneck and
fetch node information asynchronously.

Fixes #5684

### CODE REVIEW

**Comment by mateiidavid** [comment]
Hey @fpetkovski thank you for taking care of this! 🥳 I really appreciate it. 

This looks good to me. It is pretty much the way I would have done it, save for different (and possibly less inspired) names.

File: controller/api/destination/server.go [hunk 1]
```diff
@@ -7,6 +7,8 @@ import (
 	"strconv"
 	"strings"
 
+	coreinformers "k8s.io/client-go/informers/core/v1"
+
```
Comment (kleimkuhler) [inline controller/api/destination/server.go:11]: nit: Can you remove the newline below this so it gets group with the other imports?

File: controller/cmd/destination/main.go [hunk 2]
```diff
@@ -84,14 +84,14 @@ func Main(args []string) {
...
-			k8s.Endpoint, k8s.ES, k8s.Pod, k8s.RS, k8s.Svc, k8s.SP, k8s.TS, k8s.Job, k8s.NS,
+			k8s.Endpoint, k8s.ES, k8s.Pod, k8s.RS, k8s.Svc, k8s.SP, k8s.TS, k8s.Job, k8s.NS, k8s.Node,
 		)
 	} else {
 		k8sAPI, err = k8s.InitializeAPI(
 			ctx,
 			*kubeConfigPath,
 			true,
-			k8s.Endpoint, k8s.Pod, k8s.RS, k8s.Svc, k8s.SP, k8s.TS, k8s.Job, k8s.NS,
+			k8s.Endpoint, k8s.Pod, k8s.RS, k8s.Svc, k8s.SP, k8s.TS, k8s.Job, k8s.NS, k8s.Node,
```
Comment (kleimkuhler) [inline controller/cmd/destination/main.go:94]: 👍

**Review by kleimkuhler — APPROVED** [review]
This looks good! It makes sense that this address the bottleneck we're seeing in that issue.

File: controller/api/destination/server.go (hunk 1 above)
Comment (fpetkovski) [reply controller/api/destination/server.go]: Sure thing, removed the new line and resorted the imports to make the lint pass.

**Review by adleong — APPROVED** [review]
Fantastic!!! Thank you, @fpetkovski! 💯

**Comment by christianhuening** [comment]
@adleong much appreciated to see this solved! We just discovered that we ran into the same issue. Sadly, we currently cannot update to L5d 2.10.x as far as I understand it, since we're still using K8s 1.15 and `2.10.0` requires K8s 1.16. Is there a possibility to backport this fix to `2.9.4` ?
