### PR TITLE
Don't patch httproute status if it hasn't changed

### LINKED ISSUE #12104: Policy Controller Memory Leak
### What is the issue?

We recently upgraded Linkerd in our staging environment from `2.12.4` (Helm chart version `1.9.6`) to `2.14.8` (Helm chart version `1.16.9`).  After this upgrade, we noticed some cluster instability; upon investigating, it turns out that the policy container in just one of our five destination pod replicas was leaking memory at a constant rate of around 25 MB per minute.  We have since updated to the latest patch version (`2.14.9`/`1.16.10`) with the same result.

The primary issue here is the memory leak itself: you can see from the chart below that the memory usage on the policy container holding the policy-controller-write lease will grow until that pod is terminated for exceeding its memory limit.  (We're running a five-replica HA deployment.)  I've attached a small extract of trace logs from that container; it seems to be processing HttpRoute updates at very high volume - the logs are basically just this on repeat for different namespaces/services - but I don't know if that's the intended behavior.

The secondary issue is that in our deployment of Linkerd, the policy container was not defaulting back to the destination pod resource requests/limits as [this line](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/destination.yaml#L347) in the Helm template would imply - in fact it had no requests or limits applied, which meant it would eventually grow to 13GB+ and cause the node it was located on to fail.  We solved this issue in the short term by applying resources specifically to the policy controller via `policyController.resources` so it correctly kills just the one pod now, but if I'm understanding the templates correctly it never should have had the issue in the first place.

I did generally notice that after the upgrade, the baseline CPU and memory consumption of the policy containers (including non-leaseholders) is much higher - the CPU usage is at least 20x higher (although still small in the grand scheme of things, around 70ms for the leaseholder and 35ms for non-leaseholders) and the memory usage is around 5x higher (around 150 MB, up from 30MB before the update).  Skimming the release notes, it does look like the policy controller is doing a lot more these days than it used to, so again - that may be expected.

I will happily pull any resource definitions or additional logs from our staging cluster as required - just let me know what you'd like to see.

Thanks!

### How can it be reproduced?

Unclear; since this is unreported elsewhere it's likely an edge case we're just unlucky enough to have hit.

### Logs, error output, etc

```
2024-02-18T17:21:22.344432Z TRACE hyper::proto::h1::decode: decode; state=Chunked(Size, 0)
2024-02-18T17:21:22.344459Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.344500Z TRACE hyper::proto::h1::io: received 1640 bytes
2024-02-18T17:21:22.344505Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.344508Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.344510Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.344513Z TRACE hyper::proto::h1::decode: Chunk size is 1633
2024-02-18T17:21:22.344517Z DEBUG hyper::proto::h1::decode: incoming chunked header: 0x661 (1633 bytes)
2024-02-18T17:21:22.344521Z TRACE hyper::proto::h1::decode: Chunked read, remaining=1633
2024-02-18T17:21:22.344529Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Chunked(BodyCr, 0)), writing: KeepAlive, keep_alive: Busy }
2024-02-18T17:21:22.344555Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: attempting to decode a frame
2024-02-18T17:21:22.344673Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: frame decoded from buffer
2024-02-18T17:21:22.344858Z TRACE httproutes.policy.linkerd.io: kubert::index: event=Applied(HttpRoute { metadata: ObjectMeta { annotations: Some({"meta.helm.sh/release-name": "mfgx-customer1", "meta.helm.sh/release-namespace": "customer1"}), cluster_name: None, creation_timestamp: Some(Time(2024-01-16T17:02:10Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(1), labels: Some({"app.kubernetes.io/managed-by": "Helm"}), managed_fields: Some([ManagedFieldsEntry { api_version: Some("policy.linkerd.io/v1beta1"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:metadata": Object {"f:annotations": Object {".": Object {}, "f:meta.helm.sh/release-name": Object {}, "f:meta.helm.sh/release-namespace": Object {}}, "f:labels": Object {".": Object {}, "f:app.kubernetes.io/managed-by": Object {}}}, "f:spec": Object {".": Object {}, "f:parentRefs": Object {}, "f:rules": Object {}}})), manager: Some("helm"), operation: Some("Update"), time: Some(Time(2024-01-16T17:02:10Z)) }, ManagedFieldsEntry { api_version: Some("policy.linkerd.io/v1beta3"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:status": Object {".": Object {}, "f:parents": Object {}}})), manager: Some("policy.linkerd.io"), operation: Some("Update"), time: Some(Time(2024-02-18T17:21:22Z)) }]), name: Some("mfgx-backend-svc-orchestration-worker-primary-route"), namespace: Some("customer1"), owner_references: None, resource_version: Some("1495930533"), self_link: None, uid: Some("51097cb5-02ce-4a45-a73b-721661b4c637") }, spec: HttpRouteSpec { inner: CommonRouteSpec { parent_refs: Some([ParentReference { group: Some("policy.linkerd.io"), kind: Some("Server"), namespace: None, name: "mfgx-backend-svc-orchestration-worker-primary", section_name: None, port: None }]) }, hostnames: None, rules: Some([HttpRouteRule { matches: Some([HttpRouteMatch { path: Some(PathPrefix { value: "/" }), headers: None, query_params: None, method: None }]), filters: None, backend_refs: None, timeouts: None }]) }, status: Some(HttpRouteStatus { inner: RouteStatus { parents: [RouteParentStatus { parent_ref: ParentReference { group: Some("policy.linkerd.io"), kind: Some("Server"), namespace: Some("customer1"), name: "mfgx-backend-svc-orchestration-worker-primary", section_name: None, port: None }, controller_name: "linkerd.io/policy-controller", conditions: [Condition { last_transition_time: Time(2024-02-18T17:09:55Z), message: "", observed_generation: None, reason: "Accepted", status: "True", type_: "Accepted" }] }] } }) })
2024-02-18T17:21:22.345021Z DEBUG httproutes.policy.linkerd.io: linkerd_policy_controller_k8s_index::outbound::index: indexing route name="mfgx-backend-svc-orchestration-worker-primary-route"
2024-02-18T17:21:22.345092Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: attempting to decode a frame
2024-02-18T17:21:22.345108Z TRACE hyper::proto::h1::decode: decode; state=Chunked(BodyCr, 0)
2024-02-18T17:21:22.345113Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.345176Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Chunked(Size, 0)), writing: KeepAlive, keep_alive: Busy }
2024-02-18T17:21:22.345199Z TRACE hyper::proto::h1::conn: Conn::read_head
2024-02-18T17:21:22.345254Z TRACE hyper::proto::h1::io: received 1980 bytes
2024-02-18T17:21:22.345265Z TRACE parse_headers: hyper::proto::h1::role: Response.parse bytes=1980
2024-02-18T17:21:22.345274Z TRACE parse_headers: hyper::proto::h1::role: Response.parse Complete(376)
2024-02-18T17:21:22.345293Z DEBUG hyper::proto::h1::io: parsed 8 headers
2024-02-18T17:21:22.345307Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1604 bytes)
2024-02-18T17:21:22.345318Z TRACE hyper::proto::h1::decode: decode; state=Length(1604)
2024-02-18T17:21:22.345322Z DEBUG hyper::proto::h1::conn: incoming body completed
2024-02-18T17:21:22.345330Z TRACE hyper::proto::h1::conn: maybe_notify; read_from_io blocked
2024-02-18T17:21:22.345385Z TRACE want: signal: Want    
2024-02-18T17:21:22.345396Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
2024-02-18T17:21:22.345405Z TRACE want: signal: Want    
2024-02-18T17:21:22.345408Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
2024-02-18T17:21:22.345427Z TRACE status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer1/httproutes/mfgx-backend-svc-orchestration-worker-primary-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: put; add idle connection for ("https", 10.100.0.1)
2024-02-18T17:21:22.345445Z DEBUG status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer1/httproutes/mfgx-backend-svc-orchestration-worker-primary-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: pooling idle connection for ("https", 10.100.0.1)
2024-02-18T17:21:22.345569Z TRACE status::Controller: tower::buffer::service: sending request to buffer worker
2024-02-18T17:21:22.345580Z TRACE tower::buffer::worker: worker polling for next message
2024-02-18T17:21:22.345584Z TRACE tower::buffer::worker: processing new request
2024-02-18T17:21:22.345588Z TRACE status::Controller: tower::buffer::worker: resumed=false worker received request; waiting for service readiness
2024-02-18T17:21:22.345593Z DEBUG status::Controller: tower::buffer::worker: service.ready=true processing request
2024-02-18T17:21:22.345605Z TRACE status::Controller: tower::buffer::worker: returning response future
2024-02-18T17:21:22.345610Z TRACE tower::buffer::worker: worker polling for next message
2024-02-18T17:21:22.345631Z DEBUG status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer2/httproutes/mfgx-backend-svc-package-management-health-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: kube_client::client::builder: requesting
2024-02-18T17:21:22.345642Z TRACE status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer2/httproutes/mfgx-backend-svc-package-management-health-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: take? ("https", 10.100.0.1): expiration = Some(90s)
2024-02-18T17:21:22.345651Z DEBUG status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer2/httproutes/mfgx-backend-svc-package-management-health-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: reuse idle connection for ("https", 10.100.0.1)
2024-02-18T17:21:22.345671Z TRACE encode_headers: hyper::proto::h1::role: Client::encode method=PATCH, body=Some(Known(491))
2024-02-18T17:21:22.346010Z TRACE hyper::proto::h1::io: buffer.flatten self.len=1400 buf.len=491
2024-02-18T17:21:22.346070Z DEBUG hyper::proto::h1::io: flushed 1891 bytes
2024-02-18T17:21:22.346075Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
2024-02-18T17:21:22.353433Z TRACE hyper::proto::h1::decode: decode; state=Chunked(Size, 0)
2024-02-18T17:21:22.353461Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.353507Z TRACE hyper::proto::h1::io: received 1656 bytes
2024-02-18T17:21:22.353514Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.353517Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.353519Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.353523Z TRACE hyper::proto::h1::decode: Chunk size is 1649
2024-02-18T17:21:22.353528Z DEBUG hyper::proto::h1::decode: incoming chunked header: 0x671 (1649 bytes)
2024-02-18T17:21:22.353532Z TRACE hyper::proto::h1::decode: Chunked read, remaining=1649
2024-02-18T17:21:22.353541Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Chunked(BodyCr, 0)), writing: KeepAlive, keep_alive: Busy }
2024-02-18T17:21:22.353565Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: attempting to decode a frame
2024-02-18T17:21:22.353574Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: attempting to decode a frame
2024-02-18T17:21:22.353649Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: frame decoded from buffer
2024-02-18T17:21:22.353901Z TRACE httproutes.policy.linkerd.io: kubert::index: event=Applied(HttpRoute { metadata: ObjectMeta { annotations: Some({"meta.helm.sh/release-name": "mfgx-customer2", "meta.helm.sh/release-namespace": "customer2"}), cluster_name: None, creation_timestamp: Some(Time(2023-05-11T15:21:09Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(1), labels: Some({"app.kubernetes.io/managed-by": "Helm"}), managed_fields: Some([ManagedFieldsEntry { api_version: Some("policy.linkerd.io/v1beta1"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:metadata": Object {"f:annotations": Object {".": Object {}, "f:meta.helm.sh/release-name": Object {}, "f:meta.helm.sh/release-namespace": Object {}}, "f:labels": Object {".": Object {}, "f:app.kubernetes.io/managed-by": Object {}}}, "f:spec": Object {".": Object {}, "f:parentRefs": Object {}, "f:rules": Object {}}})), manager: Some("Go-http-client"), operation: Some("Update"), time: Some(Time(2023-05-11T15:21:09Z)) }, ManagedFieldsEntry { api_version: Some("policy.linkerd.io/v1beta3"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:status": Object {".": Object {}, "f:parents": Object {}}})), manager: Some("policy.linkerd.io"), operation: Some("Update"), time: Some(Time(2024-02-18T17:21:22Z)) }]), name: Some("mfgx-backend-svc-package-management-health-route"), namespace: Some("customer2"), owner_references: None, resource_version: Some("1495930534"), self_link: None, uid: Some("db54b4e7-ddb3-460f-9e46-901672337e31") }, spec: HttpRouteSpec { inner: CommonRouteSpec { parent_refs: Some([ParentReference { group: Some("policy.linkerd.io"), kind: Some("Server"), namespace: None, name: "mfgx-backend-svc-package-management-primary", section_name: None, port: None }]) }, hostnames: None, rules: Some([HttpRouteRule { matches: Some([HttpRouteMatch { path: Some(PathPrefix { value: "/health" }), headers: None, query_params: None, method: Some("GET") }]), filters: None, backend_refs: None, timeouts: None }]) }, status: Some(HttpRouteStatus { inner: RouteStatus { parents: [RouteParentStatus { parent_ref: ParentReference { group: Some("policy.linkerd.io"), kind: Some("Server"), namespace: Some("customer2"), name: "mfgx-backend-svc-package-management-primary", section_name: None, port: None }, controller_name: "linkerd.io/policy-controller", conditions: [Condition { last_transition_time: Time(2024-02-18T17:09:55Z), message: "", observed_generation: None, reason: "Accepted", status: "True", type_: "Accepted" }] }] } }) })
2024-02-18T17:21:22.354067Z DEBUG httproutes.policy.linkerd.io: linkerd_policy_controller_k8s_index::outbound::index: indexing route name="mfgx-backend-svc-package-management-health-route"
2024-02-18T17:21:22.354166Z TRACE httproutes.policy.linkerd.io: tokio_util::codec::framed_impl: attempting to decode a frame
2024-02-18T17:21:22.354189Z TRACE hyper::proto::h1::decode: decode; state=Chunked(BodyCr, 0)
2024-02-18T17:21:22.354195Z TRACE hyper::proto::h1::decode: Read chunk hex size
2024-02-18T17:21:22.354211Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Chunked(Size, 0)), writing: KeepAlive, keep_alive: Busy }
2024-02-18T17:21:22.354234Z TRACE hyper::proto::h1::conn: Conn::read_head
2024-02-18T17:21:22.354271Z TRACE hyper::proto::h1::io: received 1996 bytes
2024-02-18T17:21:22.354280Z TRACE parse_headers: hyper::proto::h1::role: Response.parse bytes=1996
2024-02-18T17:21:22.354290Z TRACE parse_headers: hyper::proto::h1::role: Response.parse Complete(376)
2024-02-18T17:21:22.354309Z DEBUG hyper::proto::h1::io: parsed 8 headers
2024-02-18T17:21:22.354317Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1620 bytes)
2024-02-18T17:21:22.354327Z TRACE hyper::proto::h1::decode: decode; state=Length(1620)
2024-02-18T17:21:22.354333Z DEBUG hyper::proto::h1::conn: incoming body completed
2024-02-18T17:21:22.354498Z TRACE hyper::proto::h1::conn: maybe_notify; read_from_io blocked
2024-02-18T17:21:22.354548Z TRACE want: signal: Want    
2024-02-18T17:21:22.354555Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
2024-02-18T17:21:22.354562Z TRACE want: signal: Want    
2024-02-18T17:21:22.354566Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
2024-02-18T17:21:22.354582Z TRACE status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer2/httproutes/mfgx-backend-svc-package-management-health-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: put; add idle connection for ("https", 10.100.0.1)
2024-02-18T17:21:22.354592Z DEBUG status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer2/httproutes/mfgx-backend-svc-package-management-health-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: pooling idle connection for ("https", 10.100.0.1)
2024-02-18T17:21:22.354694Z TRACE status::Controller: tower::buffer::service: sending request to buffer worker
2024-02-18T17:21:22.354709Z TRACE tower::buffer::worker: worker polling for next message
2024-02-18T17:21:22.354713Z TRACE tower::buffer::worker: processing new request
2024-02-18T17:21:22.354718Z TRACE status::Controller: tower::buffer::worker: resumed=false worker received request; waiting for service readiness
2024-02-18T17:21:22.354723Z DEBUG status::Controller: tower::buffer::worker: service.ready=true processing request
2024-02-18T17:21:22.354733Z TRACE status::Controller: tower::buffer::worker: returning response future
2024-02-18T17:21:22.354770Z TRACE tower::buffer::worker: worker polling for next message
2024-02-18T17:21:22.354795Z DEBUG status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer3/httproutes/mfgx-backend-svc-package-management-primary-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: kube_client::client::builder: requesting
2024-02-18T17:21:22.354809Z TRACE status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer3/httproutes/mfgx-backend-svc-package-management-primary-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: take? ("https", 10.100.0.1): expiration = Some(90s)
2024-02-18T17:21:22.354817Z DEBUG status::Controller:HTTP{http.method=PATCH http.url=https://10.100.0.1/apis/policy.linkerd.io/v1beta3/namespaces/customer3/httproutes/mfgx-backend-svc-package-management-primary-route/status?&fieldManager=policy.linkerd.io otel.name="patch_status" otel.kind="client"}: hyper::client::pool: reuse idle connection for ("https", 10.100.0.1)
2024-02-18T17:21:22.354912Z TRACE encode_headers: hyper::proto::h1::role: Client::encode method=PATCH, body=Some(Known(491))
2024-02-18T17:21:22.354935Z TRACE hyper::proto::h1::io: buffer.flatten self.len=1400 buf.len=491
2024-02-18T17:21:22.354961Z DEBUG hyper::proto::h1::io: flushed 1891 bytes
2024-02-18T17:21:22.354965Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
```

### output of `linkerd check -o short`

```
$ linkerd check -o short --linkerd-namespace kube-system
Status check results are √
```

### Environment

Kubernetes version: 1.26
Cluster environment: EKS
Host OS: Amazon Linux (RHEL)
Linkerd vesrion: 2.14.9

### Possible solution

_No response_

### Additional context

Memory usage graph:
image

Kube manifest for one of the HttpRoute resources in question:
```yaml
Name:         mfgx-backend-svc-transformation-health-route
Namespace:    customer1
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: mfgx-customer1
              meta.helm.sh/release-namespace: customer1
API Version:  policy.linkerd.io/v1beta3
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2023-05-11T15:17:57Z
  Generation:          1
  Resource Version:    1496020292
  UID:                 a18469f8-4b5c-4bcb-b790-69ce2cbb8a19
Spec:
  Parent Refs:
    Group:  policy.linkerd.io
    Kind:   Server
    Name:   mfgx-backend-svc-transformation-primary
  Rules:
    Matches:
      Method:  GET
      Path:
        Type:   PathPrefix
        Value:  /health
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-02-18T17:28:01Z
      Message:
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Controller Name:         linkerd.io/policy-controller
    Parent Ref:
      Group:      policy.linkerd.io
      Kind:       Server
      Name:       mfgx-backend-svc-transformation-primary
      Namespace:  customer1
Events:           <none>
```

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by adleong**
Fixes #12104

The leader of the policy controllers (as determined by a lease resource) is in charge of keeping the HttpRoute resource statuses up to date.  To accomplish this, it performs reconciliation every 10 seconds where it computes the desired status for each HttpRoute and patches the resource.  When there are many HttpRoute resources in the cluster, most of which change infrequently, this results in a large number of redundant no-op patches: one per HttpRoute every 10 seconds.

These patches are stored in an in-memory unbounded queue while waiting to be dispatched to the Kube API.  If the rate that these patches are generated exceeds the rate that the Kube API can process them (synchronously) then this queue will grow without bound, resulting in a memory leak.

To address this we do two things:
* Use a bounded queue of size 10000. If the queue fills up, patches will be dropped.  Statuses will be reconciled in a later iteration of the reconciliation loop once there is queue capacity.
* Only generate a patch when the desired status differs from the current status.  This greatly reduces the number of patches generated.

TODO in follow up PRs:
* Add timeout and metrics to the Kube API patch calls
* Add queue metrics for enqueues, dequeues, dropped patches, and avg queue depth

### CODE REVIEW

File: policy-controller/src/main.rs [hunk 1]
```diff
@@ -159,8 +164,9 @@ async fn main() -> Result<()> {
 
     // Build the status index which will maintain information necessary for
     // updating the status field of policy resources.
-    let (updates_tx, updates_rx) = mpsc::unbounded_channel();
-    let status_index = status::Index::shared(hostname.clone(), claims.clone(), updates_tx);
+    let (updates_tx, updates_rx) = mpsc::channel(10000);
```
Comment (alpeb) [inline policy-controller/src/main.rs:167]: Better to make this a constant to make it more visible? Also can you share the reasoning behind the number? As a point of comparison, in the endpoint translator the bounded queue size is just 100.

Comment (adleong) [reply policy-controller/src/main.rs:167]: queue size was picked mostly arbitrarily.  I wanted this to be big enough to hold the most patches we could possibly process in a 10 second interval (the frequency of reconciles).  If it took 1ms to apply a patch, this would be 10000.  Very conservative estimate.

File: policy-controller/k8s/status/src/index.rs [hunk 2]
```diff
@@ -114,8 +131,14 @@ impl Controller {
...
-                    tracing::debug!("Lease holder has changed");
                     let claim = self.claims.borrow_and_update();
+                    match (self.leader, claim.is_current_for(&self.name)) {
+                        (true, false) =>
+                            tracing::debug!("Lease holder has changed; no longer the leader"),
+                        (false, true) =>
+                            tracing::debug!("Lease holder has changed; now the leader"),
+                        _ => {}
+                    }
                     self.leader = claim.is_current_for(&self.name);
```
Comment (olix0r) [inline policy-controller/k8s/status/src/index.rs:142]:
```suggestion
                    let was_leader = self.leader;
                    self.leader = claim.is_current_for(&self.name);
                    if was_leader != self.leader {
                        tracing::debug!(leader = %self.leader, "Leadership changed");
                    } else {
                        tracing::trace!(leader = %self.leader, "Leadership unchanged");
                    }
```

File: policy-controller/k8s/status/src/index.rs [hunk 3]
```diff
@@ -303,24 +332,30 @@ impl Index {
...
-                patch,
-            }) {
-                tracing::error!(%id.namespace, route = ?id.gkn, %error, "Failed to send HTTPRoute patch")
+            if let Some(patch) = self.make_http_route_patch(id, route) {
+                if let Err(error) = self.updates.try_send(Update {
+                    id: id.clone(),
+                    patch,
+                }) {
+                    tracing::error!(%id.namespace, route = ?id.gkn, %error, "Failed to send HTTPRoute patch")
+                }
```
Comment (olix0r) [inline policy-controller/k8s/status/src/index.rs:358]: I don't think it's useful to log the error message here. There are specifically two kinds of errors we can hit:

* The receiver has been dropped, in which case we have no reason to log or do any further work.
* The channel is at capacity.

If the channel is at capacity, what should we do? I assume we'll typically continue to log errors for each and every route. Is that desirable?

We could also use [`Sender::reserve()`](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.reserve) to eagerly ensure the channel has capacity.

```suggestion
            let Ok(tx) = match self.updates.reserve() else {
                tracing::error!("Cannot process additional status updates.")
                return;
            };
            if let Some(patch) = self.make_http_route_patch(id, route) {
                tx.send(Update {
                    id: id.clone(),
                    patch,
                });
```

But should we go further? If we can't actually process status updates, should we relinquish our claim on the release?

File: policy-controller/src/main.rs (hunk 1 above)
Comment (olix0r) [reply policy-controller/src/main.rs:167]: I do think that we should document this relationship. I'd also really like it if we could extract [this hardcoded 10s timeout](https://github.com/linkerd/linkerd2/blob/6e630e09fdd14e5da8d4d4db23900b9e03c55796/policy-controller/k8s/status/src/index.rs#L201) so that it's configured from the main. That way we can specify both of these constants in the same place -- ideally, up at the top of the file with the rest of the consts.

File: policy-controller/k8s/status/src/index.rs (hunk 2 above)
Comment (adleong) [reply policy-controller/k8s/status/src/index.rs:142]: Even at trace level, logging that leadership is unchanged every 10s does not seem particularly useful.

File: policy-controller/k8s/status/src/index.rs (hunk 3 above)
Comment (adleong) [reply policy-controller/k8s/status/src/index.rs:358]: With the changes in this PR, we do not expect this queue to ever fill up under normal conditions.  It should only run out of capacity in pathological cases like if there is an extremely high rate of real status changes or if the Kube API becomes extremely slow, unreachable, or we're unable to process patches for some other reason.  In any of those cases, I think the log messages are helpful so that we can see that we're in such a pathological case.  If the channel is at capacity we will log an error for each route which does not match its desired state, every 10 seconds, until capacity becomes available.

Comment (adleong) [reply policy-controller/k8s/status/src/index.rs:358]: What is the benefit to using reserve? Is this to be able to skip doing the work of building the patch if capacity is not available?  Not sure, but this seems like a premature optimization.

Comment (adleong) [reply policy-controller/k8s/status/src/index.rs:358]: Relinquishing the claim if we can't process status updates sounds like a more robust behavior but it's also a larger change that isn't necessary to fix the immediate issue.  I'd like to punt on that and say that pathological cases where we're unable to process status updates need to be remediated manually.

File: policy-controller/k8s/status/src/index.rs [hunk 4]
```diff
@@ -132,12 +132,10 @@ impl Controller {
...
-                            tracing::debug!("Lease holder has changed; no longer the leader"),
-                        (false, true) =>
-                            tracing::debug!("Lease holder has changed; now the leader"),
-                        _ => {}
+                    let was_leader = self.leader;
+                    self.leader = claim.is_current_for(&self.name);
+                    if was_leader != self.leader {
+                        tracing::debug!(leader = %self.leader, "Leadership changed");
                     }
                     self.leader = claim.is_current_for(&self.name);
```
Comment (olix0r) [inline policy-controller/k8s/status/src/index.rs:140]: this is redundant now

File: policy-controller/k8s/status/src/index.rs [hunk 5]
```diff
@@ -114,9 +131,12 @@ impl Controller {
...
-                    tracing::debug!("Lease holder has changed");
                     let claim = self.claims.borrow_and_update();
+                    let was_leader = self.leader;
                     self.leader = claim.is_current_for(&self.name);
+                    if was_leader != self.leader {
+                        tracing::debug!(leader = %self.leader, "Leadership changed");
+                    }
                 }
                 // If this policy controller is not the leader, it should
                 // process through the updates queue but not actually patch
```
Comment (olix0r) [inline policy-controller/k8s/status/src/index.rs:142]: I can't quite comment on the line I want, but this comment here does not accurately reflect what this code does, and that is a subtle bug lurking:

```rust
                Some(Update { id, patch}) = self.updates.recv(), if self.leader => {
```

This condition mans that we will only ever check the channel if we are currently the leader. This means that if there is a leadership change (and we lose leadership), the channel can end up holding patches indefinitely, and when leadership is resumed we'll process very old patches. This if condition must be moved within the body of the block, and we should drop updates while we're not the leader.

**Review by olix0r — COMMENTED** [review]
I've refreshed myself on the current state of the status manager and a few
(pre-existing) issues stand out that I think we should take this change into
consideration:

1. Nothing constrains how long a patch operation may take. You've noted that the
   Kubernetes API being very slow is pathological and that can lead to issues
   that would cause this controller to back up. This raises a few important
   issues:
   * We need to bound this with a timeout so that we can properly size the queue.
   * We should measure the histogram of patch durations.
   * We should countthe number of failures (including timeouts).
2. The receiver only processes updates while it is the leader. This means that
   if a process loses leadership while patches are enqueued, they will remain in
   the queue until the process regains leadership, and then the very old patches
   will be applied.
   * We need to continue processing patches, even if we lose leadership.
   * We should count the number of patches that are dropped.
3. I'm wary about getting into an unhealthy state where the controller does
   nothing but emit error messages for every resource it encounters. If we fail
   fast, we can communicate more generally that reconcilation has been halted
   because the buffer is at capacity.
4. The queue size metric, as implemented here, is of limited use: (1) the value
   is only updated before reconcilation starts, and (2) it will then be sampled
   by readers of the /metrics endpoint. The first issue is easy to avoid, but I
   also think this would be an excellent use of a Peak-EWMA measurement to avoid
   the latter as well.

I recognize that we'll probably want to merge parts of this in discrete PRs. Perhaps we split this PR itself into one that _only_ changes the mpsc type, and we can address these other (required, imo) fixes in additional discrete changes?

File: policy-controller/k8s/status/src/index.rs [hunk 6]
```diff
@@ -114,23 +111,29 @@ impl Controller {
...
-                    } else if id.gkn.group == k8s_gateway_api::HttpRoute::group(&()) {
-                        let api = k8s::Api::<k8s_gateway_api::HttpRoute>::namespaced(self.client.clone(), &id.namespace);
-                        if let Err(error) = api.patch_status(&id.gkn.name, &patch_params, &patch).await {
-                            tracing::error!(namespace = %id.namespace, route = ?id.gkn, %error, "Failed to patch HTTPRoute");
+
+                Some(Update { id, patch}) = self.updates.recv() => {
+                    // If this policy controller is not the leader, it should
+                    // process through the updates queue but not actually patch
+                    // any resources.
+                    if self.leader {
```
Comment (olix0r) [inline policy-controller/k8s/status/src/index.rs:126]: It may be desirable to log debug messages when we drop events.

**Review by olix0r — APPROVED** [review]
