### PR TITLE
Display more helpful websocket errors

### LINKED ISSUE #1599: Display more helpful websocket errors
The UI often displays websocket errors with no explanation if the server has disconnected and hasn't provided a close reason. We should come up with a nicer error message, e.g. "Websocket disconnected" for the common 1006 error we encounter.

To reproduce: disconnect from the public api, or throw some websocket errors from the server.

### PR DESCRIPTION
**Pull request by siggy**
The web client displays `Websocket [code]` on websocket close errors.

Modify the web client to render a more helpful error message to the
user. If a reason is present, render that, otherwise translate the
websocket error code into a message.

Fixes #1599

Signed-off-by: Andrew Seigner <siggy@buoyant.io>

screen shot 2018-09-11 at 2 08 11 pm

### CODE REVIEW

File: web/app/js/components/Tap.jsx [hunk 1]
```diff
@@ -83,15 +104,15 @@ class Tap extends React.Component {
     if (!e.wasClean) {
       this.setState({
         error: {
-          error: `Websocket [${e.code}] ${e.reason}`
+          error: `Websocket close error: [${e.code}] ${e.reason ? e.reason : wsCloseCodes[e.code]}`
```
Comment (rmars) [inline web/app/js/components/Tap.jsx]: Since the websocket codes are less known that http status codes, it might be worth displaying the text all the time here, like
```
error: `Websocket close error [${e.code}: ${wsCloseCodes[e.code]}] ${e.reason ? ":" : ""} ${e.reason}`
```

File: web/app/js/components/Tap.jsx [hunk 2]
```diff
@@ -11,6 +11,27 @@ import { httpMethods, processTapEvent, setMaxRps } from './util/TapUtils.jsx';
 import './../../css/tap.css';
 
 const maxNumFilterOptions = 12;
+
+// from https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
```
Comment (rmars) [inline web/app/js/components/Tap.jsx]: There's similar websocket error handling in `TopModule.jsx`. It might be good to put this into `TapUtils.jsx` and then we can do the same error handling there.

Comment (siggy) [reply web/app/js/components/Tap.jsx]: screen shot 2018-09-12 at 10 09 57 am

File: web/app/js/components/Tap.jsx (hunk 1 above)
Comment (siggy) [reply web/app/js/components/Tap.jsx]: screen shot 2018-09-12 at 10 09 31 am
