### PR TITLE
Fix routes wide output formatting for empty values

### LINKED ISSUE #4216: incorrect formatting of empty values in routes wide output
Empty values are not formatted correctly in the `LATENCY_P95` and `LATENCY_P99` columns of the wide `linkerd routes` output.  These empty values should be formatted as a dash `-` but instead are completely blank.

```
linkerd routes deploy/books --to deploy/authors -o wide -t 30s
ROUTE                          SERVICE   EFFECTIVE_SUCCESS   EFFECTIVE_RPS   ACTUAL_SUCCESS   ACTUAL_RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
DELETE /authors/{id}.json      authors                   -               -                -            -             -
GET /authors.json              authors                   -               -                -            -             -
GET /authors/{id}.json         authors                   -               -                -            -             -
HEAD /authors/{id}.json        authors             100.00%          2.0rps            0.00%       0.0rps           6ms   18ms   20ms
POST /authors.json             authors                   -               -                -            -             -
[DEFAULT]                      authors                   -               -                -            -             -
[DEFAULT]                   kubernetes                   -               -                -            -             -
```

Linkerd version edge-20.3.4

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #4216 

Adds a wider templating string which is used when `outputActual` is enabled

Output:
```bash
./bin/go-run cli routes deploy/vote-bot --to service/web-svc -n emojivoto -o wide
ROUTE           SERVICE   EFFECTIVE_SUCCESS   EFFECTIVE_RPS   ACTUAL_SUCCESS   ACTUAL_RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
GET /api/list   web-svc             100.00%          1.0rps          100.00%       1.0rps           3ms           9ms          10ms
GET /api/vote   web-svc              81.36%          1.0rps           81.36%       1.0rps           4ms          15ms          19ms
[DEFAULT]       web-svc                   -               -                -            -             -             -             -

```

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

File: cli/cmd/routes.go [hunk 1]
```diff
@@ -233,7 +234,11 @@ func printRouteTable(stats []*routeRowStats, w *tabwriter.Writer, options *route
 
 			fmt.Fprintf(w, templateString, values...)
 		} else {
-			fmt.Fprintf(w, emptyTemplateString, values...)
+			if outputActual {
+				fmt.Fprintf(w, emptyWideTemplateString, values...)
+			} else {
+				fmt.Fprintf(w, emptyTemplateString, values...)
+			}
```
Comment (kleimkuhler) [inline cli/cmd/routes.go:241]: Instead of checking `outputActual` for each row in the stats, can we just check it once above and set the template string based off that?:
```
var emptyTemplateString string
if outputActual {
    emptyTemplateString = routeTemplate + "\t%s\t-\t-\t-\t-\t-\t-\t-\t\n"
} else {
    emptyTemplateString = routeTemplate + "\t%s\t-\t-\t-\t-\t-\t\n"
}
..
```

Comment (Pothulapati) [reply cli/cmd/routes.go]: Yep, Great suggestion. Updated. :)
